bazel-contrib/rules_scala

- scala/scala.bzl
this started failing today prompting:
https://github.com/bazelbuild/bazel/issues/969
quickfix here.
Review @dinowernli
> Change the scala compiler download to https

- README.md
- scala/scala.bzl
- test/BUILD
In using the scala rules for a short time, we have already seen several instances of people forgetting to update the suites attribute.
This changes to always run all tests in the target, print the timing for each test in the target (in the standard out) as well as full stack traces of errors.
what do you think @dinowernli
> deprecate scala_test suites

- WORKSPACE
- scala/scala.bzl
- test/BUILD
this is related to #14 
We give a function `scala_version` and a `scala_mvn_artifact` that can be used in name mangling for scala jars. This can help deal with making WORKSPACES less tied to a particular version of scala.
> Add scala_version function

- scala/scala.bzl
this copies the fix from #27 while we wait for a CLA to be signed.
The problem is the scala rule was assuming that bazel started it in a clean directory, which is evidently not the case, so we can see the output from previous runs if we are not careful.
This fixes that by removing the directory used to make the jar.
> Remove output directory between making jars

- scala/scala.bzl
- test/src/main/scala/scala/test/disappearing_class/BUILD
- test/src/main/scala/scala/test/disappearing_class/ClassProvider.scala
- test/src/main/scala/scala/test/disappearing_class/UsesClass.scala
- test_run.sh
We came across a case where deleting a class would let the Downstreams using it still compile. This should highlight that bad case
> Add disappearing class test

- test/src/main/scala/scala/test/twitter_scrooge/thrift/BUILD
- test/src/main/scala/scala/test/twitter_scrooge/thrift/Thrift1.thrift
- test/src/main/scala/scala/test/twitter_scrooge/thrift/thrift2/BUILD
- test/src/main/scala/scala/test/twitter_scrooge/thrift/thrift2/Thrift2_A.thrift
- test/src/main/scala/scala/test/twitter_scrooge/thrift/thrift2/Thrift2_B.thrift
- test/src/main/scala/scala/test/twitter_scrooge/thrift/thrift2/thrift3/BUILD
- test/src/main/scala/scala/test/twitter_scrooge/thrift/thrift2/thrift3/Thrift3.thrift
- thrift/thrift.bzl
https://github.com/bazelbuild/rules_scala/pull/29
This adds the thrift_library rule. This will be used and more thoroughly tested in a followup PR with codegen that depends on this
> add support for thrift_library to organize .thrift files

- thrift/thrift.bzl
I had forgotten to make the jar a dependency (via the action's input) of the thrift action, so the sandbox was hiding it.
> Fix thrift target in sandbox

- thrift/thrift.bzl
This should fix the issue that came up after the fact here
https://github.com/bazelbuild/rules_scala/pull/36
@damienmg, thank you for pointing this out! A question to mull over with @johnynek: how can we avoid this?
Is there an issue if we set up the automatic CI to run on different architectures? Is it a cost concern?
Also, any word on sandboxing in OSX? I see this https://github.com/bazelbuild/bazel/issues/902, but there's not code or anything.
> Make jdk dependency explicit

- scala/scala.bzl
Bazel HEAD has removed //tools/defaults:ijar, rules should
now depends on @bazel_tools//tools/jdk:ijar.
> Fix scala rules with bazel HEAD

- scala/scala.bzl
I'm not sure why, but they don't seem to work inside the args file
specified with `@file`. Fortunately, only the classpath/input args
should actually be huge.
> Move scalacopts and jvm_flags out of the args file

- WORKSPACE
- scala/scala.bzl
- test/BUILD
- test/HelloLib.scala
- thrift/thrift.bzl
- twitter_scrooge/twitter_scrooge.bzl
This seems to work to add plugins.
Only tested with existing ones, but it *should* work for plugins in the repo as well.
It it not clear to me what the classpath for plugins is (do they need to be fat jars, or does it share a classpath with compilation?)
This seems to work.
review? @smparkes @dinowernli @jcoveney
> Add support for scalac compiler plugins

- scala/scala.bzl
@unlikely-leo @johnynek @smparkes
> Remove the baked-in akka library from the scalasdk filegroup.

- .bazel-installer-linux-x86_64.sh.sha256
- .travis.yml
- README.md
- scala/scala.bzl
due to the path changes in bazel 0.2.3, the plugin needs to be updated.
> change script to support 0.2.3

- scala/scala.bzl
That way, a java_binary pulling it in will have scala-lang on the classpath.
> scala-lang should be a runtime dependency of any scala_library

- scala/scala.bzl
"Deployable" Jars, as created by the java_binary rule, are Jars with all runtime dependencies included. These are usable as standalone Jars that can be deployed onto servers and such. The reason why we need these for Scala binaries and libraries is as a bandaid fix for Java/Scala interop in Bazel. The Java ecosystem of rules is closed: AFAICT, only known-good rules (cc_library, java_library, java_import, ...) can be used as dependencies of java libraries and binaries. To work around this, the scala_export_to_java macro injects scala into the java ecosystem via "precompiled" jars in the java_imports rule. However, this rule does not pick up transitive runtime dependencies of the imported Jars, so when using these Jars in java_tests, the tests fail because they do not have access to the …
> Fix deployable JARs created by Scala rules.

- scala/scala.bzl
This seems to reduce build time for `bazel build test/...` from 80 seconds to about 55 seconds on my machine. I *think* it is because it is not building the deploy jar for libraries unless needed after this change (or that is my intent). I only see 4 deploy jars created after this change, but 12 without it.
My hope is that `_deploy.jar` becomes an implicit output and is not created unless specifically requested (to the cost of creating deploy jars being quite large).
@smparkes @dinowernli
> Add a default output to scala_library

- scala/scala.bzl
- src/java/io/bazel/rulesscala/jar/BUILD
- src/java/io/bazel/rulesscala/jar/JarCreator.java
- src/java/io/bazel/rulesscala/jar/JarHelper.java
- test_run.sh
This is to address #53 
This adds a jar creator that is a minor edit of:
https://github.com/bazelbuild/bazel/blob/master/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/jarhelper/JarCreator.java
to remove the unneeded guava dependency (so it would build easier), which sets the timestamps to fixed values, which makes the jars pure functions of the contents.
> Check that jar output is byte-for-byte identical

- scala/scala.bzl
_java.path was (incidentally) working, but is now broken. short_path is
for paths relative to the runfiles tree.
This fixes ci.bazel.io's rules_closure project. See https://github.com/bazelbuild/bazel/issues/1316 for more info.
> Use short_path for runfiles paths

- scala/scala.bzl
- test/BUILD
- test/HelloLibTest.scala
- test_run.sh
actually, starting repls for test code and binaries is really useful, so I added support for that as well. This is done by making the binary targets return their deps correctly.
> Add repl support to binary and test targets

- test_expect_failure/transitive/java_to_scala/BUILD
- test_expect_failure/transitive/scala_to_java/BUILD
- test_expect_failure/transitive/scala_to_scala/BUILD
- test_run.sh
This prevents from building failing targets with `bazel build //...`.
Fixes #73.
> Set failing build to manual

- README.md
Hi,
I might be wrong here but I think the main_class property is required for the scala_binary rule.
The doc also says `A scala_binary requires a main_class attribute.` but the attribute says its optional.
I updated to say It's mandatory.
> Updated the readme to say main_class is required for scala_binary

- CONTRIBUTORS
- scala/scala.bzl
- twitter_scrooge/twitter_scrooge.bzl
I've mirrored your files for guaranteed reliability, courtesy of Google Cloud Storage.
In the future, you can mirror these files too with the following command. Although you need to ask @damienmg for write access to the bucket. Or just email me the URL you want mirrored and I'll happily do it.
```bash
bzmirror() {
local url="${1:?url}"
if [[ "${url}" =~ ^([^:]+):([^:]+):([^:]+)$ ]]; then
url="http://repo1.maven.org/maven2/${BASH_REMATCH[1]//.//}/${BASH_REMATCH[2]}/${BASH_REMATCH[3]}/${BASH_REMATCH[2]}-${BASH_REMATCH[3]}.jar"
fi
local dest="gs://bazel-mirror/${url#http*//}"
local desturl="http://bazel-mirror.storage.googleapis.com/${url#http*//}"
local name="$(basename "${dest}")"
wget -O "/tmp/${name}" "${url}" || return 1
gsutil cp -a public-read "/tmp/${name}" "${dest}" || return 1 …
```
> Use Bazel mirror to download externals

- scala/scala.bzl
- src/java/io/bazel/rulesscala/jar/JarCreator.java
- src/java/io/bazel/rulesscala/jar/JarHelper.java
This does not pass the zip contents through the file system and makes deploy jar creation part a executable action. It should be both faster, but also safer for creation of deploy jars on linux systems (such as Docker or with encrypted home directories) that often have limited file lengths that might be violated by jars.
review? @ianoc @ittaiz ?
> improve the deploy jar creation

- thrift/thrift.bzl
The problem is that the path is not the same when remote as local. The current fix:
1. makes sure that a prefix, if given, is an actual substring of the common prefix.
2. ignores anything *before* the prefix that matches. So it is like the regex `.*prefix(.*)$`.
The above two fixes make this rule usable in both local and remote contexts for me.
> Fix for thrift rule issue that manifests with remote repos

- scala/scala.bzl
bazel java binary targets have certain options:
https://github.com/bazelbuild/bazel/blob/c1b417549cf4ba719662f7562e99e807c606eae7/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt
use:
```bash
```
to set the jvm flags.
> Fix jvm_flag support

- thrift/thrift.bzl
`unzip` by default prints all the files. This creates a lot of noise for thrift targets.
> make thrift targets quieter

- src/java/io/bazel/rulesscala/scalac/ScalaCInvoker.java
I ran into errors that were killing the standalone workers. Seems the Exception catching we have wasn't picking up these types. Not sure how safe it is to pickup all throwables so i'm just going to focus on the one we know should be captured..
> Catch throwables from type errors

- scala/scala.bzl
Discovery starting.
Discovery completed in 126 milliseconds.
Run starting. Expected test count is: 1
DummyTest:
- Arithmetic *** FAILED *** (157 milliseconds)
2 did not equal 5 (DummyTest.scala:26)
org.scalatest.exceptions.TestFailedException:
at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)
at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1555)
at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)
at com.stripe.dummy.DummyTest$$anonfun$1.apply$mcV$sp(DummyTest.scala:26)
at com.stripe.dummy.DummyTest$$anonfun$1.apply(DummyTest.scala:14)
at com.stripe.dummy.DummyTest$$anonfun$1.apply(DummyTest.scala:14)
at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
at …
> scalatest runner options: switch to using shorter stack traces

- scala/scala.bzl
- thrift/thrift.bzl
This adds cfg settings to the executable labels (which 0.3.2 now warns about).
> Cleanup 0.3.2 warnings

- test/BUILD
testonly was not enforced in previous version of Bazel but this will
be fixed in the next version of Bazel. Correct it for rules_scala.
Tested with `bazel build ...`
Tracking bug: bazelbuild/bazel#1967
> Correctly set testonly to test targets

- README.md
Otherwise the commands will be improperly highlighted.
> Fix minor formatting issue in README.md

- .gitignore
- scala/scala.bzl
- src/java/io/bazel/rulesscala/scalac/CompileOptions.java
- src/java/io/bazel/rulesscala/scalac/ScalaCInvoker.java
- test/BUILD
... by making the param a list rather than a string.
Drive-by:
* Add a few bits and pieces to .gitignore.
* Add a repro-case to test/BUILD which validates the fix.
* Use a list of arguments rather than a string to invoke javac.
Addresses: https://github.com/bazelbuild/rules_scala/issues/99
@petemounce @johnynek @damienmg
> Fix the behavior of the jvm_flags param to support multiple params 

- test_run.sh
> Removing redundant second call of disappearing class test

- .bazelrc.travis
- README.md
- scala/scala.bzl
- src/java/io/bazel/rulesscala/scalac/CompileOptions.java
- src/java/io/bazel/rulesscala/scalac/ScalaCInvoker.java
- test/BUILD
- test/data/BUILD
- test/data/foo.txt
- test/data/more.txt
- test/src/main/resources/scala/test/BUILD
- test/src/main/resources/scala/test/more-byes
- test/src/main/resources/scala/test/more-hellos
- test/src/main/scala/scala/test/MoreScalaLibBinary.scala
- test/src/main/scala/scala/test/MoreScalaLibResources.scala
- test_run.sh
This will add a `resource_strip_prefix` option like the one in Java. If the `resource_strip_prefix` is defined, we will strip out the prefix from the resource file path and forms the new destination path for the resource files. We will also throw a runtime exception if any of the resource file mentioned in the rule doesn't belongs to the specified path (which is the default behavior in Java rule too)
> Adding a simple resource_strip_prefix option

- test/BUILD
- test/src/main/scala/scala/test/only_java/Alpha.java
- test_run.sh
Added an already passing test-target which shows support of targets with java only sources.
I think it has value even if it's already passing since at least currently this is a feature we want to support (until #970 in bazel itself is resolved) and I'd be calmer if there was any regression check for it.
Do you think an actual test is needed?
> Java only sources

- README.md
This will currently show as broken because rules scala is failing due to sandboxing since https://github.com/bazelbuild/rules_scala/commit/55156d5fe501c112983deff6e8065eec2b2b366e. Travis CI does not catch those errors.
> Add ci.bazel.io build status to the README

- src/scala/io/bazel/rules_scala/scrooge_support/BUILD
- src/scala/scripts/BUILD
- twitter_scrooge/twitter_scrooge.bzl
We use some binds, but not all. This uses only bind so users can fix the versions they need.
> Fix uses of bind for thrift rules

- README.md
Since test_run.sh fails on OS X I tried running `bazel test //...` and it took me some time until I remembered the problem with the failing folder. Added a small section in the readme about it.
> added instructions on building and testing from source

- .travis.yml
- test_run.sh
Previous travis ran only with bazel **0.3.2** and on **linux**.
This update makes sure travis will have 4 permutations:
- versions: **latest** (0.4.4) and **head**.
- platforms: **linux** and **osx**
#Notes:
- The source of this file is from `go_rules` adjusted to this repo
- I skipped all apt requirements but `libxml2-utils` that failed without it
- Those changes still don't solve issue #76 but will help test solutions to it
- I also added prints on duration of each test that is run by the test_run.sh
> travis to work on newer versions and on multiplatforms

- WORKSPACE
- jmh/jmh.bzl
- src/scala/io/bazel/rules_scala/jmh_support/BUILD
- src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala
- test/jmh/BUILD
- test/jmh/TestBenchmark.scala
- test_run.sh
This PR adds crude support for JMH benchmarks with a `scala_benchmark_jmh` target. To do this, it also allows compilation of Java sources in source JARs.
The meat of the logic to generate JMH benchmark code was cargo-culted from @tixxit's excellent SBT plug-in for JMH benchmarks:
https://github.com/tixxit/sbt-benchmark/blob/master/src/main/scala/net/tixxit/sbt/benchmark/BenchmarkPlugin.scala
- https://github.com/bazelbuild/rules_scala/issues/157
- https://github.com/bazelbuild/rules_scala/issues/150
Added a very simple JMH benchmark under `tests/jmh`.
r? @johnynek
> Add support for JMH benchmarks

- jmh/jmh.bzl
This small change to the `scala_benchmarks_jmh` macro should alleviate cross-repo build issues by ensuring that the labels for tools needed to generate benchmark code are scoped to `rules_scala` rather than the repo invoking the macro.
I ran into some issues building JMH benchmarks in another repository.
CI
r? @johnynek
> Move shared labels out of scala_benchmark_jmh

- test_run.sh
sh_test don't print the each test run output unless it fails.
If it fails - it prints the output without line breaks, which makes it really hard to understand whats going on.
This tiny addition will fix it and make sure the output will be printed with line breaks
> printing the output of failed sh_test run with line breaks

- jmh/jmh.bzl
- src/scala/io/bazel/rules_scala/jmh_support/BUILD
- src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala
- test/jmh/AddNumbers.scala
- test/jmh/BUILD
- test/jmh/JavaType.java
- test/jmh/ScalaType.scala
- test/jmh/TestBenchmark.scala
This PR properly gathers the dependencies for JMH benchmark generation. It uses a Skylark rule to assemble the runtime dependencies for the compiled library for which JMH will generate benchmark code. We need the runtime dependencies (rather than the `ijar` compile-only dependencies) since JMH's generators actually need to loaded classes depended upon.
We were failing to build benchmarks with dependencies on targets exported from the benchmarks' dependencies.
Added some Java and Scala dependencies to test target for JMH benchmarks.
r? @johnynek
> Transitive dependencies for JMH benchmarks

- scala/scala.bzl
- test/BUILD
- test/test_binary.sh
In trying to get these rules to work in other build environments
(with different locations and ways for building scalac, javac, etc.)
found that various bazel constructs were not being applied properly.
This commit tries to clean some of that up and make things slightly
more consistent and reliable.
Also, in general, the launchers for scala_test, scala_binary, and
scala_repl were not resilient to the various permutations of places that
Bazel will place your runfiles. In particular, a scala_binary could not
reliably be used in a genrule or shell test. Thus...
The biggest change is unifying the launcher for all three of the
executable rules (see _write_launcher). This borrows from the form in
the java_skylark rules to inspect itself and more reliably find its
runfiles. As a bonus, now all …
> Cleanup rules, esp. executables, to be more consistent

- scala/scala.bzl
The default @local_jdk just imports _java and _javac as raw binaries
without establishing a dependency on/runfiles of _jdk. Thus, all uses of
those should manually add _jdk as a dependency.
In the scalac execution ation that compiles scala, also added _jdk in
case _scalac ever was replaced by a binary that wasn't a java_binary.
Haven't been able to test locally in a hermetic system with the default local_jdk so should wait until CI green before integrating....
> Add _jdk dependency to binary runfiles and scalac action

- src/java/io/bazel/rulesscala/scalac/CompileOptions.java
- src/java/io/bazel/rulesscala/scalac/ScalaCInvoker.java
- src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
Removing unused imports, variables.
Properly typing the Enumeration meant no longer needed type-cast, which
is nice. Avoids implicit 'inference' of Enumneration<?> by javac which leads to 'fun'.
constParams removal because was dead code.
== is reference equality and .equals is potentially value equality.
> Some small fixes to the scalac infrastructure

- scala/scala.bzl
Need to get the bazel mirrors to work with the lightbend/version bump
Something like:
http://bazel-mirror.storage.googleapis.com/downloads.lightbend.com/scala/2.11.11/scala-2.11.11.tgz
I'd have expected to work.
> Bump scala-version

- scala/scala.bzl
- scala/support/BUILD
- src/java/com/google/devtools/build/lib/BUILD
- src/java/io/bazel/rulesscala/scalac/BUILD
- src/scala/io/bazel/rules_scala/jmh_support/BUILD
- src/scala/io/bazel/rules_scala/scrooge_support/BUILD
- src/scala/io/bazel/rules_scala/tut_support/BUILD
- src/scala/scripts/BUILD
Make all the deps use the bind targets.
My motivation for this is that we use:
https://github.com/johnynek/bazel-deps
to specify our maven dependencies and deal with updating the transitive versions at stripe. We'd rather pull all the jars just from maven than from the sdk. With the recent changes, that is now possible since we don't use the scala repl script any longer.
> Use consistent way of expressing external deps

- scala/scala.bzl
- test/BUILD
- test/aspect/aspect.bzl
- test_run.sh
- thrift/thrift.bzl
Many places were directly using file or files on various jars when
building up the classpaths. This was not resilient to later changing
those jars to being true java targets (and thus having runtime
dependencies).
Also, there was significant redundancy in the various scala rules each
analyzing their deps and runtime_deps to build up the compile and
runtime jar lists.
A new function _collect_jars_from_common_ctx has been created to reduce
this redundancy. This function looks at ctx.attr.deps and
ctx.attr.runtime_deps to build up compiletime and runtime jars. It also
assumes an automatic dependency on scala-reflect and scala-library.
(This allows eliminating weirdness where both those jars were being
separately added to the compiletime and runtime classpath.) All these
collections are via …
> Unified use of collect_jar and binary_common, other cleanups

- .travis.yml
Around a week ago Bazel build started to output another "without-jdk" installer which causes the travis script to fail. The script tries to do some parsing on the ci.bazel.io output to find the download url and that parsing needs to be changed to handle the new case.
It looks like the parsing was done to be more resilient to output names but on the other hand the output name seems fixed so I've hardcoded that name (bazel--installer.sh).
Let's see if travis will pass for this one
> travis hardcoded to bazel--installer.sh for HEAD

- scala/scala.bzl
- test/BUILD
- test/src/main/scala/scala/test/location_expansion/LocationExpansionTest.scala
We need $location expansion and that is supported by the java rules.
Not exactly sure why I had to add `ctx.attr.data` explicitly to the `expand_location` since, to me at least, once I add the label in the `data` attribute I think that should be a valid dependency but it's apparently not strict enough for bazel for some reason. I added this [SO](http://stackoverflow.com/questions/43982762/location-expansion-in-bazel) question to try and gather more details on why this works like it does.
> added location expansion with data attribute

- src/java/io/bazel/rulesscala/test_discovery/DiscoveredTestSuite.scala
- test/BUILD
- test/src/main/scala/scala/test/junit/JunitAbstractClassAndInterface.scala
junit and specs2 fail with when trying to run abstract classes and traits.
We now filter those out.
> test discovery filters abstract classes and traits

- src/java/io/bazel/rulesscala/test_discovery/DiscoveredTestSuite.scala
- test/BUILD
- test/src/main/scala/scala/test/junit/JunitInnerClass.scala
If you have an inner class in a test with a match on prefix (TestClass for example where the prefix is Test) then the current implementation tries to run it as tests (TestClass$SomeHelper matches the prefix of Test).
Surefire's [behavior](https://github.com/apache/maven-surefire/blob/f841a16e4f85ffc28a39baa3f01454c08092f79d/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L747) is to filter out inner classes. 
This PR mimics it.
> junit filters inner classes

- scala/scala.bzl
- src/java/io/bazel/rulesscala/scala_test/BUILD
- src/java/io/bazel/rulesscala/scala_test/Runner.java
- test/BUILD
- test/TestFilterTestA.scala
- test/TestFilterTestB.scala
- test_run.sh
This should address #188, enabling what sbt users are used to with it's `testOnly` feature, with the `--test-filter` option of bazel with `scala_test` rules
> make scala_test honor --test_filter flag.

- .travis.yml
- test_run.sh
fixes #221 
travis doesn't like it that our build takes > 30m to finish, especially when we don't print anything to stdout while one of the tests is running.
Hence I created an alternative `run_test` that would run only in CI that would run each test as spawned processes and print to stdout every 1 minutes while the spawned process is running.
**why didn't I just replace the current `run_test`?**
Because locally we don't want our test to spawn new processes (we want to be able to terminate the process tree with Ctrl+C, for instance).
> stabilize travis run

- scala/scala.bzl
- test/src/main/scala/scala/test/resources/strip/BUILD
- test/src/main/scala/scala/test/resources/strip/ResourceStripPrefixTest.scala
- test/src/main/scala/scala/test/resources/strip/nosrc_jar_resource.txt
- test_expect_failure/mismatching_resource_strip_prefix/BUILD
- test_expect_failure/mismatching_resource_strip_prefix/resource.txt
- test_run.sh
Noted that the function `_adjust_resources_path` was used for both nosrc jar and the scalac worker.
Because this issue does not happen for scalac worker, I had to rename the function `_adjust_resources_path` to `_adjust_resources_path_by_general_rules` and then create another function for the nosrc jar - that calls the original function only if `resource_strip_prefix` is missing.
The test simply checks that after filtering all lines with "strip" from `jar tf` output, we can still find the resource file.
> Fixed #214 - resources_strip_prefix now works for nosrc jar

- scala/scala.bzl
- test/BUILD
- test/src/main/scala/scala/test/utf8/JavaClassWithUtf8.java
- test/src/main/scala/scala/test/utf8/ScalaClassWithUtf8.scala
`java_library` compiles UTF-8 files without special configurations.
On systems where UTF-8 is not the default encoding, `scala_library` fails when compiling java code with UTF-8 characters, showing error: 
```
error: unmappable character for encoding ASCII
```
As part of the effort to be compliant with java_library - I suggest we do the same.
> forcing utf-8 encoding with javac

- scala/scala.bzl
- test_run.sh
Moved to using Bazel's Junit runner which apparently was already open.
based on @natansil's previous work on scala.bzl but without the code from Bazel.
Also changed the existing junit logs test to actually check that the test-cases are actually printed to the xml log file. Test was red and with the change it passed! :)
cc @chaoren
> Junit (and specs2) tests now output logs with content

- test/BUILD
- test/src/main/scala/scala/test/ResourcesStripScalaBinary.scala
- test/src/main/scala/scala/test/ResourcesStripScalaLib.scala
- test_run.sh
Pretty confident from context and git commit log that this is the actual name.
I tried to understand this a few weeks ago and thought it's best to document this knowledge back in the code.
@johnynek,
Would appreciate your thoughts as well to make sure I'm not adding confusion here.
> renamed MoreScala* targets to ResourcesStripScala* targets

- scala/scala.bzl
- test/BUILD
- test/LibToBin.scala
- test/LibToTest.scala
this being missing caused us some pain.
1) some targets depend on binaries or test. Maybe not awesome, but not sure we really want to make this impossible either.
2) we want tooling we have that deals with hadoop deploys to just use java providers, but scala_binary does not have one, so it fails.
I added two tests that failed before this change.
> Add a provider for binary targets

- README.md
This is adds an extra line of padding so you can read the "Building from source" section (sorry).
> misc: add line for test and build formatting

- tut_rule/tut.bzl
when we load this rule in a remote repo, this label looks like a local label. We need to use the full name of the target.
> Use workspace name in tut rule

- scala/scala.bzl
- test/aspect/BUILD
- test/aspect/FakeJunitTest.scala
- test/aspect/aspect.bzl
Add a separate attribute whose sole purpose is to propagate dependency
information via aspects.
This will allow the IntelliJ aspect to get every necessary implicit
dependency by just following _scala_toolchain.
This also allows us to avoid the issue of certain dependencies being
required to be used as files instead of java targets.
> Organize implicit dependencies necessary for IDEs.

- src/scala/scripts/TwitterScroogeGenerator.scala
- twitter_scrooge/twitter_scrooge.bzl
when workers are enabled, it seems empty lines are removed from the arguments list. This PR makes sure to always have 1 line per arg (by padding with a leading `_` which is discarded).
This is actually currently a blocker for us. I would love to have better tests around this (that exercise everything with and without workers, but I don't want to try to shave that yak before we get this build issue unblocked).
> Fix issue with empty args and workers

- src/scala/io/bazel/rules_scala/tut_support/TutCompiler.scala
- tut_rule/tut.bzl
We saw two issues which I'm not sure how we didn't catch before:
1) the tmp directory is (sometimes?) outside of bazel's control, so sandboxing fails in one case we have (I thought the build on bazel ci would have caught that).
2) the name for the tut rule is highly unintuitive and not the name you write, so you probably can only build it with a `...` pattern, which is annoying.
> Improve tut rule

- scala/scala.bzl
If ijar is none that means dep target does not contain ijar.
This happens to us when working on intellij integration (which we'll contribute back in a few weeks).
Essentially the intellij plugin needs the `scala_import` rule to set ijar as None so that it will take the `class_jar`. This is important for the whole macros handling.
This is also why there isn't a test for this right now. 
This will be covered when we contribute back the `scala_import`
@natansil I'd appreciate your review
> handling none ijar case

- src/scala/io/bazel/rules_scala/scrooge_support/Compiler.scala
Versions of scrooge newer than 4.6.0 use java.util.logging directly, instead of com.twitter.logging.  The NullLogger instance is therefore incompatible with newer versions.  By changing to use setLevel, the logging is disabled for any logger: that method is the same on both the twitter and java loggers, and compiles correctly with more versions of scrooge.
I'm using scrooge 4.15.0 instead of the built-in 4.6.0, and everything works great once I have this change.
> scrooge compiler: disable logging via a method, not a NullLogger instance

- scala/scala.bzl
- src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
- src/java/io/bazel/rulesscala/test_discovery/DiscoveredTestSuite.scala
- test/BUILD
- test/src/main/scala/scala/test/BinaryDependentOnJava.scala
- test/src/main/scala/scala/test/ijar/A.scala
- test/src/main/scala/scala/test/ijar/B.scala
- test/src/main/scala/scala/test/ijar/BUILD
- test/src/main/scala/scala/test/ijar/C.java
- test/src/main/scala/scala/test/junit/JunitJavaTest.java
- test_expect_failure/compilers_jvm_flags/BUILD
- test_run.sh
Was supposed to be a refactoring but found a few missing tests.
The good news are that we indeed have good coverage since this hits many code paths and the tests gave me good (though long) feedback about what I'm breaking.
Possible open issues:
1) I haven't changed the "files" being returned- No tests demanded it and I'm trying to understand what needs this. I think our internal aspect actually will be broken by this so I'll try to add a test like it today and see if it breaks.
2) Not sure Intellij integration continues to work now- will see how I triage this. @chaoren can the intellij aspect try to use the java_provider before falling back to scala attr?
> Moved to java_common.compile

- .travis.yml
Testing against HEAD is very brittle and frustrates many new contributors. Until bazel supplies a standard URL to grab the HEAD builds, we should probably rely on the bazel ci bot for HEAD testing.
We still have issue #76 to make more of our tests sh_tests. We have still not tackled them, but if we did, it would probably make the bazel ci bot happier (since they want to just run bazel commands, I think).
cc @damienmg
> Just test most recent two releases

- scala/scala.bzl
- test_expect_failure/missing_direct_deps/internal_deps/BUILD
- test_expect_failure/missing_direct_deps/internal_deps/User.java
- test_run.sh
exposing transitive_compile_time_jars to java_common.provider to use strict java deps
We still can't run this with `warn` until https://github.com/bazelbuild/bazel/issues/3626 is resolved but it's already a step forward.
Additionally if you're using `java_library` targets with strict deps this currently doesn't work and this fixes it as well
> exposing transitive_compile_time_jars to java_common.provider

- .travis.yml
- WORKSPACE
- scala/scala.bzl
- test/src/main/scala/scala/test/sources_jars_in_deps/BUILD
- test/src/main/scala/scala/test/sources_jars_in_deps/ReferCatsImplicits.scala
This won't effect compiling source jars, but they shouldn't be in the dependency tree.
The issue here is that for maven_jar type imports we need to use the `jar:file` to avoid the ijar behavior for importing scala macros. But since scala 0.6.0 
https://github.com/bazelbuild/bazel/commit/7a7c41d7d342cd427e74f091b55690eed13e280d
Means that the source jars are also being included into this filegroup. Either we need a custom maven fetching rule, or this will strip `-sources.jar` from the dependencies tree. Since we wouldn't expect class files to be in sources jars already compiled this seems safe?
(First push here should fail build with error all going well, then the new code can be activated to pass build)
r? @johnynek
> Strip -source's jars from scala's compiler classpath for dependencies

- .bazelrc.travis
- .travis.yml
- test/src/main/scala/scala/test/twitter_scrooge/thrift/BUILD
- test/src/main/scala/scala/test/twitter_scrooge/thrift/ThriftMany1.thrift
- test/src/main/scala/scala/test/twitter_scrooge/thrift/ThriftMany2.thrift
- thrift/thrift.bzl
Bazel has a built in command for building zips deterministically. Use that rather than the find + timestamp setting trick.
closes #282
> Use zipper rather than jdk/jar in the thrift rules

- scala/scala.bzl
- src/java/io/bazel/rulesscala/scalac/CompileOptions.java
closes #288 
While I was at it, I trimmed out some stuff we are no longer using from scalac compilation, which was relevant because I was trying to remove uses of `_jdk` and related dependencies.
> Use zipper for empty-srcs targets

- scala/scala.bzl
- src/java/io/bazel/rulesscala/scalac/BUILD
- src/java/io/bazel/rulesscala/scalac/CompileOptions.java
- src/java/io/bazel/rulesscala/scalac/Resource.java
- src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
- test/BUILD
- test/src/main/resources/scala/test/BUILD
- test/src/main/scala/scala/test/ResourcesStripScalaBinary.scala
- test/src/main/scala/scala/test/ResourcesStripScalaLib.scala
> Address inconsistent behavior of generated resources files

- WORKSPACE
The change is required for compatibility with the upcoming Bazel 0.8.0
> Update protobuf to 3.4.1

- scala/scala.bzl
we had an internal system that didn't work when someone used the `_wrapper` script because we hadn't exec'ed.
This fixes it. Really, users should only use the `wrapper.sh` for the repl, but this is probably not clear, so this error is easy to make.
~~Alternatively, we could actually just not generate this file for non-repl targets, which I also think would work although it would be a break for people who have assumed it exists. This seems the most conservative change.~~
actually, the standard launcher calls this wrapper, so I think we do want this PR exactly as is.
> exec in wrapper script if we aren't in the repl

- WORKSPACE
- scala/scala.bzl
- scala/scala_cross_version.bzl
- scala_proto/scala_proto.bzl
- specs2/specs2.bzl
- specs2/specs2_junit.bzl
- tut_rule/tut.bzl
* migrate from hardcoded _2.11 to `scala_mvn_artifact`
* upgrade to scalding-date 0.17.0
See commits for details.
> Dependencies cleanup

- scala/scala.bzl
It's fresh of the oven, tagged an hour ago and not yet announced: https://github.com/scala/scala/releases/tag/v2.12.4
The #305 is not fixed, see comments.
> Upgrade to Scala 2.12.4

- scala_proto/scala_proto.bzl
Protobufs generated in a separate repository do not have their root set properly. This causes builds to fail when using well known protos from the latest https://github.com/google/protobuf.
Fixes https://github.com/bazelbuild/rules_scala/issues/312.
I could not find documentation on the right way to join paths in `bzl` files so have resorted to `'/'.join(...)`. Open to suggestions on a better way to do that.
> Prepend generated file root to protobuf input root path.

- scala/scala.bzl
- test_expect_failure/missing_direct_deps/internal_deps/BUILD
- test_expect_failure/missing_direct_deps/internal_deps/HasCustomJavaProviderDependency.scala
- test_expect_failure/missing_direct_deps/internal_deps/custom-jvm-rule.bzl
- test_run.sh
strict-deps clearer message when no transitive jars2labels
drive-by (mostly optimizations):
iterate over deps one (via current_dep_*_jars)
for runtime_deps skip collecting labels
@johnynek:
This PR came from me troubleshooting our strict deps move with our scala_import. The need comes from a problem in the design of java_common where each rule will have to calculate the transitive labels on their own. I hope to address it via bazel but it will take time. The current solution is the simplest I could find without going into the plugin and introducing more concepts (which I hope will be redundant once Bazel supports them natively).
> strict-deps clearer message when no transitive jars2labels

- .travis.yml
- scala/scala.bzl
- scala_proto/scala_proto.bzl
fixes compatibility with 0.7.0 onwards
fixes #280 
fixes #314 
fixes https://github.com/bazelbuild/bazel/issues/3792
Good news:
Small and easy fix. Identical to what @lberki did but just for the additional provider that was added.
Bad news:
Actually utilizing the feature @iirina exposed for us proves to be more tricky than expected for two reasons:
1. We have intimate handling of ijar and output gluing throughout our code.
2. I think the current `create_provider` API doesn't take into account `exports`
**Note**:
The provider is hardcoded to not create an ijar exactly due to the problems above. The current fix is just to play nice with the skylark API and sidestep the new feature.
> create provider conditionally based on existence of attribute

- scala_proto/scala_proto.bzl
This fixes https://github.com/bazelbuild/rules_scala/issues/315 by allowing the inclusion of `java_library` in the deps of `scalapb_proto_library`.
> Allow java libraries as deps of scalapb_proto_library.

- scala/scala_import.bzl
- test/src/main/scala/scala/test/scala_import/BUILD
- test/src/main/scala/scala/test/scala_import/ReferCatsImplicits.scala
- test/src/main/scala/scala/test/scala_import/ScalaImportExposesJarsTest.scala
- test/src/main/scala/scala/test/scala_import/ScalaImportPropagatesRuntimeDepsTest.scala
- test_expect_failure/scala_import/BUILD
- test_expect_failure/scala_import/ScalaImportPropagatesCompileDepsTest.scala
- test_run.sh
Motivation:
The need for `scala_import` stems from the lack of support for scala's macros in ijar (see https://github.com/bazelbuild/bazel/issues/632 fro more details). This means we need a way to import external jars which doesn't pass through ijar. The current workaround is to use `maven_jar` and then use the `//jar:file` target which exposes a raw filegroup target.
Unfortunately that doesn't play nicely with bazel-intellij plugin which needs metadata about the target.
Current state:
Does:
Supports intellij
Creates java_provider
has deps and runtime_deps
Partial support for "aggregators" (you can pass None)
Does not (yet):
Support neverlink
Support many code jars
Supports exports (not sure will be supported)
Allow to give a raw jar and have the rule create an ijar if needed for it. This …
> adding scala_import

- WORKSPACE
- scala/BUILD
- scala/scala.bzl
- scala/scala_cross_version.bzl
- scala_proto/scala_proto.bzl
- specs2/specs2.bzl
- specs2/specs2_junit.bzl
- src/java/io/bazel/rulesscala/scalac/BUILD
- src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala
- src/scala/io/bazel/rules_scala/scrooge_support/Compiler.scala
- test/aspect/aspect.bzl
- test/jmh/BUILD
- test_run.sh
- tut_rule/tut.bzl
- twitter_scrooge/twitter_scrooge.bzl
Reverts bazelbuild/rules_scala#358
Mistakenly targeted master instead of scala2_12 branch.
> Revert "Sync Scala 2.12 with master"

- scala/scala.bzl
- test_expect_failure/missing_direct_deps/internal_deps/BUILD
- test_expect_failure/missing_direct_deps/internal_deps/JavaLibraryHasCustomJavaProviderDependency.java
- test_expect_failure/missing_direct_deps/internal_deps/Placeholder.java
- test_expect_failure/missing_direct_deps/internal_deps/custom-jvm-rule.bzl
- test_run.sh
scala_* rules create java_provider with compile_jars in transitive_compile_jars
@johnynek we saw internally that with a scala_library depending on a scala_import depending on scala_library  (somewhat similar to bazel-deps `replacements` mode) the compile jars of the root scala library dep aren't propagated. Only its transitive compile ones.
I initially fixed it in scala_import but then I suspected the root problem is with the scala rules themselves.
I added two tests that show it and actually removed the crutches we had (scala.bzl and custom_jvm_rule) which did it themselves. This was a problem since every passing rule type needed to implement it themselves (like scala_import which is how I caught this).
@damienmg @lberki @dslomov @iirina 
FYI- The current state of the create_provider is …
> Fix bug in the provider we create in scala_library/binary/rest

- scala/scala_import.bzl
fixes #359 
Additionally it fixes label propagation of transitive deps of exports
@johnynek this has no tests since quite honestly I'm tired from all of the permutations we need to do here. Given that https://github.com/bazelbuild/bazel/issues/3769 is being worked on and it will remove 90% of the code in this rule I feel ok with this.
We use this code as is today.
cc @gkk-stripe
> Scala import exports fixes

- src/java/io/bazel/rulesscala/specs2/Specs2RunnerBuilder.scala
- test_run.sh
This happens if a give test filter matches everything (e.g. `.*`), including the intermediate `should` scopes, which are not real test method descriptions.
> Specs2: fixing a NPE when trying to match against a "should" descripition

- scala/scala.bzl
As described in
https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#dictionary-concatenation,
the ability to + dictionaries in Skylark is going away soon. This
change removes this practice for rules_scala. Alas, it makes the rule
attr code a bit wordier.
> Remove Skylark dictionary concatenation.

- .travis.yml
- scala/scala.bzl
Good news:
- 0.9.0 passes without any changes
- 0.8.1 and 0.9.0 are [faster](https://travis-ci.org/greggdonovan/rules_scala/builds/322222475) to run the rules_scala tests than 0.7.0 (~18-25 minutes vs. ~33-35 minutes).
Bad news:
- Adding a third Bazel build to the build matrix increases the overall wall-clock time from ~56 minutes to to ~85 minutes. 
- It might be too soon to drop 0.7.0 support?
> Add Bazel 0.9.0 to the Travis build matrix.

- scala/scala.bzl
//tools/defaults:jdk is a filegroup and won't be compatible with Bazel 0.10 .
> Depend on @bazel_tools//tools/jdk:current_java_runtime for the JDK.

- scala_proto/scala_proto.bzl
Including workspace name so others can use it
This fixes #388 
Cc @natansil can you please review?
Didn't add a test since this is our blind spot currently with the current e2e setup
> Use generator fully qualified label

- scala/support/JUnitXmlReporter.scala
Testing with strict scala compiler warnings in another project gave me this error:
```
INFO: From scala @io_bazel_rules_scala//scala/support:test_reporter:
external/io_bazel_rules_scala/scala/support/JUnitXmlReporter.scala:53: warning: Procedure syntax is deprecated. Convert procedure `apply` to method by adding `: Unit =`.
def apply(event: Event) {
^
external/io_bazel_rules_scala/scala/support/JUnitXmlReporter.scala:503: warning: Procedure syntax is deprecated. Convert procedure `unexpected` to method by adding `: Unit =`.
def unexpected(event: Event) {
```
> Change from procedure syntax to address compiler warnings

- scala/scala_import.bzl
- test_expect_failure/scala_import/BUILD
- test_expect_failure/scala_import/LeafScalaImportPassesLabelsDirectDeps.scala
- test_expect_failure/scala_import/RootScalaImportPassesLabelsDirectDeps.scala
- test_rules_scala.sh
Currently scala_import doesn't keep labels of direct deps, only of transitive deps.
This causes "unknown label" warnings for some use-cases (as the test shows).
A more thorough revamp is needed for label propagation but I'm trying to sync with the bazel team on it since it sounds a bazel issue
> scala_import keeps labels of direct deps

- scala/scala.bzl
- src/java/io/bazel/rulesscala/scalac/CompileOptions.java
- src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
- test/BUILD
- test/check_statsfile.bzl
As it stands there isn't clean path to getting target level metrics from Bazel. The build event protocol currently doesn't have timing information for non-test targets [0]. But that doesn't have to stop us from being the first to get this kind of metric from Scala [1].
This adds an output file, the "statsfile" with a very basic property file inspired syntax. The values can be read easily with basic text manipulation utilities, for example `awk -F '=' '$1 == "property_name" { print $2 }' 'path_to.statsfile'` to read the value for `property_name`.
One downside is that this statsfile is non-deterministic. As long as this file is only used for downstream metrics, it shouldn't be problematic. The long term hope is that timing information can be added to the build event protocol and that this …
> Emit a the Scala compilation time for downstream metrics

- scala/scala.bzl
- scala/scala_import.bzl
The IntelliJ plugin assumes that source_jar and source_jars are both
present on the jars struct. This sets those to empty values, so the
IntelliJ plugin does not fail.
> Add struct members that IntelliJ plugin expects to exist

- scala/scala.bzl
Looks like I forgot to add the statsfile to the output struct needed by downstream aspects.
> Specify the statsfile output in the rule output struct

- scala/scala.bzl
Without it, builds fail on Windows as it uses semi-colon instead.
> Use OS-specific classpath separator

- scala_proto/scala_proto.bzl
- src/scala/scripts/PBGenerateRequest.scala
- test_expect_failure/proto_source_root/dependency/BUILD
- test_expect_failure/proto_source_root/dependency/zip_code.proto
- test_expect_failure/proto_source_root/user/BUILD
- test_expect_failure/proto_source_root/user/address.proto
- test_expect_failure/proto_source_root/user/person.proto
following https://github.com/bazelbuild/bazel/issues/4544 I'm adding an optional propagation of transitive_proto_path_flags to protoc.
It's optional since it's not currently in a released version and in fact the exposition to skylark will only land in an hour or two but I've tested it manually.
For the above reason the test is under `test_expect_failure` and not part of CI since we can't run only that test against bazel head.
@azymnis @johnynek I'd like to merge this soon so I'd appreciate your review
> use transitive_proto_path_flags if exist

- scala/support/BUILD
- scala/support/JUnitXmlReporter.scala
This is the short term fix for https://github.com/bazelbuild/rules_scala/issues/432
> Compile reporter using very strict settings

- scala/scala.bzl
- test_expect_failure/compilers_javac_opts/BUILD
- test_expect_failure/compilers_javac_opts/WillNotCompileSinceJavaToolchainAddsAnInvalidJvmFlag.java
- test_rules_scala.sh
Scala rules compile java sources using `java_common.compile`. When building the required input for `java_common.compile` scala rules uses only `javacopts` and `javac_jvm_flags` attributes while ignoring any global/default `javac_opts` such as the ones from `.bazelrc` file, e.g., `build --javacopt=...` or `build --java_toolchain=//:some_tool_chain`
This PR uses `java_common.default_javac_opts` to add the default `javac_opts` to `java_common.compile` `javac_opts`
> Add default javac opts when compiling java srcs

- scala_proto/scala_proto.bzl
- src/scala/scripts/PBGenerateRequest.scala
@johnynek Bazel ended up using a different name for the skylark field.
It landed [here](https://github.com/bazelbuild/bazel/commit/98ed9af727ec6342206d181fcd465e3e83980c52)
> adjust transitive_proto_path_flags skylark name to transitive_proto_path

- test/src/main/scala/scala/test/scala_import/BUILD
- test/src/main/scala/scala/test/scala_import/ScalaImportExposesFileJarsTest.scala
When adding a test for scala_import files support, a test was added that
is never run. This fixes that mixup.
> Fix mixup that occured when adding scala_import files test

- scala/scala.bzl
- src/java/io/bazel/rulesscala/scalac/BUILD
- src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
This greatly improves the performance of that method. It was spotted in
the wild to take up to 50s for relatively small input source jar.
> Use commons-io to copy bytes in ScalacProcessor.extractJar

- scala/scala.bzl
This is a workaround for the issue described [here](https://stackoverflow.com/q/49373212/334519). Instead of waiting for bazel 0.11 to be generally available (see [discussion](https://github.com/bazelbuild/rules_scala/pull/409/files#r164850044)), this change checks whether the new `java_executable_runfiles_path` method is available and uses it now if it is. Otherwise the logic is the same as what it was previously.
> Use java_executable_runfiles_path if available

- scala_proto/scala_proto.bzl
just the proto part of #452 to address #430
> fix bazel incompatibilities in proto

- scala/scala.bzl
This is now in Bazel in the latest release, so it works this way.
> Unconditionally use java_executable_runfiles path.

- scala/scala.bzl
This is a minor refactor of write_launcher to prepare for a change to make a repl script for all targets.
One cleanup here is that we had repeated ourselves with the name of a launcher script. Here we explicitly plumb this through so we can define it in a single place and be more honest about the dependencies.
Secondly, we make it clear that we only need a single wrapper script for each target (really each directory I think), so we can share a wrapper between the repl launcher and, for instance, the binary executable.
ptal @ittaiz
> Refactor write_launcher

- jmh/jmh.bzl
- src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala
Use reflection-based generator (RFGeneratorSource) instead of ASM-based, it does support Java8 byte-code.
Also version of JMH is upgraded.
> Support JMH for scala 2.12 #295

- .bazelci/presubmit.yml
- jmh/jmh.bzl
- src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala
- test/jmh/BUILD
This is a replacement of #463 by cherry-picking and merging #465 into the scala 2.12 branch ultimately closing #295 actually.
@dkomanov @ittaiz please take a look.
> Cherry pick and merge #465 into scala 2.12 branch

- thrift/thrift.bzl
- twitter_scrooge/twitter_scrooge.bzl
This updates thrift to use a modern provider instead of an anonymous struct.
This is part of #450 
ptal @andyscott @ittaiz
> Add a ThriftInfo provider

- scala/scala.bzl
This is part of #452 in the scala.bzl part. Not all of the changes. I want to see them pass on CI, since the laptop I am using is a bit slow. They seem to pass, but to be extra sure we might want a clean build from travis.
> Use some more non deprecated APIs

- scala/scala.bzl
- test/BUILD
- test/aspect/aspect.bzl
- test_rules_scala.sh
This fixes the remaining issues to resolve #430. With this, I can pass all tests using `--all_incompatible_changes`.
We test both strict deps and without strict deps to make sure we can pass with the all_incompatible_changes. Since the build should be exactly the same, the cache works when things pass, so it doesn't really increase CI time.
> Fix remaining incompatible changes warnings

- scala_proto/scala_proto.bzl
Fixes:
```
ERROR: test/proto/BUILD:36:1: in scala_proto_srcjar rule //test/proto:test_proto_java_conversions_srcjar:
Traceback (most recent call last):
File "test/proto/BUILD", line 36
scala_proto_srcjar(name = 'test_proto_java_conversions_srcjar')
File "scala_proto/scala_proto.bzl", line 332, in _gen_proto_srcjar_impl
transitive_proto_paths += target.proto.transitive_proto_path
`+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
```
See also #480
> `+` operator on a depset is forbidden

- WORKSPACE
- scala/scala.bzl
- scala/scala_cross_version.bzl
- scala_proto/scala_proto.bzl
- specs2/specs2.bzl
- specs2/specs2_junit.bzl
- src/java/io/bazel/rulesscala/scalac/BUILD
- src/scala/io/bazel/rules_scala/scrooge_support/Compiler.scala
- test/aspect/aspect.bzl
- tut_rule/tut.bzl
- twitter_scrooge/twitter_scrooge.bzl
**This targets master to show it's one simple commit on top of master. It should be merged to scala_2.12**
I had a spare minute and saw comments asking for 2.12 branch. I cherry-picked the original commit for 2.12 branch to start with a clean slate.
Below are original comments from the commit
* Scala 2.12 updates
Bump dependencies to versions that support Scala 2.12.
* Fix incompatible scrooge api change.
They swapped the logger interface and now there's a different went to
silence the logging.
* Add scalactic as a transitive dep of scalatest
Newer versions of scalatest have scalactic as a dependency. Let bazel
know about it and add its a transitive dep.
* Add a missing dependency on util_core from scrooge rule
Add a missing dependency on Twitter's util_core from scrooge rule
Switch to a …
> Fresh cherry-pick of the Scala 2.12 support (#304)

- .bazelci/presubmit.yml
Local disk caching does not work on Bazel's CI and actually causes the project to fail in our downstream tests at the moment:
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/224#e8eab4eb-9baf-4503-8328-62d1ca2f454d
> Remove tools/bazel.rc on CI as it's incompatible.

- .bazelci/presubmit.yml
- tools/bazel.rc.buildkite
this is following @johnynek's request to have our workers on when running in buildkite.
I wonder if this will fix #498 or not.
cc @buchgr @dslomov
> enable workers on buildkite

- src/java/io/bazel/rulesscala/test_discovery/FilteredRunnerBuilder.scala
- test/BUILD
- test/src/main/scala/scala/test/junit/JunitCustomRunner.java
- test/src/main/scala/scala/test/junit/JunitCustomRunnerTest.scala
- test_rules_scala.sh
Fixes #376
This is a bit hacky, since it requires replacing a private object instance of the current test runner using private reflection.
Unfortunately, there doesn't seem to be a way to set this object from the outside using normal API.
This PR moves the filtering logic to the actual `TestClass` instance that the JUnit runners query internally, allowing us to perform external filtering on custom runner instances. 
Background info:
The actual logic for querying test methods lives in `org.junit.runners.model.TestClass`, which is, unfortunately, a private field, created by the runner.
To be able to support our custom filtering on other runners, this `TestClass` instance has to be modified.
We're currently handling scala junit tests by "intercepting" the runner as a custom suite, and …
> Support custom runners (@RunWith) on filtered Scala junit tests

- .travis.yml
- test_rules_scala.sh
Hopefully this supersedes #481 (cc @pauldraper)
Like discussed on the ticket I've changed the assertion (due to the naming it was pointless to loosen the assertion so I changed it a bit).
> Upgrade bazel travis to 0.12.0

- scala_proto/scala_proto.bzl
- test_rules_scala.sh
@johnynek #454 broke transitive proto paths. Because the test was not in CI (requires bazel 0.12.0 which we didn't have until yesterday) we didn't notice it.
I'm now running the test and fixed the issue.
This is a serious blocker for us so if you can take a look and sign off I'd appreciate it :)
> flatten depset of transitive proto paths (currently broken accumulation)

- scala/private/common.bzl
- scala/private/rule_impls.bzl
- scala/scala_import.bzl
I think we already require a bazel version that means we don't need to use these checks.
Just some small housekeeping on the way to using modern providers on all the rules now that https://github.com/bazelbuild/intellij/issues/279 is solved.
> Remove some old java_common checks

- scala/private/rule_impls.bzl
- test_rules_scala.sh
@johnynek apparently we only expose the wrapper script for scala binary targets.
Added tests for scala_binary/scala_test/scala_junit_test
There is some redundancy between the three but they felt important enough to protect if we re-implement them without a shared method
> expose scala binary jars in build even protocol

- WORKSPACE
to a version that includes a fix to the bazel incompatibility of PACKAGE_NAME.
Currently one of the things blocking the usage of 0.13.0 in travis
> update protobuf version

- scala/private/rule_impls.bzl
https://github.com/bazelbuild/rules_scala/pull/511 introduced a bug meaning we always build all non-default outputs for our binary rules. So we were always building the deploy jars (ultimately filling disks in our CI cluster :) )
@ittaiz can you take a look? i didn't remove any of the tests you added so this shouldn't be a regression i don't believe for what you were looking at.
> Fix issue building all outputs rather than just default

- README.md
Issues referenced for building in MAC (#136, #396 and #398)  are closed/merged
Having the comment `This doesn't currently pass on OS X (see #136 for details)` is not accurate. 
BTW, I cannot confirm it's true, because in my env have bazel 0.14 and `test_all.sh` is failing
(`bazel test //test/...` is OK)
> docs: Remove stale comment

- scala/private/rule_impls.bzl
- scala/scala.bzl
The goal here is to produce a skylark function we can call to compile source or source jars. The first step is to stop getting all the arguments implicitly from the ctx which implies that they were set up by a rule.
Instead, we want to have a function we could call inside any other rule, which may not have the right attrs or files.
This does not get all the way there, maybe halfway, but I'd rather send the PR.
> refactor the _compile function

- scala/scala.bzl
- scala_proto/scala_proto.bzl
extra info is a wart from over 2 years ago to allow walking the dependency graph. Since then, it seems that aspects are the way bazel recommends doing things. We only currently use extra_info in the scrooge rules, but the protobuf rules seem to have copied the idea, but does not use it.
ptal @ittaiz 
cc @azymnis
> remove cargo-culted extra info in protobuf rules

- scala/scala.bzl
the version we were on has a silent failure with large classpaths.
The version on master, has a bug with very large classpaths, but at least it is not a silent error.
https://github.com/bazelbuild/bazel/issues/5413
When that is fixed we should update.
Also, we should revisit the #471. It would be nice to have a supported `jvm_binary` that we could call, so really we only own scala_library.
> use latest version of java launcher stub

- scala/private/rule_impls.bzl
this moves all the rest of the items I don't expect would be required out of the function accessing by ctx and instead by a parameter.
After this is merged, I will pick back up #510 which I think can be made to work using this PR.
Note, there are still some toolchain-ish stuff accessed on ctx, but I think that we will just have to add those to the thrift/proto generation rule until we have toolchains working correctly (see #530)
> Make compile scala callable

- scala/private/rule_impls.bzl
the launcher in 0.14.1 has some additional jacoco variables. With these unset, things build, but you get a bash warning.
This fixes that.
> Add additional substitutions

- scala/private/rule_impls.bzl
- scala/scala.bzl
- src/java/io/bazel/rulesscala/scalac/CompileOptions.java
- src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
- test_rules_scala.sh
here is a supported function to run ijar:
https://docs.bazel.build/versions/master/skylark/lib/java_common.html#run_ijar
I don't know at the moment when it was introduced because bazel docs are sadly unversioned. It does allow us to delete a fair amount of code, so I think it is worth it.
cc @ittaiz @ianoc
> Use java_common.run_ijar

- scala/scala_import.bzl
https://github.com/bazelbuild/rules_scala/pull/549 is blocked as using a `$(location)` expression with a target created using `scala_import` fails. As @ittaiz suspected this was due to `scala_import` not returning a `DefaultInfo` provider.
Tested with https://github.com/bazelbuild/rules_scala/pull/549 confirming that it fixes the problem.
> Add DefaultInfo provider to outputs of scala_import

- scala/scala.bzl
- scala/scala_import.bzl
- test/BUILD
- test/aspect/aspect.bzl
As part of a larger PR (https://github.com/bazelbuild/rules_scala/pull/544) for adding support for selecting scala versions I separated `scala-xml` and `scala-parser-combinators` to be imported individually using `native.http_jar`. @johnynek suggested making o separate PR for this smaller change so here it is.
The motivation behind the change is that the versions of `scala-xml` and `scala-parser-combinators` that are downloaded as part of the main `{scala_version}.tgz` differ between minor scala versions and this way we can select specific versions (https://github.com/bazelbuild/rules_scala/pull/544 would allow users to select any 2.11/2.12 minor version)
> Add scala-xml and scala-parser-combinators jars individually

- test_rules_scala.sh
Some specs2 tests in `test_rules_scala.sh` set `$method` while other don't. All test were printing `$method` in their error messages. This PR prints the correct variables instead.
Really minor thing I just happened to notice
> Add correct variables to test error messages

- test/src/main/scala/scalarules/test/twitter_scrooge/BUILD
- test_rules_scala.sh
Noticed that the test `barethriftslib` is not working and never run. Currently it fails with: `Error: Could not find or load main class scalarules.test.twitter_scrooge.BareThrifts`
And it's not run anywhere:
```sh
$ bazel query "rdeps(//test/..., //test/src/main/scala/scalarules/test/twitter_scrooge:barethrifts)"
//test/src/main/scala/scalarules/test/twitter_scrooge:barethrifts
$ git grep barethrifts
test/src/main/scala/scalarules/test/twitter_scrooge/BUILD:    name = "barethriftslib",
test/src/main/scala/scalarules/test/twitter_scrooge/BUILD:    name = "barethrifts",
```
This fixes the test and runs it from `test_rules_scala.sh`
Also added 2 other scrooge tests that were never run (as far as I could tell) to `test_rules_scala.sh`
> Fix and run barethriftslib test

- test/BUILD
- test/src/main/scala/scalarules/test/large_classpath/BUILD
- test/src/main/scala/scalarules/test/twitter_scrooge/BUILD
- test_rules_scala.sh
Currently tests executed by `bazel run` are run both by `test_rules_scala.sh` directly:
```
$runner bazel run test/src/main/scala/scalarules/test/twitter_scrooge:justscrooges
$runner bazel run test:JavaBinary
...
```
and using `sh_test` in `test/BUILD`:
```python
[sh_test(
name = "Run" + "".join([binary[idx] if binary[idx].isalnum() else "_" for idx in range(len(binary))]),
srcs = ["test_binary.sh"],
args = ["$(location %s)" % binary],
data = [binary if (":" in binary) else (":%s" % binary)],
) for binary in [
"JavaBinary",
"JavaBinary2",
...
```
This PR moves all `bazel run` tests to be run using `sh_test` in `test/BUILD`
> Run "bazel run" tests from test/BUILD

- README.md
Yesterday we merged https://github.com/bazelbuild/rules_scala/pull/544 to add support for different scala versions.
I noticed that the shas I'd added in the README were for Scala 2.11.12 and not 2.12.6, this fixes that.
At the moment if a user copies the example in the README rules_scala will either error or just use the wrong version of scala.
@johnynek
> Add correct hashes for 2.12.6 to readme

- .travis.yml
- README.md
- test_all.sh
Add notes to make upgrading rules_scala easier. Based on discussion here: https://github.com/bazelbuild/rules_scala/pull/544#discussion_r204822174
@johnynek @ianoc
> Add notes about updates and usage with bazel-deps to readme

- scala_proto/scala_proto.bzl
The upstream Maven group for scalapb has officially become
com.thesamet.scalapb per this announcement:
https://groups.google.com/forum/#!topic/scalapb/BhM2IzT70Ww
I also upgraded protoc-jar to 0.6.0, which obsoletes pull request #422.
The extra changes added to work around the FreeBSD issue are not
required for 0.6.0.
Fixes #570.
> Switch scalapb to thesamet distribution, 0.7.0

- scala/scala.bzl
Set `unused_dependency_checker_mode = "off"` as default for `scala_macro_library`.
As discussed internally with @johnynek, any dependency can be used by macro targets at compile time so we want this as default for most cases.
> scala_macro_library unused deps checker default off

- scala/scala.bzl
This removes the need to use --incompatible_disallow_data_transition
> Remove cfg = "data" no-op

- README.md
Thanks for all of the hard work, [VSCO](https://vsco.co) uses rules_scala in production.
> VSCO adopts rules_scala

- lint.sh
- scala/private/rule_impls.bzl
- scala/scala.bzl
- test/test_binary.sh
- test_all.sh
- test_intellij_aspect.sh
- test_lint.sh
- test_reproducibility.sh
- test_rules_scala.sh
- test_runner.sh
- test_version.sh
- test_version/version_specific_tests_dir/test_binary.sh
closes #595
- Replaces occurrences of `#!/bin/bash` by `#!/usr/bin/env bash`, as `/bin/bash` does not exist on all systems. See issue #595.
- Fetches a more recent version of `java_stub_template.txt` from the bazel repository, in which `#!/bin/bash` was replaced by `#!/usr/bin/env bash`. See https://github.com/bazelbuild/bazel/pull/5979.
> /bin/bash does not exist on certain systems

- scala/scala_import.bzl
Currently `scala_maven_import_external` declares `neverlink` as `bool` while `scala_import` expects `int`
> Change scala_import rule neverlink attribute from int to bool

- WORKSPACE
- scala/scala_import.bzl
- scala/scala_maven_import_external.bzl
- test/src/main/scala/scalarules/test/scala_import/BUILD
This is a better approach to fetch sources following: #623. This also includes a usage example for `scala_maven_import_external` (which fails since `scala_import` has no `srcjar` attribute)
> Better way to fetch sources

- README.md
Does it work without the prefix?
> Add prefix to scala_toolchain example

- scala/scala_import.bzl
Fixed intellij metadata generated for `scala_import` to include the correct source jars information for intellij to be able properly show sources.
Since the attribute `source_jar` is marked deprecated in [intellij_ide_info.proto](https://github.com/bazelbuild/intellij/blob/02b148713798c71d86121e3c22ca5ef5470cb08b/proto/intellij_ide_info.proto#L36) I removed it from the metadata struct and used `source_jars` for all cases.
Tested manually on intellij 2018.3 and hopefully after this is merged, I will develop a test in the intellij bazel plugin project, to cover that.
We should probably do the corresponding cleanups in `aspect/intellij_info_impl.bzl`, just to keep it clean and avoid confusion.
> Fixed intellij metadata to include correct source_jars info for scala_import libraries

- scala/scala.bzl
replaced the last remaining occurrences of `native.maven_jar` in `scala_repositories` with `scala_maven_import_external` to ensure consistent behaviour of all external libraries and better integration with intellij IDE.
> replaced 'native.maven_jar' with 'scala_maven_import_external'

- scala_proto/scala_proto.bzl
- test/BUILD
subj.
drive-by: removed old conditional.
@laurentlb @dslomov I really wanted to use `ProtoSourcesProvider` and not `"proto"` like the [docs say](https://docs.bazel.build/versions/master/skylark/rules.html#migrating-from-legacy-providers) but as far as I can see `ProtoSourcesProvider` isn't defined as a symbol. Also see https://github.com/bazelbuild/bazel/issues/3701 and https://github.com/bazelbuild/bazel/issues/3527
Can anyone help us move to the correct pattern?
> scala_proto should require JavaInfo provider and not specific rules

- WORKSPACE
- scala/scala_maven_import_external.bzl
- test/src/main/scala/scalarules/test/fetch_sources/BUILD
- test/src/main/scala/scalarules/test/fetch_sources/FetchSources.scala
- test_rules_scala.sh
This PR is a proposed solution for issue #652 
The decision regarding whether or not to download source jars are implemented in a repository rule that declares dependency in the environment variable, so changes in the environment variable, will force a reload, which is desired in this case.
> suppressing external libraries source fetching based on an env-var

- scala/private/rule_impls.bzl
- scala/scala.bzl
- scripts/ij.bazelproject
- test/BUILD
- test/src/main/scala/scalarules/test/junit/JunitSeparateTarget.scala
- test/src/main/scala/scalarules/test/junit/separate_target/FailingTest.scala
- test/src/main/scala/scalarules/test/junit/separate_target/JunitJavaSeparateTargetTest.java
- test/src/main/scala/scalarules/test/junit/separate_target/JunitSeparateTargetTest.scala
- test/src/main/scala/scalarules/test/junit/separate_target/SomeScalaClass.scala
if `alternatively_discover_tests_from` is set then test discovery is attempted from a different target.
This is in preparation for the introduction of `trim_test_configuration` in bazel which will mean that `scala_library` (even with `testonly = 1`) can't depend on a `scala_junit_test`.
For us (Wix) this will be a problem since often `scala_junit_test` targets contain tests and a bit of test support code which other test support targets (`scala_library`) sometimes depend on.
Additionally such separation can serve us since we can segment compilation rules to test rules and have different worker pools (in remote execution) for the different usage
> Allow alternatively discovering junit tests from a separate target

- jmh/jmh.bzl
- test/jmh/BUILD
This is needed for a future change in Bazel
(`--incompatible_no_transitive_loads`).
Tested:
`bazel test //scala:all //test/... --all_incompatible_changes --incompatible_disallow_legacy_javainfo=false --incompatible_disable_deprecated_attr_params=false`
> Explicitly re-export symbols

- README.md
This prevents getting an error ("The native http_archive rule is deprecated.")
> Adding a load rule for new `http_archive` in the code snippet

- WORKSPACE
- scala_proto/scala_proto.bzl
- src/scala/scripts/PBGenerateRequest.scala
- test/proto/BUILD
Resolves https://github.com/bazelbuild/rules_scala/issues/665
Had to change `com_google_protobuf` and `com_google_protobuf_java` targets in a WORKSPACE otherwise I couldn't run `bazel test //test/...`
> Add blacklisted_protos to scala_proto_srcjar

- scala/scala.bzl
- test/BUILD
If you add `unused_dependency_checker_ignored_targets ` to your scala junit test target, analysis fails with message: 
```
duplicate keyword 'unused_dependency_checker_ignored_targets' in call to scala_junit_test
```
This PR fixes that by merging the ignored targets provided on the target with `_specs2_junit_dependencies`.
> Fix duplicate key error with ignored unused dependencies on scala junit tests

- specs2/specs2_junit.bzl
Accidentally used the 'common' lib hash instead. This is the correct one for v4.3.5 for Scala 2.12.
> Fixing wrong junit hash

- specs2/specs2.bzl
- specs2/specs2_junit.bzl
- src/java/io/bazel/rulesscala/specs2/Specs2RunnerBuilder.scala
- test_rules_scala.sh
This PR subsumes #671, as well as removes some workarounds that were added previously for exceptions thrown from specs2 - it is now handled in the library.
This PR upgrades to v4.1.1 of specs2, which contains the [fix](https://github.com/etorreborre/specs2/pull/727) for the hanging runner.
> Specs2 upgrade 4.4.1

- src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
- test/BUILD
- test/UnusedLib.scala
- test_rules_scala.sh
Fixes #630. I'm really not sure about the test I wrote because it can only pass if the package in question is actually built. Let me know how we can make it better.
> Make unused dependency checker respect checking mode

- .travis.yml
- scala_proto/scala_proto.bzl
- test/proto/BUILD
- test/proto/different_root.proto
- test/proto/different_root2.proto
- test/proto/test_external_dep.proto
This reproduces an issue in bazel 0.22.0 that breaks `scalapb_proto_library`. Issue to follow.
It's expected that the build will fail.
> Add targets that reproduce proto issues in 0.22.0 (and maybe earlier)

- src/scala/scripts/PBGenerateRequest.scala
- test/proto3/BUILD
- test/proto3/test.proto
The owner's workspace_root for proto files that are generated by a
genrule is empty. This means that the root path ends with a trailing
slash. PBGenerateRequest expects the root path to not end in a slash
and removes an additional character (see line 17) which is the expected
path separator after the workspace_root component of the path.
For generated files, this means that the first character of the proto
file path is cut off, and thus the scalapb compiler cannot read the
file.
> Fix root path for generated proto files

- scala/private/rule_impls.bzl
- test_rules_scala.sh
Similar to the java_binary script we should allow users to override the version of java based on the environment rather than using the runfiles version.
> use the JAVA_BIN environmental variable to allow overriding the jdk at runtime

- .travis.yml
- WORKSPACE
- scala/plusone.bzl
- scala/private/common.bzl
- scala/private/rule_impls.bzl
- scala/scala.bzl
- scala/scala_toolchain.bzl
- test_expect_failure/plus_one_deps/BUILD.bazel
- test_expect_failure/plus_one_deps/exports_deps/A.scala
- test_expect_failure/plus_one_deps/exports_deps/B.scala
- test_expect_failure/plus_one_deps/exports_deps/BUILD.bazel
- test_expect_failure/plus_one_deps/exports_deps/C.scala
- test_expect_failure/plus_one_deps/exports_deps/D.scala
- test_expect_failure/plus_one_deps/external_deps/A.scala
- test_expect_failure/plus_one_deps/external_deps/BUILD.bazel
- test_expect_failure/plus_one_deps/internal_deps/A.scala
- test_expect_failure/plus_one_deps/internal_deps/B.scala
- test_expect_failure/plus_one_deps/internal_deps/BUILD.bazel
- test_expect_failure/plus_one_deps/internal_deps/C.scala
- test_expect_failure/plus_one_deps/with_unused_deps/A.scala
- test_expect_failure/plus_one_deps/with_unused_deps/B.scala
- test_expect_failure/plus_one_deps/with_unused_deps/BUILD.bazel
- test_expect_failure/plus_one_deps/with_unused_deps/C.scala
- test_expect_failure/scala_import/ScalaImportPropagatesCompileDepsTest.scala
- test_rules_scala.sh
Tries to balance between sternness of strict-deps off and strict-deps on cache issues and false positives.
We, Wix, have been using `strict-deps=error` for a long time and have been enjoying the relative ease a developer has when needing to add a new dependency.
However the current strict-deps compiler plugin has a serious drawback in generating too many false positives (causing errors about dependencies which aren't really used because of the compiler eagerness). This is a much bigger issue for us then the cache hits (which we also care about) since this means that:
1. Builds on master fail from seemingly innocent changes. This is because we have many repositories in a logical head dependency.
2. Additionally this causes developer fatigue which just try to "please the beast".
OTOH using …
> add plus one deps transitive mode for compilation

- scala/private/rule_impls.bzl
- scala/scala.bzl
This applies the formatting changes from Emacs' bazel-mode, in preparation for https://github.com/bazelbuild/rules_scala/pull/692.
> Reformat core files [split from code coverage PR]

- scala_proto/scala_proto.bzl
- src/scala/scripts/BUILD
- src/scala/scripts/PBGenerateRequest.scala
- src/scala/scripts/ScalaPBGenerator.scala
Remove `protoc-jar` which brings own versions of `protoc`
> Reuse @com_google_protobuf//:protoc when generating scala from proto

- WORKSPACE
- scala/scala.bzl
- test_version/WORKSPACE.template
Looks like there are two versions of `protobuf-java`. One comes from `@com_google_protobuf//:protobuf_java` version `3.6.1.3` and another one from `_scala_maven_import_external` version `3.1.0`. There are warnings which comes from `protobuf-java 3.1.0` although `3.6.1.3` should be used.
> Unify protobuf-java versions

- scala_proto/private/scala_proto_default_repositories.bzl
grpc 1.18 causes a warrning to displayed on JVM versions above 8:
`WARNING: An illegal reflective access operation has occurred`
This is fixed with 1.19.
> use grpc 1.19

- jmh/jmh.bzl
- junit/junit.bzl
- scala_proto/private/scala_proto_default_repositories.bzl
- test/aspect/aspect.bzl
- twitter_scrooge/twitter_scrooge.bzl
`native.maven_jar` does not properly support HTTP(S)_PROXY environment variable. This prevents us from using `rules_scala` in certain network-restricted environments. This PR replaces `native.maven_jar` with `scala_maven_import_external` which does respect proxy environment variables.
I had a few questions:
* How confident are you that test would catch issues with this change? I'll need to manually validate any part of this without clear testing.
* There are a few `maven_jar` references in the WORKSPACE file that I didn't replace because comments describe them as specifically for testing. Should I swap out those too?
* There are some expectation failures in `//test/aspect`. I can't tell if these are real failures or just a consequence of changing how deps are pulled. The log output is: …
> Replace maven_jar with scala_maven_import_external

- WORKSPACE
- scala/scala.bzl
adding it to the WORKSPACE was wrong since now each user needs to do the same action (and we have two contradicting declarations)
> Updated java_stub_template in scala_repositories

- CONTRIBUTING.md
- README.md
- scala/scala_maven_import_external.bzl
Add links to missing rules at the top of the README. Format WORKSPACE
and BUILD file code fragments to match the formatting of buildifier. Fix
typo.
> README fixes

- README.md
`test` inherits from `build`, so the 2nd line is redundant. See: https://docs.bazel.build/versions/master/guide.html#bazelrc-syntax-and-semantics
I'd say that, _generally_, sandboxing in Bazel is preferred. By default you get non-sandboxed workers in Bazel, so I've added the option that enables the sandboxing as an 'easy win'.
> Improve persistent Scalac worker docs in README.md

- scala/private/rule_impls.bzl
Experimental java coverage was [added in Bazel 0.24.0](https://github.com/bazelbuild/bazel/commit/68c7e5a3c679be51f750d44aae146007f0f04b4d), which introduced a new template variable `%set_java_coverage_new_implementation%` to `java_stub_template.txt`. Not handling that substitution results in the following error on build:
```bash
/private/var/tmp/[...]: line 262: fg: no job control
```
This PR resolves the error by enabling the experimental coverage functionality if coverage is enabled, but disables it otherwise. This corresponds to the behaviour of the Java rules. I'm not complete sure if that is applicable for Scala as well.
> Handle experimental java coverage configuration

- README.md
Updated Scala and scala libs versions, highlight the possibility to specify scala_version for `scala_proto_repositories` rule (because default is `2.11.8` and it obviously doesn't work with default scala version).
> [DOCS] README updates 

- WORKSPACE
- scala/private/rule_impls.bzl
- test/src/main/scala/scalarules/test/compiler_plugin/BUILD.bazel
- test/src/main/scala/scalarules/test/compiler_plugin/KindProjected.scala
- test_rules_scala.sh
In BUILD.bazel if you have:
scala_library(
name = "testapp",
plugins = ["@org_spire_math_kind_projector_2_12"]
)
It fails with following error:
File "..../io_bazel_rules_scala/scala/private/rule_impls.bzl", line 123, in paths.append
p.scala.outputs.jar
'struct' object has no attribute 'jar'
Seems like jar attributed has been changed to jars some time ago. This pull request fixes this problem.
> Fix scala rules if scala compiler plugins provided 

- WORKSPACE
- scala/scala_maven_import_external.bzl
bazel repo has [artifact_sha256](https://github.com/bazelbuild/bazel/blob/d8ffad56129e2c358c5b208edb62918c8ed1220c/tools/build_defs/repo/jvm.bzl#L56) arg:
This change aligns rules_scala version of `jvm_import_external` to also have this arg.
See https://github.com/bazelbuild/rules_scala/issues/737
> add arg  to _jvm_import_external to align with bazel repo version

- scala/private/rule_impls.bzl
Change to use the platform-specific path separator. The stub template script already sets `IFS=';'` on Windows so having colons in `CLASSPATH` means it doesn't get split properly.
> Portable classpath in stub template

- .bazelrc.travis
- .travis.yml
- scala/private/rule_impls.bzl
- scala/scala.bzl
- src/java/io/bazel/rulesscala/exe/BUILD
- src/java/io/bazel/rulesscala/exe/LaunchInfo.java
- src/java/io/bazel/rulesscala/exe/LauncherFileWriter.java
- src/java/io/bazel/rulesscala/scala_test/BUILD
- src/java/io/bazel/rulesscala/scala_test/Runner.java
- src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
- src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala
- src/scala/io/bazel/rules_scala/scrooge_support/FocusedZipImporter.scala
- test/BUILD
- test/longnames/looooooongnaaaaaaame/anooooootherlooooooooongname/anooooootherlooooooooongname2/anooooootherlooooooooongname3/LongNamesTest.scala
- test_reproducibility.ps1
- test_rules_scala.ps1
- third_party/unused_dependency_checker/src/main/io/bazel/rulesscala/unuseddependencychecker/UnusedDependencyChecker.scala
This is based on (includes it) the work done as part of: https://github.com/bazelbuild/rules_scala/pull/717 (Windows support) - it fixes `scala_test` rule on Windows. Before this change `scala_test` was using a bit hacky way to pass scala test's Runner arguments by providing a bash script with arguments instead of a java executable (https://github.com/bazelbuild/rules_scala/blob/master/scala/private/rule_impls.bzl#L560). After changes done in https://github.com/bazelbuild/rules_scala/pull/717 bash script is not used on Windows at all, so the workaround for passing args in an embedded bash script is not taken into account at all. With this change args are written into a file and read by the scala-test java wrapper (`io.bazel.rulesscala.scala_test.Runner`), which was already in place for …
> Windows support - scala_test

- README.md
- docs/scala_import.md
Related issue: #721
This PR adds an initial doc for `scala_import`.
I chose to do it as a Markdown table written by hand. The rest of the docs are HTML tables that I think were generated long ago by Skydoc when it still worked. As soon as Stardoc works, generated files should replace these hand maintained files!
I do need a second look with these attributes though, since I don't really know all of them really mean and cribbed the descriptions from:
- https://docs.bazel.build/versions/master/skylark/lib/JavaInfo.html
- https://github.com/bazelbuild/rules_scala/blob/master/docs/scala_library.md
> Document scala_import

- scala_proto/private/proto_to_scala_src.bzl
- scala_proto/private/scalapb_aspect.bzl
- scala_proto/scala_proto_toolchain.bzl
- src/scala/scripts/PBGenerateRequest.scala
- src/scala/scripts/ScalaPBGenerator.scala
- test/proto/BUILD
- test/proto/CustomGeneratedObjectTest.scala
- test/src/main/scala/scalarules/test/extra_protobuf_generator/BUILD
- test/src/main/scala/scalarules/test/extra_protobuf_generator/ExtraProtobufGenerator.scala
This allows adding more generators to scalapb to run within the toolchain. 
Use case here is that i want to generate service definitions that are friendly to twitter's util/futures rather than scala futures. So want to make it extensible to add more scala code generators into the output.
Thoughts @johnynek and @ittaiz ?
> Add support and test for custom generator

- scala/private/rule_impls.bzl
The argument of string.join should be a list of strings. In the future,
Bazel won't perform this implicit conversion.
> Fix for Bazel upcoming change --incompatible_string_join_requires_strings

- scala_proto/private/scalapb_aspect.bzl
Soon, Bazel will forbid iterating directly on a depset.
> Fix compilation for --incompatible_depset_is_not_iterable

- WORKSPACE
- scala/scala.bzl
With this commit, this repository works with Bazel flag `--incompatible_disable_deprecated_attr_params`.
Progress towards #644
> Update protobuf dependency

- scala/private/coverage_replacements_provider.bzl
- test/coverage/expected-coverage.dat
This fixes an issue where the aspect that gathers up coverage data needs access to the scala toolchain, but the scala toolchain is not enabled for the aspect. This results in coverage data only being created for the test targets and none of its transitive deps.
This is the part of the aspect that fails because the toolchain is not enabled for the aspect:
https://github.com/bazelbuild/rules_scala/blob/09790bb54249ab8ad517cd696171bc50a8e8a218/scala/private/coverage_replacements_provider.bzl#L72-L76
The updated `expected-coverage.dat` tracefile shows that more coverage data is being generated.
> Add scala toolchain to aspect

- src/java/io/bazel/rulesscala/specs2/Specs2RunnerBuilder.scala
- test_rules_scala.sh
This change fixes a bug in test.xml generation produced by the bazel JUnit runner. Before this fix, the test.xml produced by the test runner will contain all test cases, regardless whether they ran or not, and incorrectly display them in IntelliJ as successful.
(shows `foo` as having successfully ran even though it never actually ran, due to test filter) 
When providing a `test_filter`, the string is passed to the underlying specs2 runner, so it runs just the filtered tests, but the test model contains all the tests, regardless of the filter. In Java, the underlying model is modified, so the test children which don't match the filter are removed from the model. In Scala the model is immutable, so the solution is to generate a test model that is already filtered. This works by first …
> Prevent showing filtered-out specs2 tests in the test.xml

- README.md
- docs/scala_doc.md
- scala/private/common.bzl
- scala/private/rule_impls.bzl
- scala/scala.bzl
- scala/scala_doc.bzl
- src/scala/io/bazel/rules_scala/scaladoc_support/BUILD
- test/BUILD
- test/src/main/scala/scalarules/test/compiler_plugin/BUILD.bazel
Closes https://github.com/bazelbuild/rules_scala/issues/230.
This PR adds a basic implementation of `scala_doc`.
I hesitate to recommend using it widely yet since I haven't figured out if there are weird edge cases. Would it be better to somehow designate this as experimental or something?
I did _not_ automatically compress outputted scaladoc, instead I think you could use `pkg_tar`.
For an internal target, scaladoc takes ~17sec to scaladoc for "324 documentable templates".
Comparatively, cats-core takes ~32sec to scaladoc for "771 documentable templates":
```
sbt:cats> coreJVM/doc
[info] Main Scala API documentation to /Users/long/oss/cats/core/.jvm/target/scala-2.12/api...
model contains 771 documentable templates
[info] Main Scala API documentation successful.
[success] Total time: 32 …
```
> Add scala_doc rule

- scala/scala_doc.bzl
This will be required by Bazel 0.27, where the flag
`--incompatible_no_support_tools_in_action_inputs` will be on by
default.
The function `collect_plugin_paths` iterates over its argument, so we
need to flatten the depset.
> Explicitly convert depset to list

- scala_proto/default_dep_sets.bzl
- scala_proto/private/scala_proto_default_repositories.bzl
- upgrade `opencensus-java` packages to the latest (`0.22.1`)
- add `opencensus-impl` and `opencensus-impl-core` 
The opencensus stats integration support for gRPC when using a `scala_proto_toolchain` with `with_grpc = True` seems to be missing some transitive dependencies. I'm exporting these metrics with `opencensus-exporter-stats-prometheus` and without this patch nothing is put into the metrics registry. These are [runtime dependencies](https://github.com/census-instrumentation/opencensus-java#add-the-dependencies-to-your-project-1) so it's possible I've declared them in the wrong place in this patch. I'm getting around this right now in my build with this target configuration:
```
load("@io_bazel_rules_scala//scala_proto:default_dep_sets.bzl", "DEFAULT_SCALAPB_GRPC_DEPS") …
```
> fix grpc opencensus stats integration

- README.md
We're using Bazel in our Data Engineering + Data Science monorepo to build Scala (and Python) 🙂
> Add Canva to the adopters list

- scala/private/common.bzl
In 0.27 by default depset's aren't iterable. So just need a simple to_list to do this
> Depset is not iterable

- README.md
> Specify which version of bazel is required.

- src/java/io/bazel/rulesscala/specs2/Specs2RunnerBuilder.scala
- src/java/io/bazel/rulesscala/specs2/package.scala
- test/src/main/scala/scalarules/test/junit/specs2/Specs2Tests.scala
- test_expect_failure/scala_junit_test/BUILD
- test_expect_failure/scala_junit_test/specs2/SuiteWithOneFailingTest.scala
- test_rules_scala.sh
This PR augments the fix introduced in #759. The previous PR introduced a bug with incorrectly flattening JUnit descriptions - their original hashCode value was lost, and this caused failed tests to appear as succeeded in the bazel runner.
This PR replaces the flattening logic by having Specs2 itself create the Descriptions, keeping their original hashCode values.
Adding some tests to make sure only valid results appear in the XML.
@ittaiz
> Specs2 filtering of JUnit descriptions

- README.md
I'm a longtime user of SBT, but completely new to Bazel. The documentation on getting started compiling Scala projects with Bazel is pretty sparse, so thank you for this project! I had to make the following changes to get my first tiny Scala project to build with Bazel. It's unclear to me why I needed to add the Skylib reference, but the build command by default complains about its lack.
> Update "Getting started" WORKSPACE block

- scala/private/rule_impls.bzl
- scala/scala_import.bzl
- test_expect_failure/missing_direct_deps/internal_deps/BUILD
- test_expect_failure/missing_direct_deps/internal_deps/custom-jvm-rule.bzl
- twitter_scrooge/twitter_scrooge.bzl
also did a few nits from the review of #781
> Passing source-jar into JavaInfo

- scala/private/rule_impls.bzl
@iirina I used to think that because we use `java_common.create_provider` then our `JavaInfo` instances are faulty and return empty sequence for `archive[JavaInfo].runtime_output_jars`.
I've now tried to remove this hack thanks to your work but it still returns an empty sequence.
1. Are we constructing the JavaInfo incorrectly?
2. Is the below usage of `outputs.jars` correct?
3. When is `runtime_output_jars` non empty?
> remove usage of attr scala with JavaInfo outputs

- scala/scala.bzl
It seems like `deps` should behave like `runtime_deps` in that a `JavaInfo` provider must be given.
Opening a drive-by PR now to see if CI will build this and confirm my hunch...
> JavaInfo provider should be given for deps

- scala/private/common.bzl
Follow-on from https://github.com/bazelbuild/rules_scala/pull/774.
Since deps now require `JavaInfo` providers this check is no longer needed.
> Remove warning if dep has no JavaInfo since it's required now

- test_reproducibility.sh
https://github.com/bazelbuild/rules_scala/issues/699
> Exclude jmh from reproducibility test, since the code generator is non-deterministic.

- scala/private/rule_impls.bzl
While reviewing `scala_library` attributes I saw that `jvm_flags` is in the common attributes when actually it should be part of the common attributes for binary rules.
Added a print to clarify to users they shouldn't use this attribute and I guess we should remove it completely in ~ a month
> warn if jvm_flags is used in scala_library

- scala/private/rule_impls.bzl
resolve_command shouldn't be required here.
> Simplify _jacoco_offline_instrument.

- tut_rule/tut.bzl
As per https://docs.bazel.build/versions/master/be/general.html
> Do not write informational messages to stdout or stderr. While useful for debugging, this can easily become noise; a successful genrule should be silent. On the other hand, a failing genrule should emit good error messages.
Before this change:
```
$ bazel test test/tut/...
INFO: Analyzed 3 targets (4 packages loaded, 631 targets configured).
INFO: Found 3 targets and 0 test targets...
INFO: From Executing genrule //test/tut:some_example:
[tut] compiling: test/tut/SomeExample.md
wrote: bazel-out/darwin-fastbuild/bin/test/tut/some_example_tut.md
INFO: Elapsed time: 5.178s, Critical Path: 4.49s
INFO: 1 process: 1 darwin-sandbox.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total …
```
> silence tut

- docs/scala_toolchain.md
- scala/private/rule_impls.bzl
- scala/scala_toolchain.bzl
- test_expect_failure/scalac_jvm_opts/BUILD
- test_expect_failure/scalac_jvm_opts/Empty.scala
- test_rules_scala.sh
This is useful for globally setting the max heap usage of Scalac workers. At Stripe, we've seen Scalac workers get killed by the kernel OOM killer because the default JVM heap size is too large.
> Add scalac_jvm_flags option to toolchain

- docs/scala_toolchain.md
- scala/private/rule_impls.bzl
- scala/scala_toolchain.bzl
- test_expect_failure/scala_test_jvm_flags/BUILD
- test_expect_failure/scala_test_jvm_flags/Empty.scala
- test_expect_failure/scala_test_jvm_flags/EmptyTest.scala
- test_rules_scala.sh
This gives `jvm_flags` for `scala_test` the same treatment as in https://github.com/bazelbuild/rules_scala/pull/803. This allows a global config for the maximum amount of heap a `scala_test` may use. We've seen scala_test processes getting OOM-killed in CI. 
Setting an `Xmx` on test runs makes memory-related test failures more deterministic. If a test fails due to excessive memory usage, it should be more deterministic than the whims of the kernel OOM-killer.
> Add `scala_test_jvm_flags` to toolchain

- .travis.yml
- scala/private/rule_impls.bzl
- test/proto/BUILD
- test_expect_failure/proto_source_root/dependency/BUILD
- test_expect_failure/proto_source_root/user/BUILD
Replace it with strip_import_prefix, its spiritual successor.
And apparently some automatic buildifier cleanups.
> Remove the deprecated attribute proto_source_root.

- jmh/jmh.bzl
- scala/private/common.bzl
Migrating in preparation of flipping the flag [--incompatible_disallow_legacy_java_provider](https://github.com/bazelbuild/bazel/issues/7598) in bazel.
> Migrate from old-style .java provider to JavaInfo.

- scala_proto/scala_proto.bzl
If you don't have grpc deps/grpc building enabled this would cause the build to fail.
> Flip GRPC deps around to be correct

- jmh/jmh.bzl
noticed we could improve things when reviewing #807
> Clean up jmh rule a bit

- .bazelrc
- .travis.yml
- test_reproducibility.sh
- test_rules_scala.sh
- test_runner.sh
- tools/bazel
**Description:**
Ports over bazel pinning functionality from https://github.com/higherkindness/rules_scala.
With this, rules_scala developers on Linux/OSX will have Bazel pinned to the version rules_scala expects, automatically, regardless of the global bazel install version. Windows developers will still need to match global bazel with the rules_scala bazel version.
The `tools/bazel` script has been tested extensively (via other projects) for OSX/Linux developers.
**Motivation:**
One hurdle for development on bazelbuild/rules_scala is a lack of Bazel version pinning that's consistent for local development and CI.
> Pin Bazel versions

- CONTRIBUTING.md
- scala/private/common_attributes.bzl
- scala/private/common_outputs.bzl
- scala/private/rule_impls.bzl
- scala/private/rules/scala_binary.bzl
- scala/scala.bzl
This PR moves `scala_binary` to its own file, per convention established in https://github.com/bazelbuild/rules_scala/pull/808.
In the process, I made quite a few formerly private functions in `rule_impls.bzl` public in order for it to be imported by `scala_binary.bzl`. These functions will eventually be moved somewhere else but I'm leaving them in place until rules are split out to avoid even larger PRs. Even with the newly exposed public functions, I figure that by convention a user isn't supposed to be directly loading something from a `private` package anyhow, so I think we can abdicate responsibility and give no guarantees of compatibility if a user is doing that.
Too bad Starlark doesn't have better access modifiers than a leading underscore, but I think if I ever want to untangle …
> Move scala_binary to its own file

- scala/private/common.bzl
- scala/private/common_attributes.bzl
- scala/private/rule_impls.bzl
- scala/private/rules/scala_test.bzl
- scala/scala.bzl
This PR moves `scala_test`/`scala_test_suite` to its own file, per #808 
I relocated `sanitize_string_for_usage` from `scala/scala.bzl` to `scala/private/common.bzl` for now and loaded it in `scala/scala.bzl`, but as things move into `private`, these functions will only be used in `private`.
As I get more familiar with the little private library of functions rules_scala has, perhaps organizing them a bit better like how [rules_haskell](https://github.com/tweag/rules_haskell/blob/b3bea97d7cf133bc5896dfa9d02f0258547b43b8/haskell/private/set.bzl) does for its own private lib would make sense, dunno yet.
> Move scala_test/scala_test_suite to their own file

- scala/private/rules/scala_test.bzl
Remove the `suites` attr from `scala_test`.
Cleaning up per https://github.com/bazelbuild/rules_scala/pull/815#issuecomment-522344994, since it has been a deprecated attr for awhile.
> remove long-deprecated 'suites' attr in scala_test

- .travis.yml
Disable the windows CI.
Address #749. The windows CI has a few tests that fail (protobuf, maybe some others). We don't have any current contributors that have windows machines to test this.
cc @majcherm-da if you have time to try to get this green, either by fixing the issues, or disabling certain tests, PRs would be welcome.
> Disable windows CI

- scala/private/common_attributes.bzl
Formats a file that was missed due to sequencing of merges surrounding #826.
CI is in red. This makes it green :).
> Fix an unformatted file that breaks ci

- .travis.yml
Use travis job pipelines so we have more control than a basic matrix of environment options x OS.
Note: this PR is safe to merge despite the failing lint job. Master is broken, pending a merge of https://github.com/bazelbuild/rules_scala/pull/830.
Short term, this lets us run linters once (just on Linux). Longer term, more job control will be useful if we bring back windows support in CI.
> Use travis job pipelines

- scala/private/rule_impls.bzl
- scala/private/rules/scala_library.bzl
Refactors `build_deployable` and documents it a bit per suggestion in https://github.com/bazelbuild/rules_scala/pull/827#discussion_r315972566.
Restrict the API of this function rather than taking a `ctx` object wholesale.
> Refactor build_deployable

- Governance.md
Fixes up "Reporting bugs" section with my suggestions from https://github.com/bazelbuild/rules_scala/pull/825#discussion_r315472382, along with a few grammatical/tone/Markdown formatting changes.
The latter change is in a separate commit that can be backed out if you don't want to merge that in yet.
Keep the ball moving on https://github.com/bazelbuild/rules_scala/pull/825.
> Governance doc suggestions

- src/java/io/bazel/rulesscala/test_discovery/DiscoveredTestSuite.scala
Was not properly adding space, as such:
```
java.lang.IllegalStateException: Was not able to discover any classes for archives=testsuite/test/example/example.jarprefixes=Set(), suffixes=Set(Test)
```
Fixing for better readability of errors.
> Fix to error message

- scala/private/common_attributes.bzl
- scala/private/rules/scala_binary.bzl
- scala/private/rules/scala_junit_test.bzl
- scala/private/rules/scala_library.bzl
- scala/private/rules/scala_repl.bzl
- scala/private/rules/scala_test.bzl
- test/BUILD
Closes https://github.com/bazelbuild/rules_scala/issues/669.
Removes the warning for `jvm_flags` usage in `scala_library` and instances where they were passed in tests.
Follow up from https://github.com/bazelbuild/rules_scala/pull/795 which advocates for removing the debug completely after some period of time (~a month). Feel free to table this if it's too soon and I'll close for now.
> Remove jvm_flags debug print for scala_library

- java_stub_template/file/file.txt
Improve classpath manifest file construction
See: https://github.com/bazelbuild/bazel/pull/9314
> Improve classpath manifest file construction

- scala/scala_import.bzl
Reworks some code in `scala_import` to use `java_common.merge` instead of manually creating depsets in utils.
Tests should still pass.
I had remembered seeing this `TODO` before and it seems easy enough to fix. Deleting unneeded code!
> Use java_common.merge instead of manual _collect util functions in scala_import

- src/scala/scripts/PBGenerateRequest.scala
- src/scala/scripts/ScalaPBGenerator.scala
- test/src/main/scala/scalarules/test/scripts/BUILD
- test/src/main/scala/scalarules/test/scripts/PBGenerateRequestTest.scala
Through numerous trial-and-errors it was found that copying `proto` files is only necessary when they are withing well-known `com_google_protobuf` package. For unknown reasons (could be related to the fact that `protoc` also comes from `com_google_protobuf`) Bazel passes incorrect path that is used in `--proto_path`. This proposal shows a way to fix the `transitiveProtoPaths` by analyzing the `includedProtos` list of `proto` files.
1. We have a list of all required `.proto` files in `includedProtos` -- this is a tuple list (root -> full path), for example:
```
bazel-out/k8-fastbuild/bin -> bazel-out/k8-fastbuild/bin/external/com_google_protobuf/google/protobuf/source_context.proto
```
2. Convert the full path to relative from the root (as it was done in …
> Fix paths in --proto_path and avoid copying proto files

- test/shell/test_scala_library_jar.sh
It fixes the issue that `scala_library_jar_without_srcs_must_fail_on_mismatching_resource_strip_prefix` is not testing correctly.
Fixes #857
Intermediate step for test refactoring.
> Fix test_scala_library_jar.sh

- test/shell/test_scala_import_source_jar.sh
It fixes the issue that `test_scala_import_source_jar_should_not_be_fetched_when_env_bazel_jvm_fetch_sources_is_set_to_non_true` is not testing correctly.
Fixes https://github.com/bazelbuild/rules_scala/issues/856
Intermediate step for test refactoring.
> Fix test_scala_import_source_jar.sh

- README.md
[From this it's my understanding](https://github.com/bazelbuild/rules_scala/pull/861#issuecomment-540713730) that `0.28.0` can remain at `HEAD` as CI is still being run for that version.
https://github.com/bazelbuild/rules_scala/issues/862#issuecomment-541296893
> Include Bazel 1.0.0 in compatibility table

- .travis.yml
- README.md
- tools/bazel
> Bump v1.0.0 compatibility test to v1.1.0

- .travis.yml
- README.md
- tools/bazel
Fixes #880
Followup PR of #882 
Relates to #881
> Bump v1.1.0 compatibility test to v1.2.1

- .travis.yml
- README.md
- tools/bazel
Bump Bazel to the latest `v2.0.0`.
relates to bazelbuild/bazel#10131
> Bump Bazel to v2.0.0

- scala/private/rule_impls.bzl
- test/plugins/BUILD
- test/plugins/check_expand_location_plugin.scala
- test/plugins/trivial.scala
https://github.com/bazelbuild/rules_scala/pull/890 but with an additional adjustment to support usages of the compile function from rules without the `plugins` attribute.
Specifically:
```python
scalacopts_expansion_targets = getattr(ctx.attr, 'plugins', [])
scalacopts = [ctx.expand_location(v, scalacopts_expansion_targets) for v in toolchain.scalacopts + in_scalacopts]
```
instead of
```python
scalacopts = [ctx.expand_location(v, ctx.attr.plugins) for v in toolchain.scalacopts + in_scalacopts]
```
> expand locations in scalacptops, take 2

- scala/private/rule_impls.bzl
Plugin expansion- Use input plugins param instead of ctx
Reduce usage of ctx in inner methods.
This also allows custom logic in the rules to which attributes they use
> Plugin expansion- Use input plugins param instead of ctx

- WORKSPACE
- jmh/jmh.bzl
- junit/junit.bzl
- scala/private/macros/scala_repositories.bzl
- scala_proto/private/scala_proto_default_repositories.bzl
- scala_proto/scala_proto.bzl
- specs2/specs2.bzl
- specs2/specs2_junit.bzl
- twitter_scrooge/twitter_scrooge.bzl
Use https to access central.maven.org.
Closes https://github.com/bazelbuild/rules_scala/issues/918
Maven now requires to use https instead of http. See https://support.sonatype.com/hc/en-us/articles/360041287334
This replaces all instances of http://central.maven.org by https://central.maven.org.
Code using rules_scala fails to build due to 501 errors.
> Use https to access central.maven.org

- scala/private/phases/phase_final.bzl
- scala/private/rule_impls.bzl
- scala/scala_import.bzl
Remove remaining attributes.
This is part of a larger effort of removing all attributes we're returning and return only providers. 
Attributes were either:
1. Moved to DefaultInfo provider
2. Removed because they were redundant (pre phases they were needed in internal communication)
3. Coverage which moved to its own provider
Followup on #913 
Supersedes #914 (more accurate name and better git history)
Be Bazel 3.0.0 compliant per this bazel [issue](https://github.com/bazelbuild/bazel/issues/7347) and unifying on JavaInfo.
The above issue is also where I got the recommendation of how to move coverage to a provider from
> Return providers array instead of legacy struct

- scala/private/phases/phase_declare_executable.bzl
- scala/private/rule_impls.bzl
Move `declare_executable` to the phase file. There is no need for importing from other file.
Clean-up work of phase PR.
> Move declare_executable to phase file

- README.md
Somehow we run into the Bazel fetch dependencies issue as below:
```
ERROR: Failed to load Starlark extension '@bazel_skylib//lib:dicts.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
- @bazel_skylib
This could either mean you have to add the '@bazel_skylib' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
```
We fixed the issue by changing the order in our `WORKSAPCE` file.
> chore(docs): update WORKSPACE setup for skylib

- scala/private/phases/phase_final.bzl
Remove redundant coverage handling in scalatest final
Clean-up
Was looking over the phase architecture follow up tasks and saw the coverage smell issue.
Wanted to understand complexity and noticed that the call chain ends up leading to a constant `[]` so I just dropped it.
https://github.com/bazelbuild/rules_scala/blob/master/scala/private/phases/phase_write_executable.bzl#L28
https://github.com/bazelbuild/rules_scala/blob/master/scala/private/phases/phase_write_executable.bzl#L48
https://github.com/bazelbuild/rules_scala/blob/master/scala/private/phases/phase_write_executable.bzl#L67
https://github.com/bazelbuild/rules_scala/blob/6c16cff213b76a4126bdc850956046da5db1daaa/scala/private/rule_impls.bzl#L662
> scalatest final-remove redundant coverage handling

- src/java/io/bazel/rulesscala/exe/LauncherFileWriter.java
Fix for https://github.com/bazelbuild/rules_scala/issues/796
As per [java_launcher.cc](https://source.bazel.build/bazel/+/master:src/tools/launcher/java_launcher.cc;l=364) the jvm args should be delimited by a tab character.
> Use correct delimiter for jvm_flags launcher parameter

- scala/private/phases/phase_final.bzl
- test/BUILD
- test/shell/test_build_event_protocol.sh
- test/src/main/scala/scalarules/test/junit/HelloWorldJunitTest.scala
added a passing e2e for java jar of scala library for symmetry
exposing java jar to BEP from all binary rules
added a passing e2e for java jar of scala library for symmetry
When working on my bazelcon talk I realized we only expose the scala jar from binary targets. Anyone using java and scala and leveraging the BEP file will feel this. We (at Wix) mainly separate compilation from test targets so we don't feel it a lot but I expect that as people become more liberal with using scala_binary it might pop up more.
> exposing java jar to BEP from all binary rules

- scala/private/common.bzl
remove unused method
I'm trying to see if I can remove our excessive usage of `to_list` of depsets and I saw this unused method so I decided to drop it
> remove unused method

- .travis.yml
- README.md
- scala/private/phases/api.bzl
- scala/private/rules/scala_binary.bzl
- scala/private/rules/scala_junit_test.bzl
- scala/private/rules/scala_library.bzl
- scala/private/rules/scala_repl.bzl
- scala/private/rules/scala_test.bzl
- test/phase/providers/BUILD.bazel
- test/phase/providers/phase_providers_expose.bzl
- tools/bazel
Custom phases expose custom providers  
While doing it I found and fixed a bug in phases adjustments of first/last (they were duplicated).
I tried to send a fix for this separately but since actions are de-duped and the info passed between phases via structs is also de-duped I couldn't get a failing test. I could do it with `print` statements but I think that's too hacky.
I stumbled on to the issue in this change because Bazel forbids multiple providers of the same type. 
Btw, main implication (apart from providers) of this specific bug is a perf hit for analysis case (when adjusting phases).
Additionally this mandates bazel 2.0.0 as they have some kind of bug with providers before that (don't have an issue to ref but couldn't get the build to pass with lower bazel version)
Allow custom …
> Custom phases expose custom providers

- docs/customizable_phase.md
- scala/private/phases/api.bzl
- scala/private/phases/phase_collect_jars.bzl
- scala/private/phases/phase_compile.bzl
- scala/private/phases/phase_default_info.bzl
- test/phase/providers/BUILD.bazel
- test/phase/providers/phase_providers_expose.bzl
- test/phase/providers/phase_providers_override.bzl
Phases can override providers from previous phases
external_phases now return a dict and not an array.
Full customizability of phases require them to be able to override providers from previous phases to control what ever is being exposed
> Phases can override providers from previous phases

- scala/private/phases/phase_compile.bzl
- scala/private/resources.bzl
- scala/private/rule_impls.bzl
- scala_proto/private/scalapb_aspect.bzl
- src/java/io/bazel/rulesscala/scalac/CompileOptions.java
- src/java/io/bazel/rulesscala/scalac/Resource.java
- src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
- test/proto/BUILD
- test/proto/PackProtosTest.scala
- test/proto/some/path/nested.proto
- test/proto/standalone.proto
Bundle input protos together with generated/compiled classes
We have lots of unresolved proto imports in intellij and this happens because intellij's protobuf plugin cannot find imported proto files on the classpath.
Bundling proto files with compiled code doesn't look like unusual practice. I mean jars produced by google carries both class files and proto files for example [protobuf-java](https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.11.1/)
Implementation might look a bit aggressive on resource prefix handling but I had two options ie touch only `scala/private/rule_impls.bzl` or align it with `scala/private/phases/phase_compile.bzl` and I chose later. I could do it in separate PR but I'm afraid it would look like a random refactoring by a random guy without clear …
> Bundle input protos together with generated/compiled classes

- .gitignore
Ignores the .metals directory created by Emacs (for me) and VSCode if you've got Metals installed.
We ignore the IntelliJ dir, we should ignore the Metals dir too.
> ignore the .metals dir created by VSCode/Emacs with metals

- WORKSPACE
- jmh/jmh.bzl
- junit/junit.bzl
- scala/private/macros/scala_repositories.bzl
- scala/scala_cross_version.bzl
- scala/scalafmt/scalafmt_repositories.bzl
- scala_proto/private/scala_proto_default_repositories.bzl
- specs2/specs2.bzl
- specs2/specs2_junit.bzl
- twitter_scrooge/twitter_scrooge.bzl
Unify all maven server urls in one place.
Travis CI constantly get `GET returned 403 Forbidden`. Using multiple urls helps downloading artifacts from Maven to be more resilient.
> Unify all maven urls

- README.md
We update the versions of Scala which are supported.
The new policy is that only the last two minor versions of
each of the major versions are supported, though older
versions may still work.
Without sufficient resources, especially in the CI pipeline,
supporting all minor versions as previously done becomes
rather burdensome. One example is noted in https://github.com/bazelbuild/rules_scala/issues/966
> Update scala version support information

- scala/private/phases/phase_compile.bzl
Remove unused return fields in `phase_compile`.
These fields are collected but not used anywhere in the future phases. It would be good to simplify the struct as we move to return providers between phases.
Let me know if they are here for a purpose.
> Simplify phase_compile return struct

- CONTRIBUTING.md
- dangerous_test_thirdparty_version.sh
Add a per-scala-version test for dependency analyzer which can be run as needed.
As part of https://github.com/bazelbuild/rules_scala/issues/867 the dependency analyzer will become a bit more complex so we want an easy way to run some tests against all supported versions of scala. This is a bit hackish and can hopefully be replaced once https://github.com/bazelbuild/rules_scala/issues/962 progresses sufficiently.
> Add a per-scala-version test for dependency analyzer

- scala/private/paths.bzl
- scala/private/phases/phase_compile.bzl
- scala/private/phases/phase_scalafmt.bzl
- scala/private/rule_impls.bzl
Move "get files with extension" logic to a helper function.
We have a conversation https://github.com/bazelbuild/rules_scala/pull/975#discussion_r373098148 of possible ways to reduce the use of `dependency.bzl`. We can have a helper function, which can be used in `dependency.bzl` in the future, lives in `rule_impls.bzl` to reuse duplicate code.
> Get files with extension

- scala/private/rule_impls.bzl
Use skylib paths.is_absolute.
Extract common code out of rules_scala #936
> Use skylib path is_absolute

- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinder.scala
- third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinderTest.scala
Remove a false positive in AST walker where a never-provided default argument is flagged.
For a default argument that a caller doesn't supply, we shouldn't record the caller as needing that argument's type. Hence we detect such cases and skip them.
We wish to reduce false positives in the AST checker.
> Handle default args in AST walker

- README.md
- src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala
- test/shell/test_misc.sh
- test_expect_failure/jmh/BUILD
- test_expect_failure/jmh/InvalidBenchmark.scala
- test_expect_failure/jmh/ValidBenchmark.scala
Currently, if there are errors in some (but not all) benchmarks, running `bazel run //path/to/benchmark` will compile them, fail on some, and then run the rest.
This changes that behavior so that any JMH build failure will fail the build.
If people are relying on these errors not failing the build, or are unaware, this will break their build. I'd argue they have undefined behavior anyway in this case.
Our benchmarks for one project in the [digital-asset/daml](https://github.com/digital-asset/daml) monorepo were broken for quite some time before we realized (see https://github.com/digital-asset/daml/issues/4229).
> When building JMH benchmarks, fail on error, instead of proceeding.

- scala/private/phases/phase_compile.bzl
For the scalatest rule, we add the scalatest library to the unused dependency checker ignore list, as that library is always imported by the rule itself.
This removes a false positive in unused dependency checker.
> Ignore scalatest in unused dependency checker

- manual_test/scalac_jvm_opts/BUILD
- scala/private/macros/scala_repositories.bzl
- scala_proto/private/scalapb_aspect.bzl
- scala_proto/scala_proto.bzl
- test/proto/BUILD
- test/proto2/BUILD
- test/proto3/BUILD
- test_expect_failure/proto_source_root/dependency/BUILD
- test_expect_failure/proto_source_root/user/BUILD
- test_version/version_specific_tests_dir/proto/BUILD
- test_version/version_specific_tests_dir/proto2/BUILD
- third_party/bazel/src/main/protobuf/BUILD
Bazel will rewrite Protobuf rules in Starlark and remove their native equivalents.
As a first step, everyone will be required to add load statements for `proto_library`.
This change adds them for rules_scala.
https://github.com/bazelbuild/bazel/issues/8922
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/402#9082639a-6464-4821-bf47-3b93e00f37e0
> Make rules_scala compatible with --incompatible_load_proto_rules_from_bzl

- README.md
- scala/plusone.bzl
- scala/private/dependency.bzl
- scala/private/phases/phase_dependency.bzl
- scala/scala_toolchain.bzl
- test/scala_test/A.scala
- test/scala_test/B.scala
- test/scala_test/BUILD
- test/shell/test_deps.sh
- test/shell/test_helper.sh
- test/shell/test_unused_dependency.sh
- test/toolchains/BUILD.bazel
We expose several dependency configuration options in the scala toolchain.
These include options for dependency mode, strict deps mode, and dependency tracking method. In particular, this exposes an option for the new strict deps mode being developed in https://github.com/bazelbuild/rules_scala/issues/867 so that people can now start trying it out.
We deprecate a few methods as described in the readme, for future removal.
Part of improving the strict deps/unused deps checking for plus-one dependency mode, as detailed in https://github.com/bazelbuild/rules_scala/issues/867 .
> Update dependency configuration options

- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinder.scala
- third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinderTest.scala
We change the dependency analyzer AST mode to ignore annotations on base classes.
This removes a false positive for the dependency analyzer.
> Ignore base class annotation

- private/BUILD
- scala/BUILD
- scala_proto/BUILD
- specs2/BUILD
- src/java/io/bazel/rulesscala/coverage/instrumenter/BUILD
- src/java/io/bazel/rulesscala/exe/BUILD
- src/java/io/bazel/rulesscala/io_utils/BUILD
- src/java/io/bazel/rulesscala/jar/BUILD
- src/java/io/bazel/rulesscala/scala_test/BUILD
- src/java/io/bazel/rulesscala/scalac/BUILD
- src/java/io/bazel/rulesscala/worker/BUILD
- test/BUILD
- test/coverage/BUILD
- test/example_jars/BUILD
- test/jmh/BUILD
- test/proto/BUILD
- test/src/main/scala/scalarules/test/scala_import/BUILD
- test/src/main/scala/scalarules/test/twitter_scrooge/thrift/bare_jar_thrifts/BUILD
- test_expect_failure/missing_direct_deps/internal_deps/BUILD
- test_expect_failure/transitive/java_to_scala/BUILD
- test_expect_failure/transitive/scala_to_java/BUILD
- test_version/version_specific_tests_dir/BUILD
- test_version/version_specific_tests_dir/proto/BUILD
- test_version/version_specific_tests_dir/src/main/scala/scalarules/test/twitter_scrooge/thrift/bare_jar_thrifts/BUILD
- third_party/bazel/src/main/protobuf/BUILD
load java_library/java_binary_java_import explicitly
This PR was created by running `buildifier --lint=fix -warnings=native-java -r  .` on the repo thanks to https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md
fixes #893 
I'll send a few more based on everything the buildifier automatic fixes can
> load java rules explicitly

- test/BUILD
load py_binary explicitly
This PR was created by running buildifier --lint=fix -warnings=native-py -r . on the repo thanks to https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md
fixes #894 
Stacked PR on top of #999 (will rebase after it's merged)
> load python rules explicitly

- third_party/dependency_analyzer/src/test/BUILD
- third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/ScalacDependencyTest.scala
We add some tests that scalac needs the dependencies that we think they need.
As part of https://github.com/bazelbuild/rules_scala/issues/867 it will be useful to know whenever our assumptions is violated by e.g. a new scala version.
> Add test for scalac dependencies

- specs2/specs2.bzl
- specs2/specs2_junit.bzl
- test/aspect/aspect.bzl
specify deps for specs2 and specs2-junit deps 
Strict-deps and unused-deps https://github.com/bazelbuild/rules_scala/issues/867#issuecomment-586413125
>  specify deps for specs2 and specs2-junit deps 

- README.md
Reverts bazelbuild/rules_scala#1001
Apparently I was wrong in removing them:
https://github.com/bazelbuild/rules_scala/pull/1001#issuecomment-587464520
> Revert "remove spotify from adopters"

- scala/scalafmt/BUILD
- scala/scalafmt/scalafmt_repositories.bzl
Scalafmt supports Scala 2.12.
I also upgrade the Scalafmt version to `2.3.2`.
Users should be able to run formatting on Scala 2.12.
> Scalafmt 2.12 support

- scala/private/phases/phase_coverage.bzl
- src/java/io/bazel/rulesscala/coverage/instrumenter/JacocoInstrumenter.java
- test/coverage/A1.scala
- test/coverage/A2.scala
- test/coverage/B1.scala
- test/coverage/B2.java
- test/coverage/BUILD
- test/coverage/C2.scala
- test/coverage/TestAll.scala
- test/coverage/TestB2.java
- test/coverage/expected-coverage.dat
Fixes code coverage output to more aptly point to the source file. This allows tools like intellij's code coverage to work without any other issues.
Should also allow java coverage that's pulled into a scala library.
I'm open to making changes here, but the main idea is that bazel / jacoco allows for a file in the jar that ends with `-paths-for-coverage.txt` and rather than stitching together a file name from its package it will leverage these source 'hints' we provide it. 
I wanted code coverage in intellij.
> Fix source pathing for code coverage

- third_party/bazel/src/main/protobuf/worker_protocol.proto
Updates our copy of the worker protobuf file from ~https://github.com/bazelbuild/rules_scala/blob/master/third_party/bazel/src/main/protobuf/worker_protocol.proto~ https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/worker_protocol.proto.
The worker protobuf protocol has been updated to support multiplexing workers which can handle multiple concurrent requests in a single process. We can eventually leverage this to support parallel Scalac unit compilation without running extra JVM processes.
> update to the latest worker protobuf file

- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinder.scala
- third_party/dependency_analyzer/src/test/BUILD
- third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinderTest.scala
- third_party/utils/src/test/io/bazel/rulesscala/utils/TestUtil.scala
In the dependency analyzer ast-mode, we now report macros as used.
If a macro is used then the macro should be considered a strict dep for obvious reasons.
Relates to https://github.com/bazelbuild/rules_scala/issues/679
> Report macros as used

- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinder.scala
We remove unnecessary usage of foreach with fullyExploreTree in the AST used jar finder and simplify the interface.
In two places in the code we were calling `Tree.foreach(fullyExploreTree)`. This is redundant because `fullyExploreTree` calls `foreach` on the tree already. So we change those usages to just `fullyExploreTree(Tree)`.
We also change `fullyExploreTree` to not call `exploreTree` on its parameter, because this is redundant with `tree.foreach`.
Nobody should be calling `exploreTree` as it only partially explores the tree and everyone should just be fully exploring the tree, so we move `exploreTree` into `fullyExploreTree` and rename it `visitNode` (which is still not the best of names).
> Don't unnecessarily use fullyExploreTree

- third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinderTest.scala
Add tests around the behavior of imports in the ast dependency checker
This documents existing behavior of the ast dependency checker.
> Add tests for imports

- README.md
- docs/coverage.md
- scala/BUILD
- test/coverage/BUILD
- test/shell/test_misc.sh
toolchain which turns on coverage is part of API
followup on #1017 
Don't want documentation to point to test code which can easily change and break
> toolchain which turns on coverage is part of API

- WORKSPACE
- scala/private/macros/scala_repositories.bzl
- scala/scala_cross_version.bzl
- test_version/WORKSPACE.template
This PR exposes the fetch_sources to scala_repositories.
https://github.com/bazelbuild/rules_scala/issues/908
Being able to inspect sources can be really helpful to understanding how Scala works.
See more reasons: https://github.com/bazelbuild/rules_scala/issues/908
> Add fetch_source parameter to scala_repositories

- scala_proto/default_dep_sets.bzl
- scala_proto/private/scala_proto_default_repositories.bzl
- src/scala/scripts/BUILD
Upgrading scalapb to the latest version supported for Scala 2.11
Since this is a minor version upgrade in scalapb, there may be binary, and perhaps API incompatibilities. 
https://github.com/bazelbuild/rules_scala/issues/667
So that I can use sparksql-scala and lenses without binary incompatibilities.
There are some tests that are failing can someone  give me some pointers on why they are failing.
In particular, it looks like this target `//test/proto:test_service-fast` is failing to build but running `bazel build //test/proto:test_service-fast` says that the target does not exist.
Here's the full error message:
```
(base) nudomsak-pro:rules_scala napasudomask$ bazel build //test/...
DEBUG: /private/var/tmp/_bazel_napasudomask/27b4d30503e20c142fbe6514959c12c2/external/bazel_skylib/lib.bzl: …
```
> upgrading scalapb

- README.md
- scala/scala_toolchain.bzl
- test_expect_failure/plus_one_deps/BUILD.bazel
We remove `plus_one_deps_mode` from the toolchain, as it has been superseded by `dependency_checker_mode`.
We remove a deprecated construct since a sufficiently long period of time has passed.
> Remove plus_one_deps_mode

- test_lint.sh
take lint command as an input to test_lint.sh
#826 inadvertently broke the ability to run `./test_lint.sh fix` locally by hardocding `check` as the only option. This change returns this ability to also align with the instructions in the readme.
Easier way to run lint fix and one that is aligned with the docs
> revive test_lint fix ability

- scala_proto/private/scala_proto_default_repositories.bzl
Reopened #1029 with only single change.
Failure happens with scala 2.12:
```
ERROR: /private/var/tmp/_bazel_darl/e51d20ff8cabb9ee5d304a36295c1184/external/io_bazel_rules_scala/scala/scala_cross_version.bzl:60:18: Traceback (most recent call last):
File "/Users/darl/projects/backend/WORKSPACE", line 67
scala_proto_repositories(<1 more arguments>)
File "/private/var/tmp/_bazel_darl/e51d20ff8cabb9ee5d304a36295c1184/external/io_bazel_rules_scala/scala_proto/scala_proto.bzl", line 38, in scala_proto_repositories
scala_proto_default_repositories(<2 more arguments>)
File "/private/var/tmp/_bazel_darl/e51d20ff8cabb9ee5d304a36295c1184/external/io_bazel_rules_scala/scala_proto/private/scala_proto_default_repositories.bzl", line 133, in scala_proto_default_repositories …
```
> fixes after scalapb upgrade

- README.md
- scala/BUILD
- src/java/io/bazel/rulesscala/specs2/BUILD
- src/scala/scripts/BUILD
- test/shell/test_deps.sh
- test/shell/test_unused_dependency.sh
- test/src/main/scala/scalarules/test/srcjars_with_java/BUILD
- test/toolchains/BUILD.bazel
- test_rules_scala.sh
`ast_plus_one_deps_strict_deps_unused_deps_error` toolchain has more coverage and first class
This PR moves `//scala:ast_plus_one_deps_strict_deps_unused_deps_error` toolchain to the prod section since we now promote it as the alternative but leave users up to stitching everything themselves. I also added reference to it in the readme.
Additionally it builds and tests `test/...` with this toolchain to surface issues like #1029.
Better coverage for AST and other combo and better alignment with our approach.
1. Should we choose a more concise name for the toolchain? Right now it's honest and complete but I'm not sure we should stick to it (wasn't sure what the abstraction is OTOH).
2. I needed to add quite a few `unused_dependency_checker_ignored_targets` exclusions to get the build …
> Add more tests which use ast_plus_one_deps_strict_deps_unused_deps_error toolchain

- README.md
- scala/scala_toolchain.bzl
We change the default dependency tracking method to ast mode when the dependency mode is either transitive or plus-one.
We do this as a step in making the dependency tracking method non-configurable. This will hopefully help us find more errors in ast mode.
> Change dependency tracking method default in some cases

- docs/customizable_phase.md
- docs/phase_scalafmt.md
Adding documentation about IntelliJ plugin incompatibility as requested in https://github.com/bazelbuild/intellij/issues/1824.
We need to document that custom rule names won't work with IntelliJ which is not obvious.
> Document IntelliJ plugin incompatibility with custom rule names

- .travis.yml
- test_version.sh
- test_version/WORKSPACE.template
- test_version/version_specific_tests_dir/BUILD
Update the `test_version.sh` machinery to work with recent versions of the repo.
Changes:
- There were some missing dependencies and setup steps in `WORKSPACE.template`.
- The path to `test/shell/test_runner.sh` from `test_version.sh` was wrong.
- One target used the invalid `jvm_flags` attribute. Changed it to `scalac_jvm_flags`. **Question:** Should these flags be added as `javac_jvm_flags` as well?
Result:
`./test_version.sh` now passes.
Questions:
- Would it be possible to add `./test_version.sh` to travis somewhere, so that it doesn't regress again?
It would be useful to extend this machinery to test In #1050.
> Fixes to make test_version.sh work

- README.md
- WORKSPACE
- scala/scala_cross_version.bzl
- test/coverage/expected-coverage.dat
- test/src/main/scala/scalarules/test/scala_import/nl/ScalaImportNeverLinkTest.scala
scala 2.12.10 is default version
#703
> scala 2.12.10 is default version, closes #703

- WORKSPACE
Suggesting a very straightforward change.
1. Making sure we are using the a **release** version of bazeltools so we can keep track of how far behind are we
2. Updating to the latest release `3.3.0`
In general - we do want to make sure that our code is well linted.
I wanted to check out what we already have and I noticed that the current `lint.sh` only calls `bazel run //tools:buildifier@fix` which depends on the version of buildifier we bring from the WORKSPACE.
Without getting into the details I wanted to make sure we use the latest version and that it's easy to understand which version we depend on.
> [bazel-buildtools] Use latest released version

- jmh/jmh.bzl
- test/jmh/BUILD
The PR switches the version of `JOpt Simple` from `5.0.3` to `4.6`.
The `JMH` support introduces a dependency to the version `5.0.3` of `JOpt Simple`. However the `JMH` library is built against the version `4.6` of `JOpt Simple`. In current state the command line parsing functionality of JMH is partially broken (see test `//test/jmh:jmh_command_line_parsing_test`).
> Fix JOpt Simple version

- test/src/main/scala/scalarules/test/twitter_scrooge/twitter_scrooge_test.bzl
The behavior of the sets module changed in Skylib (internal
representation moved from depset to dict), which changed the API.
With this change, we stop using the sets module and we make the test
more explicit.
This fixes compatibility with the Bazel flag
--incompatible_disable_depset_items (planned in Bazel 4.0) as well as
the next release of Skylib.
> Remove call to obsolete function asserts.set_equals

- README.md
Buildkite badge is falsely showing that the build is failing. 
IMO - it should show the latest status of master branch
> [Minor change] Show buildkite badge according to master status

- test/shell/test_misc.sh
Since `test_disappearing_class` checks bazel/scala caching I believe it is important to isolate builds from other tasks. Although I don't have a 100% proof but I think test is failing for some PRs because multiple tasks build same targets and write to same output/cache directories. This change fixed build for https://github.com/bazelbuild/rules_scala/pull/1071
`test_disappearing_class` is failing for seemingly unrelated changes.
See PRs https://github.com/bazelbuild/rules_scala/pull/1071 and https://github.com/bazelbuild/rules_scala/pull/1080 as an example. Later one doesn't even touch any scala/starlark code.
> Move test_disappearing_class to dedicated output base and disk cache dir

- src/java/io/bazel/rulesscala/specs2/Specs2RunnerBuilder.scala
- test/shell/test_scala_specs2.sh
- test/src/main/scala/scalarules/test/junit/specs2/Specs2Tests.scala
Filtering of specs2 test classes with many examples is slow because of inefficient construction of list of examples that needs to be run. For each included example all examples are scanned in test class.
Fixes https://github.com/bazelbuild/rules_scala/issues/1014
> Fix slow specs2 filtering

- .travis.yml
Adding another automatic test (that doesn't fail the build) that will always check the repo against latest release of bazel.
This can help us identify breaking changes as early as possible and prepare mitigations and adjust the code.
> [travisci] dry check latest bazel version

- test/shell/test_misc.sh
- test_expect_failure/transitive/java_to_scala/BUILD
`scala_export_to_java` was removed in https://github.com/bazelbuild/rules_scala/pull/227/files#diff-9957b181001dad28e385437a86e99126L788 but is still used in `rules_scala/test_expect_failure/transitive/java_to_scala/BUILD`
`bazel build test_expect_failure/transitive/java_to_scala:d` was indeed failing but for different reason than expected. However current `test_transitive_deps` was passing because it checks only exit code and not exact reason. I tried to tighten assertion but not really sure about proposed bash changes.
I tried to open repository with vscode which queried bazel build targets with `bazel query ...:* --output=package` and that failed with `file '//scala:scala.bzl' does not contain symbol 'scala_export_to_java'`
> Remove usage of scala_export_to_java

- README.md
- test_version/WORKSPACE.template
As described in #1083, there's no official guideline yet on how to set up transitive repository deps.
In the interim, this PR modifies the "Getting Started" section of the `Readme.md` (and the example `WORKSPACE.template`) to add the necessary dependencies.
We would like the "Getting Started" workflow to be as close to "copy, paste and go" as possible. This means that we need to include those dependencies in the Readme, even if some users end up having to modify it afterwards to fit their project needs.
Fixes #1083
> Add protobuf deps to "Getting Started"

- scala_proto/private/scala_proto_default_repositories.bzl
- src/scala/scripts/BUILD
- src/scala/scripts/ScalaPBWorker.scala
Remove dependency on `com.thesamet.scalapb:scalapbc` which is not really useful:
- `scalapb.ScalaPbcException` has no any significance and can be replaced with any exception
- `ScalaPBC.processArgs` doesn't do any significant work because arguments are passed as is later to `protoc` (except those that are meaningful to `ScalaPBC` itself and are not passed from `rules_scala`)
From [ScalaPB documentation](https://scalapb.github.io/docs/scalapbc)
> ScalaPBC is a tool that lets you generate Scala sources from the command line (or from a maven build)
So basically this library is an executable which integrates `protocjar` with `ProtocBridge`.
`rules_scala` doesn't use `protocjar` and calls `ProtocBridge` directly.
> Remove dependency on com.thesamet.scalapb:scalapbc

- test/shell/test_twitter_scrooge.sh
- test/src/main/scala/scalarules/test/twitter_scrooge/thrift/Thrift1.thrift
- test_rules_scala.sh
- twitter_scrooge/twitter_scrooge.bzl
This adds support for compiling twitter scrooge files with jdk11.
scrooge makes use of the `@javax.annotation.Generated` annotation when code gen'ing `union`s. The location of this annotation moved between jdk8 and jdk11. The `javax.annotation-api` dep I added shims this definition in.
You can see the scrooge project making the same change here: https://github.com/twitter/scrooge/commit/78b06e92b9a5268f1c684eb186f7bff1dd429886
Related issue: https://github.com/twitter/scrooge/issues/299
> Add javax annotations-api so it works with jdk 11

- scala/private/phases/phase_default_info.bzl
- test/BUILD
- test/rootpaths_binary.sh
This PR fixes a bug where `rootpath` on a `scala_binary` resolved to the JAR instead of the wrapper binary.
This fixes a bug introduced by
https://github.com/bazelbuild/rules_scala/pull/958. Before #958,
`rootpath` on a Scala binary resolved to the wrapper binary so other
rules could treat it as an opaque executable. After that PR `rootpath`
now resolves to the JAR instead of the wrapper binary.
Adding the executable back as a direct dependency fixes that.
Happy to try and add a test for this but I need some guidance how and where to test this.
> Add executable as a direct dependency

- tut_rule/tut.bzl
After bumping to the latest version, one of our internal stripe repos was throwing the following error:
```
ERROR: /src/src/scala/com/stripe/[redacted]/BUILD:54:14: no such package 'scala/private/toolchain_deps': 
BUILD file not found in any of the following directories. 
Add a BUILD file to a directory to mark it as a package.
- /src/scala/private/toolchain_deps and referenced by '//src/scala/com/stripe/[redacted]'
```
I think this is because a recent PR (https://github.com/bazelbuild/rules_scala/commit/eabb1d28fb288fb5b15857260f87818dda5a97c8#diff-b7d365641ae2b252b2c88a798dec35dd) changed this from a `//external` reference to a local reference. Changing this to a a fully qualified reference (ie, including the workspace name) fixes the build issue.
> Fix reference to //scala/private/toolchain_deps:scala_library_classpath

- README.md
- scala/private/rule_impls.bzl
- test_rules_scala.sh
Compilation call now only passes the diagnostics file to the action if using a development build of bazel and diagnostics are enabled. 
This way, diagnostics can still be built for older versions of bazel and it gates other development builds of bazel from going down this path.
In order to fix the buildkit build, the test for the diagnostics file was also commented (since it was found that uses a development build of bazel).
Closes #1093 . At first it was thought gating the action with a single check for a development build was enough, but this proved out to be wrong.
> Add diagnostics toolchain flag to compilation action call

- .travis.yml
Echo bazel version in travis build.
Have a proof that codebase is tested against latest bazel version and what latest actually is.
> Echo bazel version in travis

- README.md
Make a note in readme that `2.0.0` is a minimal supported bazel version and that there is a PR checks against latest bazel version
Resolves https://github.com/bazelbuild/rules_scala/issues/1091
> Clarify readme on compatible bazel versions

- scala/private/rule_impls.bzl
This reverts commit 9a50e1b22d986d4c4fa292659c923960f48e1f6f.
This change was not needed. Even with previous commit rules_scala builds on downstream tests (with latest unreleased bazel version): https://buildkite.com/bazel/rules-scala-scala/builds/2265
> Revert "Disable non-functional version check in rule_impl.bsl"

- docs/testing.md
- junit/junit.bzl
- scala/private/phases/phase_collect_jars.bzl
- scala/private/phases/phase_compile.bzl
- scala/private/rules/scala_junit_test.bzl
- src/java/io/bazel/rulesscala/test_discovery/BUILD
- test/aspect/aspect.bzl
- testing/BUILD
- testing/toolchain/BUILD
- testing/toolchain/toolchain.bzl
- testing/toolchain/toolchain_deps.bzl
This PR is part of refactoring towards toolchains #940
This is a proposal for a generic testing toolchain, which can be used to configure multiple testing libraries. Some users may want to use multiple testing libraries or implementations that depend on Junit. Instead of setting up multiple toolchains (which look very similar), I think it it is more practical to have a single toolchain type, which allows to provide dependencies for mutiple testing libraries.
This PR covers toolchain itself and configuration for JUnit.
Support for ScalaTest and Specs2 will be developed as separate PRs.
> Testing toolchain and Junit deps

- scala/private/phases/phase_runfiles.bzl
- scala/private/rules/scala_test.bzl
- test/scala_test/BUILD
- test/scala_test/CustomReporter.scala
- test/shell/test_custom_reporter_class.sh
- test_rules_scala.sh
https://github.com/bazelbuild/rules_scala/issues/1111
> Added ability to configure reporter class

- WORKSPACE
- docs/testing.md
- junit/junit.bzl
- scala/private/rules/scala_test.bzl
- scala/scalatest/BUILD
- scala/support/BUILD
- specs2/specs2_junit.bzl
- src/java/io/bazel/rulesscala/scala_test/BUILD
- test/aspect/aspect.bzl
- test_version/WORKSPACE.template
- testing/BUILD
- testing/junit.bzl
- testing/scalatest.bzl
- testing/toolchain/BUILD
ScalaTest deps on toolchain, part of #940
> ScalaTest deps to toolchain

- docs/scala_proto_library.md
- scala_proto/BUILD
- scala_proto/private/scala_proto_default_repositories.bzl
- scala_proto/private/scalapb_aspect.bzl
- scala_proto/scala_proto_toolchain.bzl
- src/scala/scripts/BUILD
- test/src/main/scala/scalarules/test/extra_protobuf_generator/BUILD
Refactors scalapb toolchain to use DepsInfo providers to pass required dependencies. Part of #940
> ScalaPB deps toolchain

- scala/private/common_attributes.bzl
- scala/private/phases/phase_compile.bzl
- scala/private/rule_impls.bzl
- test/src/main/scala/scalarules/test/neverlink/A.scala
- test/src/main/scala/scalarules/test/neverlink/B.scala
- test/src/main/scala/scalarules/test/neverlink/BUILD
- test/src/main/scala/scalarules/test/neverlink/NeverlinkTest.scala
Passes neverlink attribute to JavaInfo via compile phase. Can be extracted into a separate phase after https://github.com/bazelbuild/bazel/issues/11928 is fixed.
Solves #213
> Add neverlink support

- src/scala/io/bazel/rules_scala/scrooge_support/BUILD
- src/scala/scripts/BUILD
- test/shell/test_deps.sh
- test/src/main/scala/scalarules/test/twitter_scrooge/BUILD
- thrift/thrift.bzl
- twitter_scrooge/BUILD
- twitter_scrooge/toolchain/BUILD
- twitter_scrooge/toolchain/toolchain.bzl
- twitter_scrooge/twitter_scrooge.bzl
Scrooge toolchain, part of #940 
I've grouped deps mostly mechanically, and also glued some of the code together to have less dependency groups. I think it' a perfect time to review grouping, naming and if needed refactor them.
> Add scrooge toolchain

- test/shell/test_runner.sh
- test_version.sh
I wanna add a way for specifying specific timeout per test. Currently there's a global timeout of 60 minutes **per test** while in travis the timeout it for each test **suite** is 50 minutes. 
When travis terminates the run in the middle of test run, we can't even see the logs of the timing out test. Using this mechanism we can terminate the test ourselves and see the output.
I looked at [travis job](https://travis-ci.org/github/bazelbuild/rules_scala/jobs/737970813) from [this PR](https://github.com/bazelbuild/rules_scala/pull/1118)
~I'm checking it now with super low timeout in purpose - I wanna see how it looks like.~ - see first commit travis to see example for failure on timeout..
PR is ready to merge AFAIC.
FYI: @liucijus
> [CI-shell-tests] Support granular test timeout

- WORKSPACE
- examples/testing/scalatest_repositories/WORKSPACE
- examples/testing/scalatest_repositories/example/BUILD
- examples/testing/scalatest_repositories/example/ExampleTest.scala
- test/shell/test_examples.sh
- test_rules_scala.sh
- test_version/WORKSPACE.template
- testing/scalatest.bzl
Call correct function to register toolchain
> Fix toolchain registration call for ScalaTest

- .travis.yml
- docs/testing.md
- examples/testing/specs2_junit_repositories/WORKSPACE
- examples/testing/specs2_junit_repositories/example/BUILD
- examples/testing/specs2_junit_repositories/example/Specs2ExampleTest.scala
- specs2/BUILD
- test/shell/test_examples.sh
- test_examples.sh
- test_rules_scala.sh
- test_version/WORKSPACE.template
- testing/BUILD
- testing/specs2.bzl
- testing/specs2_junit.bzl
- testing/toolchain/BUILD
Specs2 toolchain, part of #940
> Specs2 toolchain

- WORKSPACE
Bazel and bazel-toolchains need to be at the same version
> Upgrade bazel-toolchains to match bazel version 3.5.0

- README.md
- WORKSPACE
- examples/testing/scalatest_repositories/WORKSPACE
- examples/testing/specs2_junit_repositories/WORKSPACE
- scala/private/macros/scala_repositories.bzl
- test_version/WORKSPACE.template
- third_party/test/proto/WORKSPACE
Based on change in rules_proto
https://github.com/bazelbuild/rules_proto/pull/36
`rules_proto_dependencies()` declares a `@com_google_protobuf//:protoc`
which points to released `protoc` binary.
The tricks is to load that before `scala_repositories()` which has
conditional load for `@com_google_protobuf`
Avoid compiling `protoc` during `bazel build`.
> Use released protoc binaries

- README.md
Updates README to add Gemini as a user of rules_scala.
Just trying to be transparent about our usage in hopes it can help others make the choice to also use `rules_scala`
> Add Gemini as rules_scala user

- README.md
The url on the readme was accidentally changed to a fork on a recent commit; change it back to the main repo.
To point to the correct repo :)
> Fix url on readme

- README.md
Mentions 2.13 as supported in README
> Add Scala 2.13 to docs as supported version

- scala/private/phases/phase_coverage_runfiles.bzl
- test/coverage/expected-coverage.dat
- test/shell/test_coverage.sh
- test/shell/test_misc.sh
- test_rules_scala.sh
Support `--instrument_test_targets` (default value is False) flag. Solves #1042 and partially addresses instability with rules_scala coverage testing when test libraries change (by excluding test target coverage).
> Support --instrument_test_targets flag in coverage

- .bazelci/presubmit.yml
Seems like we're using Google's buildkite config [legacy format](https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#legacy-format). 
This is my attempt to move to the new format (also to learn this config so maybe I can tackle #1157 in the future)
> [buildkite] Using new presubmit format

- docs/toolchain_development.md
- jmh/toolchain/toolchain.bzl
- scala/plusone.bzl
- scala/private/coverage_replacements_provider.bzl
- scala/private/rules/scala_binary.bzl
- scala/private/rules/scala_junit_test.bzl
- scala/private/rules/scala_library.bzl
- scala/private/rules/scala_repl.bzl
- scala/private/rules/scala_test.bzl
- scala/private/toolchain_deps/toolchain_dep_rules.bzl
- scala/scalafmt/toolchain/toolchain.bzl
- testing/toolchain/toolchain_deps.bzl
- tut_rule/toolchain/toolchain.bzl
- twitter_scrooge/toolchain/toolchain.bzl
- twitter_scrooge/twitter_scrooge.bzl
Required to prevent host and target dependecies mixing for deps that come from toolchains. Example when it becomes a problem #1160
> Use incompatible_use_toolchain_transition in all rules

- scala/private/macros/scala_repositories.bzl
scala_repositories should use the passed parameter value instead of providing _default_maven_server_urls as a value passed downstream.
scala_repositories does not currently work with custom maven_servers attribute as the implementation uses the default anyhow.
This blocks rules_scala if the default maven repositories are unavailable (e.g. in restricted company networks).
> Fix maven_servers parameter passing in scala_repositories

- scala/private/phases/phase_write_executable.bzl
Fixes #1169 
I was thinking of just adding coverage support for scala_binary, but there are more issues which require debugging. For now, let's revert the change which caused breakage.
> Rollback usage of `use_jacoco` attribute

- docs/testing.md
- manual_test/scala_test_jacocorunner/BUILD
- manual_test/scala_test_jacocorunner/EmptyTest.scala
- scala/private/phases/phase_coverage_runfiles.bzl
- scala/private/phases/phase_write_executable.bzl
- scala/private/rules/scala_test.bzl
- scala/scala_toolchain.bzl
- test/shell/test_scala_jacocorunner.sh
- test_expect_failure/scala_test_jacocorunner/BUILD
- test_expect_failure/scala_test_jacocorunner/EmptyTest.scala
- test_rules_scala.sh
Use toolchains to provide jacocorunner for scala_test.
This is to enable overriding jacocorunner.
Following the discussion in #1166 and #1163, this is the latest proposal to solve #1056.
> Use toolchain for providing jacocorunner

- docs/coverage.md
- manual_test/coverage_local_jacocorunner/BUILD
- manual_test/coverage_local_jacocorunner/expected-coverage.dat
- manual_test/coverage_local_jacocorunner/test.sh
- scripts/build_jacocorunner/0001-Build-Jacoco-for-Bazel.patch
- scripts/build_jacocorunner/0002-Build-Jacoco-behind-proxy.patch
- scripts/build_jacocorunner/build_jacocorunner.sh
This is a script that can be used manually to generate custom jacocorunner, that then can be used to
e.g. fix Scala 2.12 code coverage for lambdas.
Takes Jacoco, builds and and then use it to build jacocorunner in Bazel repo.
Motivated by the idea to add the generated jacocorunner to rules_scala.
More info at: https://github.com/bazelbuild/bazel/issues/11674#issuecomment-748422907.
> Script to generate custom jacocorunner

- README.md
Updated to the latest master version because docs version had issues with 2.11 error reporting
> Update docs to the latest master version

- README.md
Must be external label to be used outside the rules_scala repo
> Fix docs: use external label for minimal deps toolchain

- src/java/io/bazel/rulesscala/scalac/ReportableMainClass.java
- src/java/io/bazel/rulesscala/scalac/ScalacWorker.java
- test_version.sh
Closes #1161 . Changed how the reporter is obtained from the `MainClass`, since the call to `getDeclaredField` is obtaining the wrong reporter for scala 2.11.
Fixes problems regarding building for scala 2.11, where the build was exiting without flagging errors, whenever the `DiagnosticsReporter` was used
> Fix error reporting on 2.11

- scala/private/rule_impls.bzl
- src/java/io/bazel/rulesscala/jar/JarCreator.java
- src/java/io/bazel/rulesscala/scalac/ScalacWorker.java
- test/src/main/scala/scalarules/test/stamping/BUILD
- test/src/main/scala/scalarules/test/stamping/ClassFromLibrary.scala
- test/src/main/scala/scalarules/test/stamping/ClassFromMacroLibrary.scala
- test/src/main/scala/scalarules/test/stamping/JarStampingTest.scala
ScalacWorker stamps jars with target label
> Stamp scalac jars

- test/shell/test_scala_library.sh
- test_expect_failure/missing_direct_deps/internal_deps/BUILD
- test_expect_failure/missing_direct_deps/internal_deps/custom-jvm-rule.bzl
- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/DependencyAnalyzer.scala
This should address problems like #553 if dependency comes with a stamped jar (for example _rules_jvm_external_ can be used with a setting to stamp third party jars). This is an opportunistic implementation - ideally the whole dep validation mechanism should be refactored to have a better API around "Unknow label", but that's much bigger effort for the future.
> Attempt to load target label from jar for unknown labels

- specs2/BUILD
- specs2/specs2.bzl
- specs2/specs2_junit.bzl
- test/aspect/aspect.bzl
- testing/BUILD
Removes binds from specs2 test rules. Users should use testing toolchain deps to customize specs2 dependencies.
> Remove specs2 binds

- .bazelci/presubmit.yml
- .travis.yml
- moves version tests from Travis to Buildkite
- gives names to Buildkite tasks
- adds ubuntu2004
- add config validation
> Move version tests to buildkite

- tools/BUILD
Excludes new linting warning introduced with #1194 which broke master build.
> Update linter settings after buildifier update

- test/shell/test_helper.sh
- test/shell/test_scalac_jvm_flags.sh
- test_expect_failure/compilers_javac_opts/BUILD
- test_expect_failure/compilers_jvm_flags/BUILD
Add missing `exit 1` to make test actually fail.
Had to remove `jvm_opts = ["-Xbootclasspath/p:$(location
@bazel_tools//third_party/java/jdk/langtools:javac_jar)"],`
because test fails for wrong reason `-Xbootclasspath/p is no longer a
supported option.`
Tried to write a test using `action_should_fail_with_message` and couldn't make it fail with a wrong error message.
> Fix action_should_fail_with_message sh helper

- src/scala/scripts/ScalaPBWorker.scala
- test/proto/custom_generator/BUILD.bazel
- test/proto/custom_generator/FailingGenerator.scala
- test/shell/test_scala_proto_library.sh
When generator fails with exception display cause stacktrace in bazel output.
Before
```
Exit with code 1
java.lang.RuntimeException: Exit with code 1
at scala.sys.package$.error(package.scala:30)
at scripts.ScalaPBWorker$.work(ScalaPBWorker.scala:56)
at io.bazel.rulesscala.worker.Worker.persistentWorkerMain(Worker.java:92)
at io.bazel.rulesscala.worker.Worker.workerMain(Worker.java:46)
at scripts.ScalaPBWorker$.main(ScalaPBWorker.scala:21)
at scripts.ScalaPBWorker.main(ScalaPBWorker.scala)
```
After
```
java.lang.RuntimeException: expected generator failure
at test.proto.custom_generator.FailingGenerator$.run(FailingGenerator.scala:5)
at protocbridge.frontend.PluginFrontend$.$anonfun$runWithBytes$1(PluginFrontend.scala:52)
at scala.util.Try$.apply(Try.scala:213)
at …
```
> Report exceptions from protoc generator

- third_party/repositories/scala_2_11.bzl
The hash and version for scalap for Scala 2.11.12 conflicted.
Set up both version and hash for scalap to be for Scala 2.11.12 (as other Scala components are set for Scala 2.11).
The sha256 is set for scalap:2.11.12, but the version set was 2.11.10 which
caused a hash conflict.
$ sha256sum scalap-2.11.12.jar
a6dd7203ce4af9d6185023d5dba9993eb8e80584ff4b1f6dec574a2aba4cd2b7  scalap-2.11.12.jar
$ sha256sum scalap-2.11.10.jar
3f6f352fce91c33055398a7081e35e5091fd5e095130905633e72f52124c1d27  scalap-2.11.10.jar
> Fixing scalap version for Scala 2.11.12

- docs/scala_import.md
- scala/scala_import.bzl
- scala/settings/BUILD
- scala/settings/stamp_settings.bzl
- test/src/main/scala/scalarules/test/scala_import/BUILD
- test/src/main/scala/scalarules/test/scala_import/ScalaImportExposesJarsTest.scala
- test/src/main/scala/scalarules/test/scala_import/scala_import_stamp_test.bzl
Another to address broken signed jars after stamping with Target-Label their manifests. 
- stamps only compile jars
- original jars are passed for runtime/full compile jars
- adds setting to disable stamping in case there are issues
> Scala Import stamping

- scala/private/rule_impls.bzl
Closes #1211 . Removes branching off to the `diagnostics_file` proposed feature.
This is being removed as `diagnostics_file`  is not yet featured in the bazel upstream and CI now seems to use a development version of bazel.
> Remove test for development version of bazel for the diagnostics file.

- scala/private/common_attributes.bzl
Looks like `cfg=host` is deprecated and needs to be changed to `cfg=exec`
> Change host_javabase cfg from host to exec

- .bazelci/presubmit.yml
- test_coverage.sh
- test_rules_scala.sh
Extracts version specific coverage tests into separate tasks with fixed bazel version to #1218
> Move coverage tests under a separate jobs with fixed bazel version

- WORKSPACE
We load our own skylib before buildifier setup
> Remove redundant call to buildifier setup

- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinder.scala
- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/DependencyAnalyzer.scala
- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/DependencyAnalyzerSettings.scala
- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/HighLevelCrawlUsedJarFinder.scala
- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/OptionsParser.scala
- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/Reporter.scala
- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/Reporter213.scala
- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/ScalaVersion.scala
- third_party/dependency_analyzer/src/main/resources/scalac-plugin.xml
- third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinderTest.scala
- third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/ScalaVersionTest.scala
- third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/ScalacDependencyTest.scala
- third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/StrictDepsTest.scala
- third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/UnusedDependencyCheckerTest.scala
- third_party/utils/src/test/io/bazel/rulesscala/utils/JavaCompileUtil.scala
- third_party/utils/src/test/io/bazel/rulesscala/utils/TestUtil.scala
Normalizing package names under `third_party`. I guess they were generated by some tool automatically.
> Clean up package names related to dependencyanalyzer

- scala_proto/private/scalapb_aspect.bzl
- scala_proto/scala_proto.bzl
- test/BUILD
- test/proto/BUILD
- test_version/version_specific_tests_dir/BUILD
- test_version/version_specific_tests_dir/proto/BUILD
It made sense to accept `JavaInfo` as a dep in `scala_proto_library` when `with_java` flag was supported. But this flags is no longer supported since implementation moved to aspects. 
**Note:** this might be a breaking change if anyone is passing `JavaInfo` to `scala_proto_library`
> Require ProtoInfo for deps in scala_proto_library

- test_expect_failure/compilers_javac_opts/BUILD
Attempt to fix https://github.com/bazelbuild/rules_scala/issues/1224
Test `java_toolchain_javacopts_are_used` fails because of failing `default_java_toolchain` declaration.
Root cause is that `javac` parameter was removed from `java_toolchain`.
Test `java_toolchain_javacopts_are_used` only cares about `javacopts` flag on a toolchain.
So this PR removes `bootclasspath` and `javac` from `default_java_toolchain` and these values will be taken from [DEFAULT_TOOLCHAIN_CONFIGURATION](https://github.com/bazelbuild/bazel/blob/667ae2adc793d376267c85e81ca6be600a4f2fbd/tools/jdk/default_java_toolchain.bzl#L80)/[_BASE_TOOLCHAIN_CONFIGURATION](https://github.com/bazelbuild/bazel/blob/667ae2adc793d376267c85e81ca6be600a4f2fbd/tools/jdk/default_java_toolchain.bzl#L55)
> Remove to-be-removed flags from default_java_toolchain

- scala/private/rule_impls.bzl
- src/java/io/bazel/rulesscala/scalac/CompileOptions.java
Use ctx.actions.args() to pass parameters to persistent worker.
As per recommendations in https://docs.bazel.build/versions/master/skylark/performance.html#use-ctxactionsargs-for-command-lines this should reduce memory consumption at analysis phase by:
- deferring expansion of depsets
- avoiding concatenation of list
- avoiding construction of large strings for args file
> Use ctx.actions.args() in compile_scala

- third_party/repositories/scala_2_13.bzl
Updated scrooge-generator, scrooge-core, util-core and util-logging to latest available version 21.2.0 for scala 2.13.
This change should have been part of the next commit https://github.com/bazelbuild/rules_scala/pull/1223
Keeping third party dependencies up-to-date is healthy for the project.
> Update  scrooge and util libs to version 21.2.0 for scala 2.13

- README.md
Adds [Domino Data Lab](https://www.dominodatalab.com/) as an adopter of `rules_scala`.
We're currently using `rules_scala` to build and test code in our monorepo. Hopefully our adoption encourages others to also use `rules_scala`.
> Add Domino Data Lab as a rules_scala adopter

- test/shell/test_deps.sh
- test/shell/test_strict_deps.sh
- test_expect_failure/missing_direct_deps/scala_proto_deps/BUILD
- test_expect_failure/missing_direct_deps/scala_proto_deps/UseScalaProtoIndirectly.scala
- test_expect_failure/missing_direct_deps/scala_proto_deps/UseTestMessage.java
- test_expect_failure/missing_direct_deps/scala_proto_deps/some.proto
- test_rules_scala.sh
Adding a test which demonstrates an incorrect behavior of `scala_proto_library` stamping #1234.
> scala_proto_library test stamping test

- scala_config.bzl
Stop setting BAZEL_VERSION
It appears to be no longer used, but may pollute cache keys.
> Stop setting BAZEL_VERSION

- third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinderTest.scala
I left some unneeded imports from the same package, which cause warning noise in the build log. This PR removes them.
> Remove imports which cause warnings

- scala_config.bzl
- test/shell/test_scala_config.sh
- test_rules_scala.sh
Specify scala version that is written by `scala_config` rule in command line `--repo_env=SCALA_VERSION_OVERRIDE=x.y.z`. 
Allows to build a project with different scala versions without need for sed workspace.
> Configure major scala version via repo_env

- .bazelci/presubmit.yml
In travis we used to have a non-failing test_rules_scala that checked if tests passs when working with latest bazel version
I wish to restore it.
Please kindly look only at the final changes and not by commits as I prefer to squash and merge it if it's accepted.
If latest version fails - it would add annotation like this:
(but won't fail the build)
Else - no annotation would be added.
I see that we're failing with `test_rules_scala.sh`, maybe we simply want to do the same thing with `bazel test //test/...` ?
> Restored check with latest version

- docs/scala_proto_library.md
Use consistent toolchain reference across the documentation.
> docs - use external deps toolchain type

- scala/private/rules/scala_test.bzl
Pass along tags passed to `scala_test_suite` to the test suite target.
This is useful to set a suite to `manual` for example.
> Pass along tags in scala_test_suite

- AUTHORS
- CODEOWNERS
- CONTRIBUTORS
- Governance.md
Over the past few months @simuons has become a very important part of rules_scala d2d (helping on issues, reviewing PRs, and authoring PRs).  
Seeing as he’s been fulfilling the maintainer roles without being named as one I feel it is only natural to add him as an official maintainer.   
I want to take this opportunity to re-iterate that we are very interested in adding more maintainers (individuals and companies) to make sure rules_scala remains a thriving project and an important part of the bazel ecosystem.   
This close and engaging work by him and @liucijus has gladly brought me to the place where I can leave rules_scala stewardship in their trusted hands and continue to new adventures.  
I want to thank you for your help over this time, I’m very excited about where rules_scala is …
> rules_scala stewardship update

- examples/testing/multi_frameworks_toolchain/BUILD
- scala/private/phases/phase_coverage.bzl
- src/java/io/bazel/rulesscala/coverage/instrumenter/JacocoInstrumenter.java
- test/coverage_filename_encoding/A1.scala
- test/coverage_filename_encoding/BUILD.bazel
- test/coverage_filename_encoding/Test.scala
- test/coverage_filename_encoding/expected-coverage.dat
- test/coverage_specs2_with_junit/BUILD
- test/coverage_specs2_with_junit/E1.scala
- test/coverage_specs2_with_junit/TestWithSpecs2WithJUnit.scala
- test/coverage_specs2_with_junit/expected-coverage.dat
- test/shell/test_coverage_equals_in_target.sh
- test_coverage.sh
Do not use  '=' as file names separator when providing them to JacocoInstrumenter .
Currently files provided as arguments for JacocoInstrumenter are separated by '='. That leads to problems if files or target names contain '=' in names. 
Currently `bazel coverage` cannot be run on targets where names include '=' sign.
> Add file name encoding for JacocoIntrumenter

- src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala
While building local build that had dependency on `//src/scala/io/bazel/rules_scala/jmh_support:benchmark_generator_lib` I noticed the warnings:
```
external/io_bazel_rules_scala/src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala:5: error: Unused import
import scala.annotation.tailrec
^
external/io_bazel_rules_scala/src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala:10: error: Unused import
import org.openjdk.jmh.runner.{Runner, RunnerException}
^
external/io_bazel_rules_scala/src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala:10: error: Unused import
import org.openjdk.jmh.runner.{Runner, RunnerException}
^
external/io_bazel_rules_scala/src/scala/io/bazel/rules_scala/jmh_support/BenchmarkGenerator.scala:11: error: Unused import
import …
```
> [BenchmarkGenerator] Fixing scalac warnings

- docs/scala_proto_library.md
scala_proto_repositories does not accept scala_version
Clean up docs
> Removes scala_version

- src/java/io/bazel/rulesscala/scalac/ProtoReporter.java
Deletes a bunch of dead code.
It’s not used anywhere.
> Delete dead code from ProtoReporter

- README.md
- WORKSPACE
- examples/testing/multi_frameworks_toolchain/WORKSPACE
- examples/testing/scalatest_repositories/WORKSPACE
- examples/testing/specs2_junit_repositories/WORKSPACE
- scala/private/macros/scala_repositories.bzl
- third_party/test/proto/WORKSPACE
- Reorganize how `rules_proto` are loaded
- Update too old `@com_google_protobuf//:protoc` version in scala repositories
- Update example/test/WORKSPACE/README code
> Load @com_google_protobuf//:protoc via rules_proto

- docs/dependency-tracking.md
* "Dependecy" -> "Dependency"
* "exludes" -> "excludes"
Fix typos in dependency-tracking README
Easier to read and more professional-looking
> Fix typos in dependency-tracking README

- jmh/jmh.bzl
- test/jmh/BUILD
Adding 2 options to JMH rules:
- `testonly` to allow marking JMH as `testonly` and consuming `testonly` dependencies, which allows re-using various test-kits and test helpers.
- `runtime_deps`, which might (and is in our case) required for benchmark dependencies
Both are optional, so should be fully backwards-compatible.
We have many test-kits and test helpers marked with `testonly`, because we're using them for testing mainly and `testonly` protects us from getting them into production. They are very useful for benchmarks as well, which is why we need this flag.
> Extra jmh options: testonly, runtime_deps

- src/java/io/bazel/rulesscala/coverage/instrumenter/JacocoInstrumenter.java
- test/coverage_scalatest_resources/consumer/BUILD.bazel
- test/coverage_scalatest_resources/consumer/src/main/scala/com/example/consumer/Consumer.scala
- test/coverage_scalatest_resources/consumer/src/test/scala/com/example/consumer/ConsumerSpec.scala
- test/coverage_scalatest_resources/expected-coverage.dat
- test/coverage_scalatest_resources/resource/BUILD.bazel
- test/coverage_scalatest_resources/resource/src/main/resources/com/example/resource/example.sql
- test/coverage_scalatest_resources/resource/src/main/scala/com/example/resource/Util.scala
- test/shell/test_coverage_scalatest_resources.sh
- test_coverage.sh
Added directories to the `packagename-offline.jar` artifacts that get created by [JaCoCoInstrumenter.java](src/java/io/bazel/rulesscala/coverage/instrumenter/JacocoInstrumenter.java).
Fixes #1280.  This fix allows calls for `ClassLoader.getResources("path/in/jar")` to succeed.  Any code that tries to fetch resources at a given path will get no results in `bazel coverage`, even if `bazel test` allows the path to be explored properly.
> Fix missing directories in JaCoCo instrumented jars

- src/java/io/bazel/rulesscala/test_discovery/ArchiveEntries.scala
- src/java/io/bazel/rulesscala/test_discovery/BUILD
- src/java/io/bazel/rulesscala/test_discovery/DiscoveredTestSuite.scala
- test/src/main/scala/scalarules/test/junit/test_discovery/ArchiveEntriesTest.scala
- test/src/main/scala/scalarules/test/junit/test_discovery/BUILD
I'm trying to make Intellij's [Fast Build](https://ij.bazel.build/docs/fast-builds.html) work with Specs2 tests, but currently JUnit test discovery only knows how to scan jars and fails id directories are passed. For fast build to work we need to prepend directories to the classpath. 
This PR adds support for listing class files from directories.
> Add directory scanning support to JUnit test discovery

- src/java/io/bazel/rulesscala/specs2/Specs2RunnerBuilder.scala
Add flattenLeft function in Specs2RunnerBuilder to support newer specs2 versions.
`flattenLeft` was removed from Trees trait with ([fix: #892 always use flattenLeft for trees (including when calling size)
](https://github.com/etorreborre/specs2/commit/ba47c8f37c18aa27190a7510a00984ae9696460d#diff-162da17eeac842c31a79882aa0fc7e5536bbf91f9ee0a9890498d5f0481b84dbL70) commit.
> Add flattenLeft function in Specs2RunnerBuilder to support newer specs2 versions

- scala/private/phases/phase_compile.bzl
This updates call to `java_common.pack_sources` according to https://github.com/bazelbuild/bazel/issues/12373
Support latest Bazel version.
> Replace output_jar with output_sources_jar in java_common.pack_sources

- src/java/io/bazel/rulesscala/exe/LauncherFileWriter.java
Do not prefix the workspace name to an absolute `javaBinPath` (or a `javaBinPath` under `external/`) in the Windows launcher.
Adding the prefix in these cases would lead to an invalid path.
This is to avoid errors of the following form when configuring a `--javabase` with an absolute `java_home` path on Windows.
```
LAUNCHER ERROR: Rlocation failed on my_workspace/C:/myjdk/bin/java.exe, path doesn't exist in MANIFEST file
```
The relevant parts in Bazel's Java launcher are [here](https://github.com/bazelbuild/bazel/blob/c4975efdd7ede7b46637bf353209d9ac371181a5/src/tools/launcher/java_launcher.cc#L304-L305) and [here](https://github.com/bazelbuild/bazel/blob/c4975efdd7ede7b46637bf353209d9ac371181a5/src/tools/launcher/launcher.cc#L149-L160).
> Do not prefix workspace name on absolute java path in the Windows launcher

- src/java/io/bazel/rulesscala/scalac/ScalacWorker.java
- test/scalac/srcjars/BUILD.bazel
- test/scalac/srcjars/DuplicatesTest.scala
- test/scalac/srcjars/duplicate/BUILD.bazel
- test/scalac/srcjars/setup.bzl
This PR follows similar pattern for temp files as java_library does when it compiles sources.
For each target create a working directory _target-bazel-out_/_scalac/_target-name_ containing:
* classes - this is where compiled scala code and resources goes before packaging into jar
* sources - this is where srcjars are extracted and each one has it's own directory named as srcjar file
eg. _target-bazel-out_/_scalac/_target-name_/sources/_srcjar-file-name_
Working directory is deleted if it exists and new one is created.
Solves https://github.com/bazelbuild/rules_scala/issues/1311
Thought we don't know when and why scalac embeds source file paths into class files.
Also fixes minor annoyance when tmp folders keep accumulating when srcjars are used.
This is not a big issue but sometimes makes …
> Use stable file paths in scalac actions

- src/java/io/bazel/rulesscala/scalac/ScalacWorker.java
Instead of using full path of srcjar as a destination directory
prepend index to srcjar file name.
Index corresponds to order in which file was passed to scalac.
Also considered computing hash of full path, but full path
contains platform specific labels ie darwin, linux etc
so not sure that would be a good approach.
Resolves https://github.com/bazelbuild/rules_scala/issues/1322
> Fix long file names in scalac action when handling srcjars

- README.md
Fixes invalid link to scala toolchains docs and changes another url to relative
> Fix scala toolchains link in README

- scala/private/phases/phase_compile.bzl
Disable ijar build on non-scala2 builds. 
Full .class is required for scalac on scala3 to compile.
This is a prerequisite for enabling scala3 support.
> feat(phase-compile): disable ijar for scala3

- test/coverage_filename_encoding/Test.scala
- test/coverage_specs2_with_junit/TestWithSpecs2WithJUnit.scala
- test/shell/test_scala_specs2.sh
- test/src/main/scala/scalarules/test/junit/specs2/Specs2Tests.scala
- test/src/main/scala/scalarules/test/location_expansion/LocationExpansionTest.scala
- test/src/main/scala/scalarules/test/resources/ScalaLibOnlyResourcesFilegroupTest.scala
- test/src/main/scala/scalarules/test/resources/ScalaLibOnlyResourcesTest.scala
- test/src/main/scala/scalarules/test/resources/ScalaLibResourcesFromExternalDepTest.scala
- test/src/main/scala/scalarules/test/resources/strip/ResourceStripPrefixTest.scala
- test/src/main/scala/scalarules/test/scala_import/ScalaImportExposesFileJarsTest.scala
- test/src/main/scala/scalarules/test/scala_import/ScalaImportExposesJarsTest.scala
- test/src/main/scala/scalarules/test/scala_import/ScalaImportPropagatesRuntimeDepsTest.scala
- test/src/main/scala/scalarules/test/scala_import/nl/ScalaImportNeverLinkTest.scala
- test_expect_failure/scala_import/ScalaImportPropagatesCompileDepsTest.scala
- test_expect_failure/scala_junit_test/specs2/SuiteWithOneFailingTest.scala
- test_version/version_specific_tests_dir/src/main/scala/scalarules/test/junit/specs2/Specs2Tests.scala
Removed usage of `should` and `new Scope` from specs2 tests.
`should` clashes with an expectation in Specs2 v5.
`Scope` is [no longer available](https://medium.com/@etorreborre_99063/specs2-the-next-10-years-8c15e85cb9fe) in Specs2 v5.
`should` can be used in specs2 v5, however in test classes must extend `ExtendedBlockDsl`, which is not available in v4. Making it cross-compatible for v4 and v5 would require to write a custom 'should' in the rules_scala repo, which is not great.
I understand it is not great in terms of spec formulation, but I do not see a cleaner way for now.
Prerequisite for scala3 support. Scala3 build requires specs2 v5.
> feat(specs2): remove scope and shoulds

- src/java/io/bazel/rulesscala/specs2/Specs2RunnerBuilder.scala
- src/java/io/bazel/rulesscala/test_discovery/DiscoveredTestSuite.scala
- src/java/io/bazel/rulesscala/test_discovery/FilteredRunnerBuilder.scala
Modification of the specs2 test runner suite to support scala3.
This includes:
- Copying `bottomUp` implementation from specs2 v4 package, as it no longer exists on v5
- Minor refactoring (thanks to @liucijus for doing this part)
A prerequisite for scala3 support
> feat(specs2): modify runner suite to support scala3

- scala/private/rules/scala_doc.bzl
- scala/scala.bzl
Add support to build scaladocs only for the provided targets.
This enables building scaladocs without building docs all transitive dependencies (i.e 3rdparty dependencies and other dependent targets). The aim is to provide a `transitive` arg that can be set to `true`/`false` (defaults to `true`) which decides whether to build scaladocs for transitive dependencies or not.
We are using bazel in a big mono-repo and building scaladocs for some of our targets take a long time because of the large dependency chain and sometimes long list of 3rdparty libraries. We only want to build scaladocs for the targets we specify in the `deps` field of the `scala_doc` rule. This change adds support for that.
> scala_doc: Add support for building docs without transitive dependencies

- third_party/repositories/repositories.bzl
- third_party/repositories/scala_3_1.bzl
Adding support for Scala 3 requires many changes, I'm splitting them into smaller PRs to bring minimal Scala 3 support faster into Rules Scala.
This is basically a copy of Scala 2.13 repository with core Scala deps updated. They were tested in https://github.com/liucijus/rules_scala/tree/scala3-in-progress branch.
> Add initial repositories for Scala 3.1

- third_party/repositories/scala_2_13.bzl
Discovered invalid checksum for `org_typelevel__cats_core` while testing Scala 2.13 locally.
Since we can pass Scala version on the command line, I think we need a follow up improvement on how version based tests run on CI.
Also it's probably good time to update default version to 2.13.
> Fix org_typelevel__cats_core checksum for 2.13

- scala/private/phases/phase_scalafmt.bzl
- scala/scalafmt/private/format-test.template.sh
Relates to https://github.com/bazelbuild/rules_scala/issues/994
With these changes, I can use a macro to place a wrapping `sh_test`
target around this script, and change the phase ordering to put
`phase_scalafmt` before the `runfiles` phase, and suddenly it works
as intended!
NB: If this change is acceptable to folks, then it might be worth
changing the default phase placement for `ext_scalafmt` to place
it before `runfiles` by default.
Example use:
In custom bzl file, I have:
```
_enable_format_targets_and_tests_by_default = True
_ext_scalafmt = dicts.add(
_base_ext_scalafmt,
{"attrs": dicts.add(
_base_ext_scalafmt["attrs"],
{"format": attr.bool(
default = _enable_format_targets_and_tests_by_default,
doc = "Enable the check-format and auto-format synthetic run targets (foo.format-test …
```
> Tweaks to `scalafmt` rules/script to support `bazel test` wrappers

- scala/scalafmt/BUILD
- scala/scalafmt/phase_scalafmt_ext.bzl
See comments in change for detailed motivation.  TL;DR: Allow the capture of formatted sources, original sources, and manifest to be passed via `runfiles` phase to downstream dependencies, such as a wrapping `sh_test`, allowing it to
actually access those during a `bazel test` invocation and fail a build if the format is incorrect.
> update default `scalafmt` phase order; place before `runfiles`

- .bazelci/presubmit.yml
Fix xmlint related failures in latest and Bazel 5 jobs
> Fix Bazel latest and 5.0.0 Buildkite jobs

- .bazelci/presubmit.yml
We have a separate build for Bazel 5. This updates optional build to track compatibility status with Bazel head.
> Update latest Bazel build to latest green head build

- WORKSPACE
- scala/private/macros/scala_repositories.bzl
- scala/scalatest/BUILD
- scalatest/scalatest.bzl
- test_version/WORKSPACE.template
- testing/scalatest.bzl
- third_party/repositories/scala_2_13.bzl
Tech debt clean up. Moving loading of ScalaTest dependencies from `scala_repositories` to `scalatest_repositories`, which was an empty call to ease such migration.
Codebases, which get broken after this change, should call `scalatest_repositories() ` in their WORKSPACEs:
```
load("@io_bazel_rules_scala//testing:scalatest.bzl", "scalatest_repositories", "scalatest_toolchain")
scalatest_repositories() # Loads ScalaTest dependencies
scalatest_toolchain()
```
> Move ScalaTest deps to its own repository macro

- test_version.sh
- test_version/WORKSPACE.template
- test_version/version_specific_tests_dir/scrooge_repositories.bzl
- pass Scala version as a command line flag
- remove uses of artifact overrides in twitter scrooge setup
- move scrooge artifacts versions to bzl file for easier setup
- pass diagnostic toolchains as command line flags
Motivation: remove tech debt to have less work for upcoming Scala 3 related changes
> Clean up versions tests

- scala/private/phases/phase_compile.bzl
- scala/private/phases/phase_scalafmt.bzl
- thrift/thrift.bzl
Actions might look like completed successfully even though one of the commands fail.
This might cause remote-cache poisoning.
> set -e for ctx.actions.run_shell commands

- examples/testing/multi_frameworks_toolchain/BUILD
- examples/testing/scalatest_repositories/example/ExampleTest.scala
- scalatest/scalatest.bzl
- test_version/version_specific_tests_dir/HelloLibTest.scala
- testing/BUILD
- third_party/repositories/scala_2_11.bzl
- third_party/repositories/scala_2_12.bzl
- third_party/repositories/scala_2_13.bzl
- third_party/repositories/scala_3_1.bzl
Updated `scalatest` to `3.2.9`.
Updated version introduces some breaking changes by [removing many of deprecated names](https://www.scalatest.org/release_notes/3.2.0#expiredDeprecations). These were used in some tests, e.g. (`FlatSpec`, `MustMatchers`).
Current version (`3.1.2`) does not support Scala 3, `3.2.9` is the lowest version [that does](https://index.scala-lang.org/artifacts/scalatest/scalatest). This PR updates updates to `3.2.9` across all Scala versions for sake of consistency.
> Scalatest version bump to 3.2.9

- scala/scala_import.bzl
- test/src/main/scala/scalarules/test/scala_import/scala_import_stamp_test.bzl
Let's see if we can use ijar via java_common.stamp_jar
Fixes #1371
> Use java_common.stamp_jar to stamp scala_import jar

- scala/private/phases/phase_coverage.bzl
- test/shell/test_coverage_scalatest_resources.sh
Previously, all Scala code would be instrumented for coverage during a
bazel coverage run instead of only those source files that belong to
targets matching the instrumentation filter.
Fixes https://github.com/bazelbuild/bazel/issues/15167.
> Take --instrumentation_filter into account in coverage phase

- scala/private/phases/phase_test_environment.bzl
- scala/private/phases/phase_write_executable.bzl
- scala/private/phases/phases.bzl
- scala/private/rules/scala_junit_test.bzl
- test/BUILD
- test/src/main/scala/scalarules/test/junit/JunitNoTestEnvironmentTest.scala
- test/src/main/scala/scalarules/test/junit/JunitSetTestEnvironmentTest.scala
Add the equivalent of `java_test`'s `env` attr to `scala_junit_tests` via `TestEnvironment` provider.
Allows targets to set their own environment variables during `bazel test` runs.
https://bazel.build/reference/be/common-definitions#test.env
We would like to test with environment variables different from the ones defaulted to by a `bazel test` invocation, on a target-specified basis. This also brings our test rules further in line with the functionality offered by native test rules.
> Allow `scala_junit_tests` targets to specify test environment variables

- src/java/io/bazel/rulesscala/worker/Worker.java
- src/java/io/bazel/rulesscala/worker/WorkerTest.java
`Worker`s should parse argsfiles/flagfiles regardless of being persistent or ephemeral.  
This doesn't change the behavior of only allowing argsfiles when called with a single argument.
Our functionality will be more in line with Bazel's `JavaBuilder`.  
This is also helpful for persistent workers outside of Bazel itself (e.g. on remote executors).  
Instead of expanding argsfiles, remote executors can pass in the argsfile as if it were an ephemeral invocation.
> Consistent argsfile parsing

- scala/private/common_attributes.bzl
- scala/private/phases/phase_compile.bzl
- scala/private/rule_impls.bzl
- scala/scala_import.bzl
- scala_proto/private/scala_proto_aspect.bzl
- test/BUILD
- test/CheckBytecodeMajorVersionTest.scala
- test/src/main/resources/java_sources/BUILD
- test/src/main/resources/java_sources/SimpleJavaSourceFileA.java
- test/src/main/resources/java_sources/SimpleJavaSourceFileB.java
- twitter_scrooge/twitter_scrooge.bzl
Allow per-target selection of Java compilation toolchain.
Note: This change doesn't add similar functionality to `thrift_library`.
Helps with JDK migrations by allowing targets to incrementally update.  
Also allows targets to opt into newer Java syntax.
Co-authored-by: Shane Delmore <sdelmore@twitter.com>
> Use a public java_compile_toolchain attr instead of _java_toolchain

- scala/private/rules/scala_doc.bzl
Generate `scaladoc` by providing arguments via param file.
When we have a large set of dependencies or source files, `scaladoc` generation fails with the following error,
```
error=7, Argument list too long
``` 
Scaladoc supports reading arguments from an argfile which can help avoid the above problem,
```sh
$ scaladoc -help
...
@<file>                              A text file containing compiler arguments (options and source files)
```
We can do this by using [param file](https://bazel.build/rules/lib/Args#use_param_file).
> scala_doc: Use param file to build scaladocs

- scala/scala_import.bzl
- test/src/main/scala/scalarules/test/scala_import/srcjar/BUILD.bazel
- test/src/main/scala/scalarules/test/scala_import/srcjar/exposes_srcjar_test.bzl
Previously, `scala_import` rules would have no `OutputGroupInfo`, and
therefore would not expose their source jars. Java's counterpart,
`java_import`, does expose the source jars via an entry named
`_source_jars` in `OutputGroupInfo`.
This patch adds an `OutputGroupInfo` provider to `scala_import` rules
containing the source jars in an entry named `_source_jars`.
The source jars of a `scala_import` rule can now be requested by
passing `--output_groups=+_source_jars` to Bazel.
Querying Bazel for the source jars can be useful in a variety of situations, like IDE integration for instance.
> Expose `_source_jars` output group in `scala_import`

- scripts/build_jacocorunner/0001-Build-Jacoco-for-Bazel-5.0+.patch
- scripts/build_jacocorunner/build_jacocorunner_bazel_5.0+.sh
JacocoRunner builder script needs an update for Bazel 5.0+.
Upgraded jacoco package name for Bazel 5.0+.
Upgraded jacoco from 0.8.3 to 0.8.6.
Jacoco upgrade to 0.8.6 was made in Bazel in:
https://github.com/bazelbuild/bazel/issues/11674
https://github.com/bazelbuild/bazel/commit/cb7c1a2ec8de92828a018e2a3450a06f1d1c7efa
Removed options for workarounds where those have been fixed in the meantime:
Bazel's handling for branch coverage was fixed in:
https://github.com/bazelbuild/bazel/issues/12696
If you use a custom-built Jacoco version for Bazel <5.0, then when you upgrade Bazel to 5.0+ you'll need to rebuild that custom Jacoco version, otherwise your coverage executions would fail with an error similar to the following:
```
Cause: java.lang.ClassNotFoundException: …
```
> JacocoRunner script: update for Bazel 5.0+

- .bazelci/presubmit.yml
- docs/scala_test.md
- scala/private/phases/phase_test_environment.bzl
- scala/private/rules/scala_junit_test.bzl
- scala/private/rules/scala_test.bzl
- test/shell/test_inherited_environment.sh
- test_bazel_5_2.sh
- test_bazel_5_2/inherited_environment/A.scala
- test_bazel_5_2/inherited_environment/BUILD
Added support for `inherited_environment` in `scala_test` rule
Follow up on this [slack thread](https://bazelbuild.slack.com/archives/CDCKJ2KFZ/p1653986701998679) I added support for the new `inherited_environment`  to `scala_test`.
This feature requires Bazel version 5.2 rc0 or higher.
While Bazel run tests in isolated environments, when running integration tests there is a need to pass env vars to the tested code - for example, credentials for external systems like databases. This PR added a new flag that is already supported by Bazel.
Note: I am a total noob. I got a lot of help on Slack in order to get to this point but I am not 100% understand everything I changed 🤦  I added a test so I know it is working, I will be helping to have some guidelines on how to run it only on Bazel 5.2: …
> feat: added support for inherited_environment in scala_test rule

- scala/private/rules/scala_doc.bzl
- scala/scala.bzl
Export `ScaladocAspectInfo` to allow users to provide custom aspect implementation to `make_scala_doc_rule`
Some of our scala rules require extra jars to be present on the classpath because of custom rules present in our repo. Its hard to replicate this requirement in tests (#1393 for more information). Exporting the `ScaladocAspectInfo` helps us build a custom aspect implementation for `make_scala_doc_rule` based on some of the custom rules in our repo.
> scala_doc: Export ScaladocAspectInfo to allow users to build custom scaladoc aspects

- scala/private/rule_impls.bzl
- test_rules_scala.sh
java_executable_exec_path does not look up the right path when resolving
the JDK from the runfiles directory and legacy_external_runfiles is disabled.
java_executable_runfiles_path should be used instead.
Examples of these paths when running "bazel build test:ScalaBinaryInGenrule":
java_executable_exec_path: external/remotejdk11_macos/bin/java
java_executable_runfiles_path: ../remotejdk11_macos/bin/java
The working directory appears to be
ScalaBinary.runfiles/io_bazel_rules_scala.
When legacy_external_runfiles is enabled, the JDK is present in
ScalaBinary.runfiles/remotejdk11_macos but is also linked
in ScalaBinary.runfiles/io_bazel_rules_scala/external/remotejdk11_macos,
so looking up using either exec_path or runfiles_path is correct.
When legacy_external_runfiles is disabled, the JDK …
> Fix rules_scala JDK lookup when using --nolegacy_external_runfiles.

- docs/scala_repl.md
- scala/private/phases/phase_declare_executable.bzl
- test/BUILD
- test/artifact_prefix_conflict_example/example/ArtifactPrefixConflictExample.scala
- test/artifact_prefix_conflict_example/example/BUILD
- test/artifact_prefix_conflict_example/example/example/BUILD
- test/artifact_prefix_conflict_example/example/example/Somefile.scala
- test/rootpaths_binary.sh
- test/shell/test_misc.sh
Add an extension for the executable runfile in non-Windows OS (`.sh`) to prevent an issue with `ArtifactPrefixConflictException`.
When `foo:bar` is a binary (or test), it will generate a runfile artifact, `<bazel-out>/.../foo/bar`.
If we also have a subdirectory `foo/bar` with targets, then there will be a conflict since those targets (e.g. `foo/bar:baz`) will need the  `<bazel-out>/.../foo/bar` output path, but that is already taken by our first artifact, resulting in Bazel erroring out with `com.google.devtools.build.lib.skyframe.ArtifactConflictFinder$ConflictException: com.google.devtools.build.lib.actions.ArtifactPrefixConflictException`.
Remove conflicts between runfile executables and directory names.
> Declare non-windows executable with .sh extension

- WORKSPACE
- jmh/jmh.bzl
- test/jmh/BUILD
- test/jmh/TestJmhRuntimeJdk11.scala
- test/jmh/TestJmhRuntimeJdk8.scala
- test/jmh/test_binary.sh
Include `runtime_jdk` as an an `attr` on `jmh_support:benchmark_generator`.
`scala_benchmark_jmh` can now specify a Java runtime to build its `scala_binary` with.
To test whether our changes work for different specified JDKs, we include [rules_java@5.1.0](https://github.com/bazelbuild/rules_java/tree/5.1.0) as an `http_archive`.
We don't override our Bazel's (`@.bazelversion`) `rules_java` and instead pull in the newer `rules_java` as `@rules_java_extra`.  
This allows us to use `remote_jdk8` runtimes specified [here](https://github.com/bazelbuild/rules_java/blob/5.1.0/java/repositories.bzl). 
We want to be able to use JMH benchmarking on different Java runtimes. 
Co-authored-by: Shane Delmore <sdelmore@twitter.com>
> Allow scala_benchmark_jmh to specify a runtime_jdk version

- CONTRIBUTING.md
- docs/scala_binary.md
- docs/scala_library.md
- docs/scala_macro_library.md
- `http://bazel.io/docs/be/` -> `https://bazel.build/reference/be/`
- `#borne-shell-tokenization` -> `#sh-tokenization`
- https://bazel.build/reference/be/common-definitions.html#sh-tokenization
While browsing the docs, realized some links are deprecated, fixing the links
> docs: fix broken links

- scala/private/phases/phase_write_executable.bzl
fix https://github.com/bazelbuild/rules_scala/issues/1431
- This PR enables to override `JAVABIN` in the wrapper script generated by `scala_binary` rule
- This behavior aligns to the wrapper script generated by `java_binary` (sorry I couldn't find where the wrapper script for `java_binary` defined, but something like)
- for `java_binary`: `JAVABIN=${JAVABIN:-${JAVA_RUNFILES}/local_jdk/bin/java}`
please see: https://github.com/bazelbuild/rules_scala/issues/1431
> fix: enable to override JAVABIN of wrapper script

- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/OptionsParser.scala
fix: https://github.com/bazelbuild/rules_scala/issues/1398
This PR suppresses a warning like
```
scalac failed: error executing command bazel-out/host/bin/external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac ... (remaining 1 argument skipped)
external/io_bazel_rules_scala/third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/OptionsParser.scala:49: warning: method copyArrayToImmutableIndexedSeq in class LowPriorityImplicits2 is deprecated (since 2.13.0): Implicit conversions from Array to immutable.IndexedSeq are implemented by copying; Use the more efficient non-copying ArraySeq.unsafeWrapArray or an explicit toIndexedSeq call
takeStringOpt(key).map(_.split(":"))
^
```
As described by https://github.com/bazelbuild/rules_scala/issues/1398, we …
> Suppress warning and enable to use dependency_tracking with `-Werror`

- README.md
- WORKSPACE
- scala/private/macros/scala_repositories.bzl
- scala/scala.bzl
- test/shell/test_scala_config.sh
- third_party/repositories/repositories.bzl
- third_party/repositories/scala_2_11.bzl
- third_party/repositories/scala_2_12.bzl
- third_party/repositories/scala_2_13.bzl
- third_party/repositories/scala_3_1.bzl
Add validation to prevent Scala version mismatch between `scala_config` and default repositories.
In case there are no overrides, we fail the build if Scala version in scala_config does not match available version in default repositories.
Additionally, macros `rules_scala_toolchain_deps_repositories` and `rules_scala_setup` are exported for easier setup of Rules Scala dependencies.
Without validation it is easy to get wrong version loaded under the impression that `scala_config` controls dependency versions.
For example, such maintenance as in #1434 would get better feedback when Scala version is not properly configured
> Validate repository Scala version against scala_config

- docs/scala_repl.md
- scala/private/phases/phase_declare_executable.bzl
- test/BUILD
- test/artifact_prefix_conflict_example/example/ArtifactPrefixConflictExample.scala
- test/artifact_prefix_conflict_example/example/BUILD
- test/artifact_prefix_conflict_example/example/example/BUILD
- test/artifact_prefix_conflict_example/example/example/Somefile.scala
- test/rootpaths_binary.sh
- test/shell/test_misc.sh
Reverts bazelbuild/rules_scala#1407
1407 was a breaking change.
The issue was that IJWB [assumes](https://github.com/bazelbuild/intellij/blob/a5522a0f1787b667a3a966e927da773cb4ec51a2/java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildTestEnvironmentCreator.java#L90) the runfiles and executable are the same name as the target (java convention) and #1407 broke this convention/assumption by having the executable named `<target>.sh` and runfiles `<target>.sh.runfiles` directory.
> Revert "Declare non-windows executable with .sh extension"

- README.md
Current instructions in the readme use older commit of Rules Scala which does not yet have updated macros used in WORKSPACE setup.
> Update Rules Scala commit in README instructions

- README.md
- docs/scala_toolchain.md
- scala/BUILD
- scala/private/macros/setup_scala_toolchain.bzl
- scala/scala.bzl
Added `setup_scala_toolchain` macro to simplify scala toolchain setup.
To configuration of custom scala toolchain one needs to understand implementation details like dependency provider ids, which makes it a complicated task. We can encapsulate those details under a macro.
> Simplify setup of scala_toolchain and its deps

- scala/private/phases/phase_write_executable.bzl
Fix toolchain type reference
Otherwise I am seeing the following build error
```
Traceback (most recent call last):
File "/home/tgeng/.cache/bazel/_bazel_tgeng/7b03291da6ccf13fbe3c6d43388e7cbb/external/io_bazel_rules_scala/scala/private/rules/scala_binary.bzl", line 32, column 22, in _scala_binary_impl
return run_phases(
File "/home/tgeng/.cache/bazel/_bazel_tgeng/7b03291da6ccf13fbe3c6d43388e7cbb/external/io_bazel_rules_scala/scala/private/phases/api.bzl", line 45, column 23, in run_phases
return _run_phases(ctx, builtin_customizable_phases, target = None)
File "/home/tgeng/.cache/bazel/_bazel_tgeng/7b03291da6ccf13fbe3c6d43388e7cbb/external/io_bazel_rules_scala/scala/private/phases/api.bzl", line 77, column 32, in _run_phases
new_provider = function(ctx, current_provider)
File …
```
> Fix toolchain type reference

- scala/private/common_attributes.bzl
- scala/private/phases/phase_compile.bzl
- test/jmh/BUILD
Remove zipper from common attributes, singlejar is already there and can generate jars with resources.
Looking at bazel source code `singlejar` utility is used for:
* [pack_sources](https://github.com/bazelbuild/bazel/blob/455454a56e961affb041a1d4a9214f7f313a05aa/src/main/java/com/google/devtools/build/lib/rules/java/JavaInfoBuildHelper.java#L198)
* [resources_jar](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/java/ResourceJarActionBuilder.java#L123)
Motivation:
* use precompiled binaries ie singlejar comes precompiled via remote_java_tools while zipper is built from sources (at least in remote execution)
* use single tool to accomplish same goal
> Replace zipper with singlejar

- third_party/repositories/scala_2_11.bzl
- third_party/repositories/scala_2_12.bzl
- third_party/repositories/scala_2_13.bzl
- third_party/repositories/scala_3_1.bzl
Also bump versions of its dependencies:
* org.ow2.asm:asm: 6.1.1 -> 9.0
* net.sf.jopt-simple:jopt-simple: 4.6 -> 5.0.4
Increase version of [jmh](https://github.com/openjdk/jmh) from 1.20 to 1.36
Changes: https://github.com/openjdk/jmh/compare/1.20...1.36
Keep up with the latest JMH.
> Bump jmh version: 1.20 -> 1.36

- scala/private/rules/scala_test.bzl
Have _lcov_merger run in the exec configuration. This fixes issues when running coverage when `--java_runtime_version` is a JRE 8 on Bazel > 6.x, similar to https://github.com/bazelbuild/bazel/issues/17568.
Fixes coverage on JRE 8.
> Add exec transition to scala_test _lcov_merger

- .github/workflows/release.yml
- .github/workflows/workspace_snippet.sh
Github generated archive may not be stable - let's upload custom archive to keep stable checksum
> Update release workflow with a stable archive

- scala/support/BUILD
- test/shell/test_examples.sh
- third_party/repositories/repositories.bzl
- third_party/repositories/scala_3_2.bzl
Add support of Scala 3.2
- Add the build and repository definitions for Scala 3.2.1
- Add an extra set of tests for Scala 3.2.1
- To stay as close as possible to the head of Scala.
-  To make new features in Scala 3.2 available to developers.
Fixes #1464
> Add support for Scala 3.2

- src/java/io/bazel/rulesscala/scalac/ScalacWorker.java
- test/shell/test_persistent_worker.sh
- test_expect_failure/scalac_exceptions/BUILD
- test_expect_failure/scalac_exceptions/BadMacro.scala
- test_expect_failure/scalac_exceptions/BadMacroInvocation.scala
- test_rules_scala.sh
Catch scalac exceptions that occur during expansion of user macros so that the entire worker doesn't crash.
Fixes #1488
> Catch macro expansion exceptions in ScalacWorker

- scala/private/common.bzl
- scala/private/phases/phase_write_executable.bzl
- scala/private/rule_impls.bzl
- src/java/io/bazel/rulesscala/exe/LauncherFileWriter.java
For Windows, this PR fixes issue where outputs of scala_test and scala_binary are failing when ran with 'bazel run' and 'bazel test'. When trying to do run or test, Bazel shows error like:
> LAUNCHER ERROR: rlocation failed on “external\localjdk\bin\java.exe not found in MANIFEST”.
The Fix:  On Windows, Bazel’s Java Launcher was being passed paths in the wrong ‘form’. The launcher expects rpathlocation form for some paths and rootpath form for others. Fix is to pass the right forms of the paths to the LauncherFileWriter which in turn passes correct paths into the Launcher.
scala_test and scala_binary should work properly on Windows
Seems to have been caused by #1313
Should also fix #1497
The following can be used as a demonstration test on windows (will fail before this PR):
`bazel test …
> For Windows: Fix to enable scala_test and scala_binary outputs to be executed on Windows

- src/java/io/bazel/rulesscala/scalac/reporter/DepsTrackingReporter.java
This fixes issue where the ‘compiler-dependency-analyzer’ was not handling Windows path separator and failed with false negatives. 
* Added one-liner in DepsTrackingReporter.java that replaces ‘\\’ with ‘/’ in the paths it receives from the scalac compiler.
Makes the new compiler-dependency-analyzer work on Windows. 
Before this PR, on Windows, compiling would report a bunch of erroneous 'unused deps' errors.
This fixes #1487
> Make DepsTrackingReporter handle Windows path separators

- src/java/io/bazel/rulesscala/scalac/ReportableMainClass.java
- src/java/io/bazel/rulesscala/scalac/ScalacWorker.java
This PR fixes the scalacWorker so that it calls close() on the compiler object (nsc.Global) after each job is done. This allows file resources (i.e. dependent jar files, source files, etc) that the compiler uses to be properly released after each job.
Note that nsc.Global did not add the close() functionality until v2.12. This is handled in this PR.
This issue was noticed more on Windows since Windows will lock the file (and not allow edits) until it is released. And with scalacWorker being a persistent process, it would lock the files until you called “bazel shutdown”. 
This should resolve #1486, where this issue was causing *-ijar.jar handles not to be released.
_Aside: There is still an issue where the jars for plugins are not being released (because calling nsc.Global.close() does not …
> call close() on compiler in scalacWorker after each job

- scala/scala_import.bzl
Any rule which uses java_common should register java toolchain_type.
> Register java toolchain inside rules_scala

- scala/private/rules/scala_binary.bzl
- scala/private/rules/scala_library.bzl
- scala/private/rules/scala_test.bzl
Description
Any rule which uses java_common should register java toolchain_type.
Fixes: https://github.com/bazelbuild/rules_scala/issues/1507
> Register Java Toolchain

- scala/private/common_attributes.bzl
- scala/private/phases/phase_compile.bzl
- scala/private/phases/phase_merge_jars.bzl
Use single jar utility from toolchains instead of private attribute.
* toolchain comes with precompiled singlejar from remote_java_tools
* it would allow to configure your own if needed
> singlejar executable from specified java compile toolchain

- README.md
- WORKSPACE
- dt_patches/dt_patch_test.sh
- dt_patches/test_dt_patches_user_srcjar/WORKSPACE
- scala_config.bzl
- test/coverage_filename_encoding/expected-coverage.dat
- test/coverage_scalatest/expected-coverage.dat
- test/coverage_specs2_with_junit/expected-coverage.dat
- test/shell/test_scala_config.sh
- test/src/main/scala/scalarules/test/compiler_plugin/BUILD.bazel
- test/src/main/scala/scalarules/test/compiler_plugin/KindProjected.scala
- test_version.sh
- third_party/repositories/scala_2_11.bzl
- third_party/repositories/scala_2_12.bzl
- third_party/repositories/scala_2_13.bzl
- third_party/repositories/scala_3_1.bzl
- third_party/repositories/scala_3_2.bzl
- third_party/repositories/scala_3_3.bzl
Bumping supported Scala 2.12 and 2.13 minor versions
Found a compilation issue related to `kind_projector` so updated to latest artifacts as well for all Scala major versions.
I wanted to level up minor Scala versions before trying to tackle #1514 that has breaking changes related to Scala `2.13.12`
> Upgrade scala 2.12.x and 2.13.x versions

- examples/semanticdb/WORKSPACE
- third_party/repositories/scala_2_12.bzl
- third_party/repositories/scala_2_13.bzl
This PR addresses current build issues regarding `semanticdb-scalac` checksums and Scala `2.13.x` version used in `examples/semanticdb` that was not up-to-date
Builds are currently failing because of : 
```
(15:35:14) WARNING: Download from https://repo.maven.apache.org/maven2/org/scalameta/semanticdb-scalac_2.12.18/4.8.4/semanticdb-scalac_2.12.18-4.8.4.jar failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 11d28a73d182453454451aef4768462730f8c3e369df47b224a4ff2e943f1db7 but wanted f31614cd13b6dc5c97804aa814b6f7ad4d67124290c08d0c9296b53e46d744e0
```
and : 
```
Error in fail: Scala config (2.13.6) version does not match repository version (2.13.11)
```
cc @crt-31
> Fix semanticdb-scalac checksums for Scala 2.12.18 and 2.13.11

- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinder.scala
Unfortunately I can't quickly figure out how to create a public repro for this one (any help would be appreciated). During the last few years I faced this issue 4 times, where scalac worker got into the infinite loop.
I've added explicit tracking of cycles using `mutable.Set[Tree]` of visited tree notes, which seems to be fixing the infinite loop problem.
> Fix handling of cycles in AST traversal in Dependency Analyzer

- jmh/jmh.bzl
- scala/private/rules/scala_junit_test.bzl
Added `@bazel_tools//tools/jdk:toolchain_type` toolchain for scala_junit_test: https://github.com/bazelbuild/bazel/issues/18970
Changed deprecated transitive_runtime_deps to transitive_runtime_jars in jmh.bzl:
https://bazel.build/versions/6.4.0/rules/lib/JavaInfo#transitive_runtime_deps
With these changes rules_scala (for the cases I checked) started working with Bazel 7.0 rc2.
> Bazel 7.0 rc2 support

- docs/scala_proto_library.md
Add default toolchains registration code to `scala_proto_library` documentation.
Closes #768
For a simple usage of `scala_proto_library` without customization, it seems default toolchains registration must be done, otherwise users will get error like: `ERROR: No matching toolchains found for types @io_bazel_rules_scala//scala_proto:toolchain_type.`
> doc: Register proto toolchain for simple usage

- README.md
Use Rules Scala tag version in README. Hopefully this adds more clarity how to configure Rules Scala
> Use tagged Rules Scala release in README.md

- scala_proto/private/scala_proto_aspect.bzl
Adds missing dependency on `@bazel_tools//tools/jdk:toolchain_type` to `scala_proto_aspect` as required since Bazel 7
> Add jdk toolchain type to proto rules

- examples/semanticdb/aspect.bzl
- scala/private/phases/phase_semanticdb.bzl
- scala/semanticdb_provider.bzl
- test/semanticdb/rules.bzl
Changed SemanticdbInfo.plugin_jar from path string to File
This keeps the File object available for users of SemanticdbInfo. 
Addresses #1527 
(Note, this does change the public interface a bit, but should be fine since SemanicDBInfo is very new.)
> Change SemanticdbInfo.plugin_jar from string to File

- examples/scala3/WORKSPACE
- test/shell/test_examples.sh
- test/shell/test_semanticdb.sh
- third_party/repositories/scala_3_3.bzl
Update supported Scala version from 3.3.0 to 3.3.1 as it is the latest PATCH version.
https://github.com/bazelbuild/rules_scala/issues/1526
> Support Scala 3.3.1

- .bazelci/presubmit.yml
Added task on CI to run on Windows. 
Running the CI on Windows will help ensure this library ensure this library maintains continuous compatibility with Windows OS. (this is essentially a follow-on to #1529)
> Added windows task to CI

- .scalafmt.conf
- docs/phase_scalafmt.md
- scala/scalafmt/scalafmt_repositories.bzl
- third_party/repositories/scala_2_11.bzl
- third_party/repositories/scala_2_12.bzl
- third_party/repositories/scala_2_13.bzl
- third_party/repositories/scala_3_1.bzl
- third_party/repositories/scala_3_2.bzl
- third_party/repositories/scala_3_3.bzl
Bump scalafmt version
With older version formatting didn't work for scala3
> Bump scalafmt version

- third_party/repositories/scala_3_3.bzl
Fix checkum for Scala 3.3 and [dependency](https://mvnrepository.com/artifact/org.scala-lang.modules/scala-parallel-collections_3/1.0.4). Correct checksum should be c3bf0d4d057942a78389fa9675823db5e3179f1b503f2df212b74e784da57050
Current checksum is invalid for `scala-parallel-collections_3/1.0.4`
> Fix checksum io_bazel_rules_scala_scala_parallel_collections in Scala3.3

- src/java/io/bazel/rulesscala/scalac/ScalacInvoker.java
This fixes functionality that was accidently broken in PR #1529   (my bad).
The fix is to call close on the compiler within the scalaCWorker (originally added in PR #1504)
> Fix to close the compiler object in scalacinvoker 

- README.md
Add VirtusLab as a user of Bazel Scala rules
We are using Bazel Scala rules for our nad our client's projects. As the maintainer of Scala 3, we have started to work on improving support for Scala (especially Scala 3) in Bazel.
> Add VirtusLab as adopter

- scala/private/phases/phase_default_info.bzl
Check that the names exist before trying to remove them from the list of fields on a struct.
These methods do not exist if --incompatible_struct_has_no_methods is passed or if they
have been removed in a future version of Bazel.
> Handle the removal of to_proto and to_json from struct

- cross-compilation-doc.md
- scala_config.bzl
A variable to hold all (possibly more than one in the future) configured versions of Scala.
#1552 may be still too big to review. Let's start with some manageable, smaller chunks.
Plan for following PRs: https://github.com/bazelbuild/rules_scala/compare/master...aszady:rules_scala:cross-compilation?expand=1
> Introduce `SCALA_VERSIONS`

- cross-compilation-doc.md
- scala/scala_cross_version.bzl
- scala_config.bzl
Build setting & config setting to transition and query about the Scala version.
A small change compared to #1552 is that I don't allow an empty string value for the build setting.
This shouldn't change any behavior.
> Introduce build setting for current Scala version

- cross-compilation-doc.md
- scala/private/phases/phase_compile.bzl
- scala/private/phases/phase_semanticdb.bzl
- scala/scala_toolchain.bzl
Before enabling cross-build we need to review (and most likely replace) all uses of `SCALA_VERSION`. This PR reviews usage of `SCALA_VERSION` when a resolved toolchain is available.
This shouldn't change any behavior.
> Don't rely on `SCALA_VERSION` in phases

- scala_proto/private/scala_proto_aspect.bzl
Add `provides = [ScalaProtoAspectInfo]` to `scala_proto_aspect`.
`scala_proto_aspect` always returns a `ScalaProtoAspectInfo` provider, so there's no reason why the provider is not listed in the `aspect(provides=[…])` list. Crucially, having `provides = [ScalaProtoAspectInfo]` enables [aspect-on-aspect](https://bazel.build/reference/glossary#aspect-on-aspect), allowing a second aspect to inspect the result of `scala_proto_aspect`.
> Make scala_proto_aspect have "provides = [ScalaProtoAspectInfo]"

- twitter_scrooge/twitter_scrooge.bzl
Add `provides = [ScroogeAspectInfo]` to `scrooge_scala_aspect` and `scrooge_java_aspect`.
Same as #1549 – allows for aspect-on-aspect introspection of these aspects.
> Make scrooge_*_aspect have "provides = [ScroogeAspectInfo]"

- .bazelci/presubmit.yml
- WORKSPACE
- scala/private/common_attributes.bzl
- scala/private/phases/phase_coverage.bzl
- scala/private/phases/phase_scalafmt.bzl
- scala/private/phases/phase_write_executable.bzl
- scala/private/rule_impls.bzl
- scala/scalafmt/phase_scalafmt_ext.bzl
- scala_proto/private/scala_proto_aspect.bzl
- test/BUILD
- test/toolchains/BUILD.bazel
- test/toolchains/jdk.bzl
- twitter_scrooge/twitter_scrooge.bzl
Codebase doesn't build with jdk 21 with default settings.
Issue is that workers and test runners use SecurityManager which fails at runtime.
Fix is to conditionally add -Djava.security.manager=allow jvm flag to:
- tools executed via ctx.actions.run if host jdk is >= 17
- generated test executables if target jdk is >= 17
This change involves some kind of guessing with which jdk version worker will be run. 
JDK is linked into worker/executable runfiles and it matches host jdk (hence added _java_host_runtime attribute to all relevant rules)
Added separate [build](https://github.com/bazelbuild/rules_scala/pull/1556/files#diff-b03048100ab56455b5b377a5c20ffd3d17f80c719befca45253af622eb9395efR93) for jdk 21
> Build with JDK 21

- cross-compilation-doc.md
- scala/private/macros/setup_scala_toolchain.bzl
- scala/scalafmt/BUILD
- testing/testing.bzl
Use `target_settings` to indicate which Scala version is supported by the toolchain. This will become useful when multiple toolchains for each Scala version are defined.
The choice of toolchains to cover by this (first) migration is quite arbitrary, but should be enough to enable the basic cross-build use cases.
No change in behavior if the default Scala version is used.
> Bind toolchains to Scala version

- scripts/build_jacocorunner/0001-Build-Jacoco-for-Bazel-7.0.patch
- scripts/build_jacocorunner/build_jacocorunner.sh
rules_scala has issues with coverage on JDK 21.
Bazel has solved this in https://github.com/bazelbuild/bazel/issues/20845 by upgrading Jacoco and ASM.
Added option to build JacocoRunner for Bazel 7, the version with fix will be used with Jacoco interface changes.
Jacoco upgraded to 0.8.11 (including the Jacoco/Bazel branches used for that).
> JacocoRunner script: update for Jacoco 0.8.11 and Bazel 7.0.2

- scala/BUILD
- scala/private/macros/setup_scala_toolchain.bzl
Purely refactoring change.
Encapsulates the logic of selecting dependencies into a function. Should come in handy in future changes.
Partitioned from / inspired by #1552.
> Move default toolchain dependencies logic to .bzl file

- cross-compilation-doc.md
- scala/scala_cross_version_select.bzl
For later use in BUILD files of `rules_scala` where customization depending on Scala version is needed.
End users are also encouraged to use this one.
The approach in this PR differs from the one in #1552, as with selects we will avoid the need of multiplying targets within `rules_scala` for each Scala version configured.
This comes at a cost of not so easy access to the internal binaries for a specific, non-default version. #1552 proposed suffixing target names with the Scala version, whereas here the target built depends on a configuration – harder to specify via command-line. Possible workaround for this, if ever needed, would be to use a flag (see: https://github.com/bazelbuild/rules_scala/pull/1558#discussion_r1539128621).
The choice of matchers is quite arbitrary, but covers the …
> Provide `select_for_scala_version` utility macro

- cross-compilation-doc.md
- scala/private/rules/scala_binary.bzl
- scala/private/rules/scala_junit_test.bzl
- scala/private/rules/scala_library.bzl
- scala/private/rules/scala_repl.bzl
- scala/private/rules/scala_test.bzl
- scala/scala_cross_version.bzl
Implements transition and exposes it via the `scala_version` attribute for a number of common rules.
No effect at the moment, as for now we have only one valid setting.
After allowing more Scala versions when configuring rules repository, this will become the central part of the cross-build.
> Allow transitioning Scala version with `scala_version` attribute of rules

- scala/private/macros/scala_repositories.bzl
- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/compiler/BUILD
A small preparation for multiple `SCALA_VERSIONS`.
In theory breaking, as removes `@scala_compiler_source` repository.
But I guess it's too internal to anyone depend on it.
> Use version-aware naming for `scala_compiler_source` repository

- examples/testing/multi_frameworks_toolchain/BUILD
- scala/private/macros/scala_repositories.bzl
- scala/private/macros/setup_scala_toolchain.bzl
- scala/scalafmt/BUILD
- scala/scalafmt/scalafmt_repositories.bzl
- scalatest/scalatest.bzl
- test/plugins/BUILD
- testing/BUILD
- third_party/dependency_analyzer/src/test/analyzer_test.bzl
- third_party/dependency_analyzer/src/test/analyzer_test_scala_2.bzl
- third_party/dependency_analyzer/src/test/analyzer_test_scala_3.bzl
- third_party/repositories/repositories.bzl
It enables the logic implemented in #1562. The choice of toolchains to cover is the same as in #1566.
Now, e.g., instead of referring to the artifact's repository `@io_bazel_rules_scala_scala_compiler`, we ~need to~ may use the version-aware name, like `@io_bazel_rules_scala_scala_compiler_3_3_0`.
**In future** this may require an update in client's code. In particular in cases they don't use the default toolchains provided by the rules, and construct their own dependency providers. One would need to manually add the version suffix to the repository names, or use a construction like `+ version_suffix(SCALA_VERSION)` in their code.
**For now** a backward compatibility layer is provided in a shape of repository with aliases, pointing to artifacts for the default Scala version.
#1290
> Use version-aware naming for artifact repositories

- scala/private/macros/scala_repositories.bzl
- scala/scalafmt/scalafmt_repositories.bzl
- scalatest/scalatest.bzl
Basically make the artifacts available for all configured Scala versions (currently still only one).
After #1573 these will be available under version-suffixed repository names.
> Download artifacts for all `SCALA_VERSIONS`

- scala/BUILD
- scala/scalafmt/BUILD
- scala/scalafmt/scalafmt_repositories.bzl
- scala/scalafmt/toolchain/setup_scalafmt_toolchain.bzl
- scala/toolchains.bzl
- testing/BUILD
- testing/scalatest.bzl
- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/compiler/BUILD
Build and register toolchains for all `SCALA_VERSIONS`.
There are aliases for toolchains for default Scala version provided – for backward-compatibility, similarly as in #1573.
> Build and register toolchains for all `SCALA_VERSIONS`

- scala/private/rules/scala_doc.bzl
- test/shell/test_scaladoc.sh
- test_expect_failure/scaladoc/A.scala
- test_expect_failure/scaladoc/B.scala
- test_expect_failure/scaladoc/BUILD
- test_expect_failure/scaladoc/C.scala
- test_expect_failure/scaladoc/scaladoc.bzl
- test_rules_scala.sh
The main goal of this PR is to fix issue where transient dependencies weren't being handled correctly. This issue manifested itself when there was an external library (i.e. scala_import) that was a transient dependency. 
Also added tests for the scaladoc rule.
This is needed for the scaladoc rule to work correctly.
I believe this also addresses the issue that #1331 was trying to address.
> Make scaladoc rule handle transient deps better (and add some tests)

- cross-compilation-doc.md
- scala_config.bzl
In my belief, all the changes required in order to enable this feature are done.
We can flip the switch!
Please find the following draft PRs as a support for this change:
#1290
> Allow configuring multiple Scala versions

- .bazelci/presubmit.yml
- test/shell/test_cross_build.sh
- test_all.sh
- test_cross_build.sh
- test_cross_build/WORKSPACE
- test_cross_build/version_specific/BUILD
- test_cross_build/version_specific/before_3_2.scala
- test_cross_build/version_specific/before_3_3.scala
- test_cross_build/version_specific/since_3_1.scala
- test_cross_build/version_specific/since_3_2.scala
- test_cross_build/version_specific/since_3_3.scala
Register a new test, for cross-build feature.
Here I propose a collection of arbitrarily chosen backward- and forward-incompatible code.
This simply tests if the proper compiler is assigned, according to Scala version setting.
#1290
> Tests with version-specific codes

- README.md
- docs/cross-compilation.md
Adding the very basic usage of the rules with multiple Scala versions.
Moving the doc file to the `docs/` folder & referring it from the main Readme.
Please review the docs as a whole, maybe there's sth else that should be included? 
#1290
> Documentation update after development of the cross-build

- test/shell/test_cross_build.sh
- test/shell/test_scalafmt.sh
- test/shell/test_scalafmt_helper.sh
- test_cross_build/WORKSPACE
- test_cross_build/scalafmt/.scalafmt2.conf
- test_cross_build/scalafmt/.scalafmt3.conf
- test_cross_build/scalafmt/BUILD
- test_cross_build/scalafmt/formatted/formatted-binary2.scala
- test_cross_build/scalafmt/formatted/formatted-binary3.scala
- test_cross_build/scalafmt/formatted/formatted-library2.scala
- test_cross_build/scalafmt/formatted/formatted-library3.scala
- test_cross_build/scalafmt/formatted/formatted-test2.scala
- test_cross_build/scalafmt/formatted/formatted-test3.scala
- test_cross_build/scalafmt/scalafmt_rules.bzl
- test_cross_build/scalafmt/unformatted/unformatted-binary2.scala
- test_cross_build/scalafmt/unformatted/unformatted-binary3.scala
- test_cross_build/scalafmt/unformatted/unformatted-library2.scala
- test_cross_build/scalafmt/unformatted/unformatted-library3.scala
- test_cross_build/scalafmt/unformatted/unformatted-test2.scala
- test_cross_build/scalafmt/unformatted/unformatted-test3.scala
First, I'm extracting a common script parts for Scalafmt testing.
Then attaching the last piece of code by @mateuszkuta256, which tests if Scalafmt cooperates correctly with alternate Scala versions.
#1290
> Add scalafmt test with multiple Scala versions

- scala_config.bzl
I cannot upgrade from 6.3.0 to 6.5.0 without this change, see attached issue below.
See #1590
> Make suffixed scala version config setting publicly visible

- src/java/io/bazel/rulesscala/scala_test/Runner.java
Normalize file paths before passing them to runfiles.rlocation() within the test runner. 
Before this change, you could not execute a bazel test target that is not in the primary workspace, it would error with 
For example running `bazel run @my_external_repo//my/path/to:test` 
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at com.google.testing.coverage.JacocoCoverageRunner.main(JacocoCoverageRunner.java:592) …
```
> [bugfix] normalize paths to enable running external tests

- src/java/io/bazel/rulesscala/scalac/ScalacInvoker.java
- src/java/io/bazel/rulesscala/scalac/ScalacInvoker3.java
- src/java/io/bazel/rulesscala/scalac/ScalacWorker.java
- src/java/io/bazel/rulesscala/worker/Worker.java
- test/shell/test_invalid_scalacopts.sh
- test_expect_failure/scalacopts_invalid/BUILD
- test_expect_failure/scalacopts_invalid/Empty.scala
- test_rules_scala.sh
- Handle cases when passing invalid scalac options 
- Prevent printing internal stack traces of ScalaWorker on compilation failing in an expected way
Fixes #1605 
When passing invalid scalac options, eg. `-source:not-existing` the Scala compiler would either: 
- return `None` form `Driver.setup` leading to runtime exception in `None.get` (Scala 3) 
- would not create an instance in `Driver.newCompiler` required to create `ProtoReporter` or `DepsTrackingReporter` leading to `reporter` being not initialized (Scala 2) 
This fix handles both of this cases by termination executing earlier with a known exception. 
In each of cases Scalac compiler would always show error message about which setting was invalid. This is expected behaviour. Because of that, there is no reason to print stack traces …
> Handle incorrect Scalac options and prevent printing ScalacWorker stacktraces

- examples/scala3/WORKSPACE
- scala/private/macros/scala_repositories.bzl
- scala/private/macros/setup_scala_toolchain.bzl
- test/shell/test_examples.sh
- third_party/repositories/repositories.bzl
- third_party/repositories/scala_3_1.bzl
- third_party/repositories/scala_3_3.bzl
- third_party/repositories/scala_3_4.bzl
-  Added artifacts for Scala 3.4.3 version
-  Updated tests that are dependent on the chosen scala version
-  Fixed `java.lang.NoClassDefFoundError: xsbti/UseScope` for Scala versions >= 3.4.0
There are newer versions of Scala that can be supported.
> Scala 3.4.3 support

- scala/private/rule_impls.bzl
- test/shell/test_toolchain.sh
- test_expect_failure/compilers_javac_opts/BUILD
Fixes https://github.com/bazelbuild/rules_scala/issues/1550
Currently the default javac flags will be appended last, overriding the manual ones.
> extra javac opts should override default ones

- scala/scala_maven_import_external.bzl
https://github.com/bazelbuild/rules_scala/pull/1509 missed a spot - netrc authentication also needs to be added to downloading sources for this to work in an environment, where we only use private mirrors, and these private mirrors will not even respond without authentication.
I found myself needing this kind of change at work. I would like to contribute this change so that I don't have to patch this into my Bazel workspace.
> Add netrc support for downloading sources

- scala_proto/private/scala_proto_aspect.bzl
Fixes protobuf related build failures under Bazel 7, while remaining compatible with Bazel 6.
Related to #1482, #1618, and #1619. Results from the investigation documented at:
- https://github.com/bazelbuild/rules_scala/pull/1619#issuecomment-2394853772
Updates `_import_paths()` in `scala_proto_aspect.bzl` to handle differences `ProtoInfo.proto_source_root` and `ProtoInfo.direct_sources` values between Bazel 6 and Bazel 7.
Without this change, `_import_paths()` emits incorrect values under Bazel 7, causing targets containing generated `.proto` inputs to fail, e.g.  `//test/proto3:test_generated_proto`.
See also:
- Fix paths for sibling repository setup and generated .proto files https://github.com/bazelbuild/bazel/commit/6c6c196ceffe14c9cf29960ef4049469df73d991
- The docstring for …
> Fix Bazel 7 related protobuf build failures

- .bazelci/presubmit.yml
Reverts https://github.com/bazelbuild/rules_scala/pull/1349
This task should be optional however it fails all builds because failing `bazel info`.
Error is related to workspace setup. Since we are in the process of moving to bzlmod I think we should not bother with that now. Especially when reproducing locally it gives different error.
Unblock pull requests.
> Build against latest bazel version instead of last_green

- scala/scalafmt/toolchain/setup_scalafmt_toolchain.bzl
- scala_proto/default/default_deps.bzl
- scripts/README.md
- scripts/create_repository.py
- third_party/repositories/scala_2_11.bzl
- third_party/repositories/scala_2_12.bzl
- third_party/repositories/scala_2_13.bzl
- third_party/repositories/scala_3_1.bzl
- third_party/repositories/scala_3_2.bzl
- third_party/repositories/scala_3_3.bzl
- third_party/repositories/scala_3_4.bzl
- third_party/repositories/scala_3_5.bzl
- Updated SHA's, dependencies, artifacts for all of the scala_x_x.bzl repository files with transitive dependencies compliance
- Added a script that simplifies creating and updating scala_x_x.bzl repository files.
It's not the ideal version, but I believe it can be improved by adding support for more Scala artifacts.
Updating and creating new versions for scala_x_x.bzl files is time-consuming, and it's a kind of work that is not performed regularly due to its specifics.
> Automated creating and updating scala_x_x.bzl repository files

- third_party/repositories/scala_2_11.bzl
- third_party/repositories/scala_2_12.bzl
- third_party/repositories/scala_2_13.bzl
- third_party/repositories/scala_3_1.bzl
- third_party/repositories/scala_3_2.bzl
- third_party/repositories/scala_3_3.bzl
- third_party/repositories/scala_3_4.bzl
- third_party/repositories/scala_3_5.bzl
Bumps every Scala version up to use protobuf-java:4.28.2. Part of #1482.
As part of my [Bzlmod exploration in my rules_scala fork](https://github.com/mbland/rules_scala/tree/bzlmod), I found that `//test/scalafmt/...` wouldn't build under Scala 2.13.14 due to using an outdated Scalafmt version (which I'll describe in a future PR). However, bumping to [Scalafmt 3.8.3](org.scalameta:scalafmt-core_2.13:3.8.3) produced:
```txt
$ bazel test //test/scalafmt/...
INFO: Analyzed 9 targets (80 packages loaded, 3307 targets configured).
ERROR: .../test/scalafmt/BUILD:43:20: ScalaFmt
test/scalafmt/test/scalafmt/formatted/formatted-test.scala.fmt.output
failed: Worker process did not return a WorkResponse:
---8<---8<--- Start of log, file at .../bazel-workers/worker-134-ScalaFmt.log ---8<---8<--- …
```
> Bump to com.google.protobuf:protobuf-java:4.28.2

- test/shell/test_coverage_equals_in_target.sh
- test/shell/test_coverage_scalatest.sh
- test/shell/test_coverage_scalatest_resources.sh
- test/shell/test_coverage_specs2_with_junit.sh
- test/shell/test_helper.sh
- test/shell/test_scala_config.sh
- test/shell/test_scala_library.sh
- test/shell/test_semanticdb.sh
- test/shell/test_strict_dependency.sh
- test_version.sh
- test_version/WORKSPACE.template
These are mostly small changes to make test assertions more flexible between `WORKSPACE` and Bzlmod runs.
For Bzlmod runs:
- Fixed `test_scala_config_content` from `test_scala_config.sh` by changing a path from `external/io_bazel_rules_scala_config` to `external/*io_bazel_rules_scala_config`.
- Fixed a number of tests by updating expected output messages to allow them to start with either `@//` or `@@//`.
- Fixed `test_stamped_target_label_loading` from `test/shell/test_strict_dependency.sh` by accommodating the canonical `io_bazel_rules_scala_guava` repo name. Also allows for the optional current Scala version suffix.
Also made these other important changes:
- Updated all the assertions in `test_helper.sh` to use Bash builtin regex matching via `_expect_failure_with_messages` instead of …
> Update test scripts for Bzlmod compatibility

- WORKSPACE
- dt_patches/test_dt_patches/WORKSPACE
- dt_patches/test_dt_patches_user_srcjar/WORKSPACE
- examples/crossbuild/WORKSPACE
- examples/scala3/WORKSPACE
- examples/semanticdb/WORKSPACE
- examples/testing/multi_frameworks_toolchain/WORKSPACE
- examples/testing/scalatest_repositories/WORKSPACE
- examples/testing/specs2_junit_repositories/WORKSPACE
- scala/private/macros/scala_repositories.bzl
- test_cross_build/WORKSPACE
- test_version/WORKSPACE.template
- third_party/test/example_external_workspace/WORKSPACE
- third_party/test/proto/WORKSPACE
Updates the build to depend on rules_proto 6.0.2, and the now separate protobuf v21.7.
Part of #1482.
As explained in the 6.0.0 release notes, rules_proto 6.x no longer depends directly on com_google_protobuf, so we need to import it separately. We're keeping the Protobuf version as 21.7 for now, because Protobuf 22.x requires C++14 at a minimum, which Bazel 6.x doesn't support by default:
- https://protobuf.dev/news/v22/#c11-support
- https://github.com/protocolbuffers/protobuf/releases/tag/v22.0
The downside is that, unline rules_proto-5.3.0-21.7, we now end up building (and occasionally rebuilding) `protoc` as part of our build.
This is in preparation for adding a `MODULE.bazel` file, which will bring in dependencies that use rules_proto 6.x. This change avoids that warning, and …
> Bump to rules_proto 6.0.2, separate protobuf 21.7

- scala/scalafmt/scalafmt_repositories.bzl
Replaces `native.new_local_repository` in `scalafmt_default_config` with the new `scalafmt_config` repo rule. Also updates the `native.register_toolchains` call with a stringified `Label` to remove the hardcoding of `@io_bazel_rules_scala`.
Resolves an incompatibility between Bazel 6.5.0 and 7.3.2, while creating a much smaller `@scalafmt_default` repo. The problem is that under Bazel 7.3.2, calling `scalafmt_default_config` from a module extension produces this error:
```txt
$ bazel test //test/scalafmt/...
ERROR: Traceback (most recent call last):
File ".../scala/extensions/deps.bzl",
line 218, column 32, in _scala_deps_impl
scalafmt_default_config()
File ".../scala/scalafmt/scalafmt_repositories.bzl",
line 18, column 32, in scalafmt_default_config
native.new_local_repository(
Error in …
```
> Use custom repo rule to generate @scalafmt_default

- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer3/DependencyAnalyzer.scala
Avoids a future Scala 3.5 compatibility issue under Bzlmod. Part of #1482.
PR #1604 added Scala 3.5 suppport. I updated [my Bzlmod working branch](https://github.com/mbland/rules_scala/commits/bzlmod/) to include those changes, and updated `scala_3_5.bzl` with dependencies I'd added or updated from `scala_3_4.bzl`. `./test_examples.sh` then failed with the following error, which I recreated in the local `examples/scala3` repo:
```txt
$ bazel build --repo_env=SCALA_VERSION=3.5.0 //...
ERROR: .../external/rules_scala~/third_party/dependency_analyzer/src/main/BUILD:4:39:
scala @@rules_scala~//third_party/dependency_analyzer/src/main:dependency_analyzer
failed: (Exit 1): scalac_bootstrap failed:
error executing Scalac command
(from target …
```
> Update dependencyanalyzer3 for Scala 3.5

- scala/private/macros/bzlmod.bzl
- scala/private/phases/phase_dependency.bzl
- scala/private/resources.bzl
- scala/scala_maven_import_external.bzl
- scala/scala_toolchain.bzl
- test/src/main/scala/scalarules/test/resources/ScalaLibResourcesFromExternalDepTest.scala
- test/src/main/scala/scalarules/test/resources/ScalaLibResourcesFromExternalScalaTest.scala
- third_party/repositories/repositories.bzl
Fixes various repository name related errors when building under Bzlmod, while remaining backwards compatible with `WORKSPACE`. See the first commit message for details on the problems solved by this change.
This change also includes a couple of other minor touch-ups:
- Updated the `runtime_deps` attribute in `repositories()` to add the Scala version suffix, just like `deps`.
- Added a `fail()` message to `repositories()` to make it more clear which Scala version dictionary is missing an artifact.
- Removed unnecessary internal uses of the `@io_bazel_rules_scala` repo name, applying `Label()` where necessary.
- Updated the construction of `dep_providers` in `_default_dep_providers` to remove the repo name, reduce duplication, and make the upcoming toolchain update slightly cleaner.
Part …
> Update repo name handling for Bzlmod compatibility

- test/src/main/scala/scalarules/test/extra_protobuf_generator/ExtraProtobufGenerator.scala
Added a `catch` case for `Throwable` in `handleCodeGeneratorRequest`. Part of #1482.
Not catching this caused `ProtoScalaPBRule` workers to hang when building `//test/...` after bumping `com_google_protobuf` from 25.5 to 27.5. With this change, we can now see the error:
```txt
$ USE_BAZEL_VERSION=7.3.2 bazel build //test/...
ERROR: .../test/proto/BUILD:165:14:
ProtoScalaPBRule test/proto/standalone_proto_strip_import_prefix_package_jvm_extra_protobuf_generator_scalapb.srcjar
failed: (Exit 1): scalapb_worker failed:
error executing ProtoScalaPBRule command
(from target //test/proto:standalone_proto_strip_import_prefix_package)
bazel-bin/src/scala/scripts/scalapb_worker
... (remaining 2 arguments skipped)
--jvm_extra_protobuf_generator_out: java.lang.NoSuchMethodError:
'java.lang.Object …
```
> Catch Throwable in ExtraProtobufGenerator

- scala/private/macros/scala_repositories.bzl
- third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/compiler/BUILD
Contains aliases to versioned Scala compiler source repository targets. Part of #1482.
Updates the version specific repo references in the srcs attribute of `//third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/compiler:dep_reporting_compiler`. Now these are references to versioned targets in
`@scala_compiler_sources//`, which are aliases to those versioned compiler source repos.
In a Bzlmod world, this enables `rules_scala` to import only the `scala_compiler_sources` repo in `MODULE.bazel`, instead of importing each individual versioned compiler source repo.
This then allows `rules_scala` clients to set multiple `SCALA_VERSIONS` without requiring them to import this repo or any versioned compiler source repo. The Bzlmodifcation of the test repos under …
> Create the `@scala_compiler_sources` repo

- .scalafmt.conf
- scala/private/macros/scala_repositories.bzl
- scala/scalafmt/BUILD
- scala/scalafmt/scalafmt/ScalafmtAdapter-2_11.scala
- scala/scalafmt/scalafmt/ScalafmtAdapter.scala
- scala/scalafmt/scalafmt/ScalafmtWorker.scala
- scala/scalafmt/scalafmt_repositories.bzl
- scala/scalafmt/toolchain/setup_scalafmt_toolchain.bzl
- test/scalafmt/.scalafmt.conf
- test_cross_build/scalafmt/.scalafmt2.conf
- test_cross_build/scalafmt/.scalafmt3.conf
- test_cross_build/scalafmt/BUILD
- third_party/repositories/scala_2_12.bzl
- third_party/repositories/scala_2_13.bzl
- third_party/repositories/scala_3_1.bzl
- third_party/repositories/scala_3_2.bzl
- third_party/repositories/scala_3_3.bzl
- third_party/repositories/scala_3_4.bzl
- third_party/repositories/scala_3_5.bzl
Ensures that all Scalafmt targets succeed under every supported Scala version. Part of #1482.
Scala 2.11 remains on Scalafmt 2.7.5, since there's not a more recent compatible version.
Between 3.0.0 and 3.8.3, Scalafmt's `FileOps` moved packages, `Config.fromHoconFile` moved to `ScalafmtConfig`, and the methods now take a `java.nio.file.Path` parameter. As a result, this required extracting a thin `ScalafmtAdapter` object, with one implementation for Scala 2.11 and Scalafmt 2.7.5, and one for Scalafmt 3.8.3.
This change also adds the file path to the `Scalafmt.format()` call, allowing error messages to show the actual file path instead of `<input>`.
Removed the `verticalMultiline.newlineBeforeImplicitKW = true` and `unindentTopLevelOperators = false` options from `.scalafmt.conf`. They …
> Update to Scalafmt 3.8.3

- dt_patches/dt_patch_test.sh
- src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/BUILD
- src/java/io/bazel/rulesscala/scalac/reporter/BUILD
Updates targets broken under the Scala 2.13.0 test. Also removes the redundant 2.12.1 test, and cleans the `test_dt_patches_user_srcjar` repo before the `test_compiler_srcjar{,_nonhermetic}` tests. Part of #1482.
This fix and the `.bazelversion` sync from #1629 can land in either order. Both are required for `dt_patches/dt_patch_test.sh` to be fully functional.
The equivalent standalone command in `dt_patches/test_dt_patches` produced the error:
```txt
$ bazel build //... --repo_env=SCALA_VERSION=2.13.0 //...
ERROR: .../rules_scala~/src/java/io/bazel/rulesscala/scalac/reporter/BUILD:5:13:
Building external/rules_scala~/src/java/io/bazel/rulesscala/scalac/reporter/libreporter.jar
(2 source files) [for tool] failed: (Exit 1): java failed:
error executing Javac command
(from target …
```
> Fix `dt_patches/dt_patch_test.sh` for Scala 2.13.0

- test/src/main/scala/scalarules/test/extra_protobuf_generator/ExtraProtobufGenerator.scala
This catches errors that happen at any point in `ExtraProtobufGenerator.run`, not just within `handleCodeGeneratorRequest`. This, in turn, prevents more cases of `ProtoScalaPBRule` aspect workers hanging. Part of #1482.
As I started [experimenting with updating gRPC and ScalaPB libs](https://github.com/mbland/rules_scala/commits/bzlmod-update-protocbridge-and-grpc/), I bumped the ScalaPB libs to 1.0.0-alpha.1 to try to resolve a problem. The `ProtoScalaPBRule` workers then started hanging again.
After pulling the `catch ... Throwable` block from #1630 up into `ExtraProtobufGenerator.run`, I got the following stack trace:
```txt
$ bazel build //test/proto/...
ERROR: .../external/com_google_protobuf/BUILD.bazel:334:14:
ProtoScalaPBRule …
```
> Move Throwable catch to ExtraProtobufGenerator.run

- scala/private/rules/scala_binary.bzl
- scala/private/rules/scala_junit_test.bzl
- scala/private/rules/scala_library.bzl
- scala/private/rules/scala_repl.bzl
- scala/private/rules/scala_test.bzl
- scala/scala_import.bzl
- test/aspect/A.scala
- test/aspect/B.scala
- test/aspect/BUILD
- test/aspect/javainfo_from_aspect_test.bzl
Made most scala_xxxx rules declare that they provide JavaInfo (setting the "provides" attribute).
This allows these targets to be visited by aspects that use "required_providers=[JavaInfo]". 
This matches behavior in java_xxx rules, and goal was to address all the equivelant scala_xxx rules.
rules updated are: scala_import, scala_library, scala_binary, scala_test, scala_junit_test, scala_proto, and scala_repl. (scala_proto_library was already correct).
Allows scala_xxx rules to be visited by aspects that use "required_providers=[JavaInfo]"
> Make scala_xxx rules declare that they provide JavaInfo

- scala/private/phases/phase_runfiles.bzl
- scala/private/phases/phase_write_executable.bzl
- src/java/io/bazel/rulesscala/scala_test/Runner.java
Changed so that paths passed to the Test Runner are in "rlocationpath" form. This should be more correct way to handle these paths as that is what rlocation() expects.  
This fixes issue where we couldn't test external repo tests on Windows. 
Note: seems to have been chasing this issue in the past (#1598. #1500), hopefully this solves for good.
Handle paths in more robust way. And run scalatests from external repos on windows again.
> Pass rlocationpaths to Test Runner

- test/shell/test_cross_build.sh
- test/shell/test_runner.sh
- test/shell/test_scalafmt_helper.sh
Cleans up some of the formatting of `test/shell/test_{runner,scalafmt_helper}.sh` and adds the `RULES_SCALA_TEST_{ONLY,VERBOSE}` environment variables. Improves `test_cross_build.sh` performance signficantly.
Defining `RULES_SCALA_TEST_ONLY`will cause only one specific test case to run, with full Bazel output. This is helpful for pinpointing and working on a specific test without hunting for it or recreating its commands.
Defining `RULES_SCALA_TEST_VERBOSE` will cause all tests to emit full Bazel output. This is more useful when running all the tests from a specific script from `test/shell/test_*.sh`.
The `test_cross_build.sh` changes speed up its tests substantially, particularly between runs. Here are the times for two runs before this change; the first is after running `bazel clean` …
> Clean `test_{runner,scalafmt_helper}`, add diagnostic env vars, and improve `test_cross_build` performance

- WORKSPACE
- dt_patches/test_dt_patches/WORKSPACE
- dt_patches/test_dt_patches_user_srcjar/WORKSPACE
- examples/crossbuild/WORKSPACE
- examples/scala3/WORKSPACE
- examples/semanticdb/WORKSPACE
- examples/testing/multi_frameworks_toolchain/WORKSPACE
- examples/testing/scalatest_repositories/WORKSPACE
- examples/testing/specs2_junit_repositories/WORKSPACE
- jmh/jmh.bzl
- scala/BUILD
- scala/private/extensions/toolchains.bzl
- scala/private/macros/scala_repositories.bzl
- scala/private/macros/setup_scala_toolchain.bzl
- scala/private/macros/toolchains.bzl
- scala/private/macros/toolchains_repo.bzl
- scala/scala.bzl
- scala/scala_cross_version.bzl
- scala/scala_toolchain.bzl
- scala/toolchains.bzl
- test/shell/test_scala_binary.sh
- test/shell/test_scala_proto_library.sh
- test/toolchains/BUILD.bazel
- test_cross_build/WORKSPACE
- test_expect_failure/plus_one_deps/BUILD.bazel
- test_version/WORKSPACE.template
- third_party/test/example_external_workspace/WORKSPACE
- third_party/test/proto/WORKSPACE
Moves the `toolchain` targets for `//scala:toolchain_type` to a new `@io_bazel_rules_scala_toolchains` repository as a step towards Bzlmodification. Part of #1482.
Instantiating toolchains in their own repository enables module extensions to define the the repositories required by those toolchains within the extension's own namespace. Bzlmod users can then register the toolchains from this repository without having to import all the toolchains' dependencies into their own namespace via `use_repo()`.
---
The `scala_toolchains_repo()` macro wraps the underlying repository rule and assigns it the standard name `io_bazel_rules_scala_toolchains`. Right now it's only instantiating the main Scala toolchain via the default `scala = True` parameter. Future changes will expand this macro and …
> Toolchainize //scala:toolchain_type

- .bazelci/presubmit.yml
- test/src/main/scala/scalarules/test/duplicated_resources/child/ScalaLibResourcesDuplicatedTest.scala
- test/src/main/scala/scalarules/test/resources/ScalaLibResourcesFromExternalDepTest.scala
- test/src/main/scala/scalarules/test/resources/ScalaLibResourcesFromExternalScalaTest.scala
Apparently windows CI hasn't been running for a long time (or ever?)
The issue seems to be that for windows, buildkite needs "batch_commands" instead of "shell_commands".
(Update)
Also made minor fixes to tests regarding line endings. _I originally (#1529) had the system work with autocrlf=true, but this isn't handled by BazelCI. And after thinking bout it, its probably best to keep autocrlf=false, since that is what is distributed to users.. even windows users._ 
Make windows CI work so we don't accidently break windows support.
> Fix windows Buildkit CI 

- .bazelci/presubmit.yml
Replaces the `latest` Bazel version specifier with `7.x`. Part of #1625 and #1652.
- https://github.com/bazelbuild/bazelisk?tab=readme-ov-file#how-does-bazelisk-know-which-bazel-version-to-run
This fixes CI builds because Bazel 8.0.0 just came out, but `rules_scala` is not yet Bazel 8 compatible, causing `latest Bazel` builds to fail.
> Set latest Bazel build to 7.x after 8.0.0 release

- WORKSPACE
- scala/scalafmt/BUILD
- scala/scalafmt/phase_scalafmt_ext.bzl
- scala/scalafmt/scalafmt_repositories.bzl
- scala/scalafmt/toolchain/setup_scalafmt_toolchain.bzl
- scala/scalafmt/toolchain/toolchain.bzl
- scala/toolchains.bzl
- scala/toolchains_repo.bzl
- test/shell/test_scala_library.sh
- test/shell/test_strict_dependency.sh
- test/shell/test_unused_dependency.sh
- test_cross_build/WORKSPACE
- test_reproducibility.sh
- third_party/dependency_analyzer/src/test/analyzer_test.bzl
Mostly a pretty straightforward and easy update on top of the previous `setup_toolchains` and `scala_toolchains_repo` changes. Part of #1482.
However, it also includes a few opportunistic changes:
- Updates `test_reproducibility.sh` to replace the nonexistent `//test/coverage/...` target with packages that
actually exist, rendering the test more meaningful.
- Adds the `SCALAFMT_TOOLCHAIN_TYPE` constant to reduce string duplication.
- Removes the `dep_providers` default from `scala_toolchain`, since it's the _only_ attribute, so it doesn't make sense to have a default (inspired by #1675).
- Tweaks a few tests to ensure they still pass under Bazel 6 and Bzlmod.
- Updates `//third_party` tests to replace `$(location)` with `$(rootpath)`, ensuring they still pass under Bazel 8 (#1652).
See …
> Toolchainize //scala/scalafmt:scalafmt_toolchain

- dt_patches/dt_patch_test.sh
- dt_patches/test_dt_patches_user_srcjar/WORKSPACE
- examples/scala3/WORKSPACE
- scala/private/macros/scala_repositories.bzl
- scripts/create_repository.py
- test/shell/test_examples.sh
- test_thirdparty_version.sh
- third_party/repositories/scala_3_1.bzl
- third_party/repositories/scala_3_2.bzl
- third_party/repositories/scala_3_3.bzl
- third_party/repositories/scala_3_4.bzl
- third_party/repositories/scala_3_5.bzl
- third_party/repositories/scala_3_6.bzl
Upgrades Scala 3.6.2 -> 3.6.3
Scala 3.6.3 switched using jline-terminal-jna with  jline-terminal-jni for REPL - these change required updated repositories for other Scala versions. 
https://github.com/scala/scala3/issues/22375
> Upgrade Scala 3.6 to 3.6.3

- src/java/io/bazel/rulesscala/scalac/ScalacWorker.java
- src/java/io/bazel/rulesscala/scalac/scala_2/ScalacInvoker.java
- test/macros/BUILD
- test/macros/IdentityMacro.scala
- test/macros/MacroUser.scala
- test/shell/test_macros.sh
This PR should fix https://github.com/bazelbuild/rules_scala/issues/366. Now, when `scala_library` is mistakenly used in place of `scala_macro_library`, the following exception is thrown:
```
error: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file macros/IdentityMacro$
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
at …
```
> Throw a more informative error when scala_macro_library isn't used

- WORKSPACE
- scala/private/toolchain_deps/toolchain_dep_rules.bzl
- scala/toolchains.bzl
- scala/toolchains_repo.bzl
- scala_proto/BUILD
- scala_proto/default/default_deps.bzl
- scala_proto/private/scala_proto_aspect.bzl
- scala_proto/private/toolchain_deps.bzl
- scala_proto/scala_proto_toolchain.bzl
- scala_proto/toolchains.bzl
- test/proto/custom_generator/BUILD.bazel
- test_version/WORKSPACE.template
- third_party/test/proto/WORKSPACE
Adds scala_proto toolchains to `scala_toolchains()`. Part of #1482.
The most significant part of the change is moving all the toolchain rules from `scala_proto/BUILD` to `setup_scala_toolchains()` in `scala_proto/toolchains.bzl`.
Adds the `scala_proto_deps_providers()` macro to replace `//scala_proto:scalapb_{compile,grpc,worker}_deps_provider` targets in the `dep_providers` parameter of `scala_proto_deps_toolchain()`. Examples of this are in `test/proto/custom_generator/BUILD`.
Excludes `@scala_proto_rules_scalapb_protoc_gen` from `DEFAULT_SCALAPB_WORKER_DEPS` in `scala_proto/default/default_deps.bzl` for Scala 2.11. For other Scala versions, this repo name will have the Scala version appended. 
A lot of the other changes are more opportunistic removals of `@io_bazel_rules_scala` label …
> Toolchainize //scala_proto:{,deps_}toolchain_type

- WORKSPACE
- jmh/BUILD
- jmh/jmh.bzl
- jmh/toolchain/toolchain.bzl
- scala/toolchains.bzl
- scala/toolchains_repo.bzl
Adds the jmh toolchain to `scala_toolchains()` and moves `jmh_repositories()` to `jmh/toolchain/toolchain.bzl` for `rules_java` 8 compatibility. Part of #1482 and #1652.
This is the next step in the toolchainization of the frameworks used to implement various rules, as required to implement Bzlmod support.
> Toolchainize //jmh/toolchain:jmh_toolchain_type

- src/java/io/bazel/rulesscala/scalac/BUILD
- src/java/io/bazel/rulesscala/scalac/definitions.bzl
I'd like to remove Scala compiler extensions from the Scala toolchain, that I could be potentially building myself (in the same monorepo, build the compiler extension, but also use it).
Till now the only way to add Scala compiler dependencies was a toolchain.
If I left the compiler extension as a toolchain dependency there, I could not build the compiler extension due to a cycle in deps (building the compiler extension would depend on itself through the toolchain).
I'd like to work this around by defining my own scalac java_binary target, where I can define my own dependencies (and then create rule names with macros that override the scalac target).
To do this without duplicating code from rules_scala, refactor SCALAC_DEPS parameter and scalac target definitions to a Starlark file to make …
> refactor scalac java_binary target creation

- WORKSPACE
- scala/toolchains.bzl
- scala/toolchains_repo.bzl
- test_version.sh
- test_version/WORKSPACE.template
- test_version/version_specific_tests_dir/scrooge_repositories.bzl
- test_version/version_specific_tests_dir/twitter_scrooge/BUILD
- twitter_scrooge/BUILD
- twitter_scrooge/toolchain/toolchain.bzl
- twitter_scrooge/twitter_scrooge.bzl
Adds `twitter_scrooge` to `scala_toolchains()`. Part of #1482 and #1652.
This is the last of the toolchains to receive the "toolchainization" treatment prior to Bzlmodification, and moves `twitter_scrooge()` to `twitter_scrooge/toolchain/toolchain.bzl` for `rules_java` 8 compatibility.
> Toolchainize twitter_scrooge

- scala_proto/private/scala_proto.bzl
- test/proto/BUILD
- test/proto/default_outputs_test.bzl
scala_proto_library returns too many outputs via DefaultInfo files
It returns all transitive jars used for compilation while it should return
pair of srcjar and compile jar for each direct proto_library dependency
Test `standalone_scala_proto_outs_test` failure before change:
```
In test _default_outputs_test from //test/proto:default_outputs_test.bzl: 
Expected "["standalone_proto_scalapb-src.jar", "standalone_proto_scalapb.jar"]", but got 
"["disruptor-3.4.2.jar", "fastparse_2.12-2.1.3.jar", "grpc-api-1.70.0.jar", "grpc-context-1.70.0.jar", "grpc-core-1.70.0.jar", "grpc-netty-1.70.0.jar", "grpc-protobuf-1.70.0.jar", "grpc-stub-1.70.0.jar", "guava-33.4.0-jre.jar", "instrumentation-api-0.3.0.jar", "lenses_2.12-0.11.17.jar", "libcore.jar", "liblite_runtime_only.jar", …
```
> Fix scala_proto_library default outputs

- .scalafmt.conf
- scala/scalafmt/scalafmt/ScalafmtAdapter.scala
- scala/scalafmt/scalafmt_repositories.bzl
- scripts/create_repository.py
- test/scalafmt/.scalafmt.conf
- test_cross_build/scalafmt/.scalafmt2.conf
- test_cross_build/scalafmt/.scalafmt3.conf
- third_party/repositories/scala_2_12.bzl
- third_party/repositories/scala_2_13.bzl
- third_party/repositories/scala_3_1.bzl
- third_party/repositories/scala_3_2.bzl
- third_party/repositories/scala_3_3.bzl
- third_party/repositories/scala_3_4.bzl
- third_party/repositories/scala_3_5.bzl
- third_party/repositories/scala_3_6.bzl
Also updates `scripts/create_repository.py` to prevent `scala-collection-compat` versions from flipping on subsequent runs by no longer comparing Scala versions. Part of #1482.
Both Scalafmt and ScalaPB depend on
`org_scala_lang_modules_scala_collection_compat`. Before removing the Scala version comparison, subsequent `create_repository.py` runs would flip between these two artifacts for Scala 3.3 through 3.6:
- `org.scala-lang.modules:scala-collection-compat_2.13:2.13.0`
- `org.scala-lang.modules:scala-collection-compat_3:2.12.0`
The artifact with the higher release version number is preferable to the artifact with the higher Scala version.
The change from `FileOps` to `PlatformFileOps` in `ScalafmtAdapter` is a consequence of an update first included in Scalafmt 3.9.0:
- …
> Bump Scalafmt from 3.8.6 to 3.9.1

- scala/private/phases/phase_coverage.bzl
- scala/private/phases/phase_scalafmt.bzl
- scala/private/phases/phase_write_executable.bzl
- scala/private/rule_impls.bzl
- scala_proto/private/scala_proto_aspect.bzl
- src/java/io/bazel/rulesscala/worker/Worker.java
- src/java/io/bazel/rulesscala/worker/WorkerTest.java
- tools/BUILD
- twitter_scrooge/twitter_scrooge.bzl
The SecurityManager is a hollow shell that just throws exceptions in Java 24. We should avoid calling it. This will make tests that call System.exit crash the worker.
Bazel is doing the same thing for now, see
https://github.com/bazelbuild/bazel/issues/24354
It is often possible to edit code to avoid calling System.exit, and guarding against it requires more effort in Java 24+, likely involving attaching an agent. Until someone actually has that need, it doesn't seem worth doing.
> Add Java 24 compatibility

- src/java/io/bazel/rulesscala/worker/WorkerTest.java
WorkerTest was failing after https://github.com/bazelbuild/rules_scala/pull/1719
> Cleanup WorkerTest after SecurityManager was removed

- README.md
- docs/scala_proto_library.md
- scala/toolchains.bzl
- scala/toolchains_repo.bzl
- scala_proto/default/default_deps.bzl
- scala_proto/private/scala_proto_aspect.bzl
- scala_proto/scala_proto_toolchain.bzl
- scala_proto/toolchains.bzl
- test/proto/BUILD
- test/proto/custom_generator/BUILD.bazel
- test_expect_failure/missing_direct_deps/scala_proto_deps/BUILD
- test_version/WORKSPACE.template
Hello,
Over a year ago I had the experience of porting a project from sbt to rules_scala. One of the quirks of such a migration was protobuf. That time I've used `rules_proto_grpc` to overcome this part but I thought it should be possible with built-in proto toolchain from `rules_scala`. Now I finally had some time to take this journey and check it. Here are the results:
1. `proto_enable_all_options` removed - I think that user should define the options. This `all` seems to be a bit out of date, e.g. `scala3_sources` was not included there.
2. `grpc` dep id removed - Similar to above. The code that was merging compile deps was checking `with_grpc` flag that also got removed. I took an approach that here, as well, user knows what he wants so if `grpc` flag was added to the toolchain …
> feat: bit more configurable proto toolchain

- src/java/io/bazel/rulesscala/worker/WorkerTest.java
- test_rules_scala.sh
Adds `src/...` to the `bazel build` and `bazel test` commands in `test_rules_scala.sh` to follow up on #1719 and #1721.
Also includes:
- Adding `--test_output=errors` to each `bazel test` invocation to make failure messages visible in the CI logs.
- Joining the `contents` lines in `WorkerTest.testPersistentWorkerArgsfile` using the `line.separator` system property to fix a test failure on Windows.
- Swapping the arguments of `assertEquals()` assertions to `expected, actual` instead of `actual, expected` to fit the assertion failure messages.
After adding `src/...` to the `bazel test` commands in `test_rules_scala.sh` the first time, the Windows build failed with:
- https://buildkite.com/bazel/rules-scala-scala/builds/5511#0195e775-498c-4ae5-b308-34cc70da65c4/75-257
```txt …
```
> Add src/... to test_rules_scala, fix Windows break

- BUILD
- MODULE.bazel
- docs/phase_scalafmt.md
- scala/extensions/deps.bzl
- scala/scalafmt/phase_scalafmt_ext.bzl
- scala/scalafmt/scalafmt_repositories.bzl
- scala/toolchains.bzl
- scala/toolchains_repo.bzl
Removes the `scalafmt_config()` macro and replaces it with the new `@rules_scala_toolchains//scalafmt:config` target. Part of #1482.
The new `test/shell/test_dependency_versions.sh` test found a problem with the previous implementation. The `dev_deps` extension in `MODULE.bazel` generated `@scalafmt_default`, leaving it invisible to `rules_scala` when it's not the main module:
```txt
ERROR: no such package
'@@[unknown repo 'scalafmt_default' requested from @@rules_scala~]//':
The repository
'@@[unknown repo 'scalafmt_default' requested from @@rules_scala~]'
could not be resolved:
No repository visible as '@scalafmt_default'
from repository '@@rules_scala~'
ERROR: .../tmp/test_dependency_versions/BUILD:52:20:
every rule of type scalafmt_scala_test
implicitly depends upon the target …
```
> Replace `@scalafmt_default` with toolchains target

- .bcr/README.md
- .github/workflows/publish-to-bcr.yml
- .github/workflows/release.yml
Updates `.github/workflows/release.yml` and adds `publish-to-bcr.yml` for publishing to the Bazel Central Registry. Part of #1482 (originally broken out from #1722).
`release.yml` now uses the `release_ruleset` workflow from `bazel-contrib/.github`, which does everything `release.yml` did previously and adds SLSA provenance attestations. `release.yml` then invokes the new `publish-to-bcr.yml` workflow after publishing a successful release to GitHub.
Requires that the `BCR_PUBLISH_TOKEN` GitHub secret and the `registry_fork` specified in `.github/workflows/publish-to-bcr.yml` are in place.
See `.bcr/README.md` for all the details and references.
This will enable automated publishing to https://registry.bazel.build/.
> Use the Publish to BCR reusable GitHub workflow

- BUILD
- MODULE.bazel
- README.md
- docs/phase_scalafmt.md
- docs/scala_proto_library.md
- scala/extensions/deps.bzl
- scala/private/toolchain_defaults.bzl
- scala/scalafmt/toolchain/setup_scalafmt_toolchain.bzl
- scala/toolchains.bzl
- scala/toolchains_repo.bzl
- scala_proto/toolchains.bzl
- test_version/MODULE.bazel.template
- test_version/WORKSPACE.template
- test_version/scrooge_repositories.bzl
- twitter_scrooge/toolchain/toolchain.bzl
Updates `scala_toolchains()` to accept either boolean or dict arguments for specific toolchains, and updates `//scala/extensions:deps.bzl` to generate them from tag classes. Part of #1482.
Notable qualities:
- Adds toolchain options support to the `scala_toolchains()` parameters `scalafmt`, `scala_proto`, and `twitter_scrooge`, and to the `scalafmt` tag class.
- Eliminates the `scalafmt_default_config`, `scala_proto_options`, and `twitter_scrooge_deps` option parameters from `scala_toolchains()`.
- Provides uniform, strict evaluation and validation of toolchain options passed to `scala_toolchains()`.
- Configures enabled toolchains using root module settings or the default toolchain settings only.
- Introduces the shared `TOOLCHAIN_DEFAULTS` dict in …
> Add toolchain options API to WORKSPACE and Bzlmod

- docs/phase_scalafmt.md
Makes it clear that `WORKSPACE` users must use a target `Label` string with the `default_config` option for the `scalafmt` argument of `scala_toolchains`. Notes that the specified config file must exist within a package, including but not limited to having a `BUILD` file in the repository root.
@gergelyfabian noticed this while building gergelyfabian/bazel-scala-example after #1730 landed.
This isn't fixable in code. With this call:
```py
scala_toolchains(
scalafmt = {"default_config": ".scalafmt.conf"},
)
```
- `scala_toolchains` looks for the file under `external/.scalafmt.conf`.
- Updating `scala_toolchains` to wrap `default_config` in a `Label` makes it relative to `@rules_scala//scala`. This because `scala_toolchains` resides in `@rules_scala//scala:toolchains.bzl`.
- …
> Fix Scalafmt `default_config` docs for `WORKSPACE`

- MODULE.bazel
- dt_patches/dt_patch_test.sh
- dt_patches/test_dt_patches_user_srcjar/MODULE.bazel
- dt_patches/test_dt_patches_user_srcjar/WORKSPACE
- examples/scala3/WORKSPACE
- scripts/README.md
- scripts/create_repository.py
- test/shell/test_examples.sh
- test_thirdparty_version.sh
- third_party/repositories/scala_3_7.bzl
Upgrades Scala 3.7 to latest patch version
https://github.com/scala/scala3/issues/23301
> Upgrade Scala versions 3.7.0 -> 3.7.1

- scala/private/rules/scala_doc.bzl
- test/shell/test_macros.sh
Add a guard for `deps` existing in `ctx.rules.attr` when generating `scala_docs`.
As a side note: Would the maintainers be interested in a `scala_export` rule in `rules_scala`? I [implemented](https://github.com/confluentinc/rules_jvm_external/blob/master/private/rules/scala_export.bzl) this in our rules_jvm_external fork but it won't be [upstreamed](https://github.com/bazel-contrib/rules_jvm_external/pull/1257#issuecomment-2428908599).
It's possible to for `ctx.rules.attr` to not have `deps`. Specifically, I ran into a failure generating `scala_docs` when a `maven_project_jar` is in the deps of the `scala_library`.
> Check for 'deps' attr in scala_doc rule

- MODULE.bazel
- dt_patches/dt_patch_test.sh
- dt_patches/test_dt_patches_user_srcjar/MODULE.bazel
- dt_patches/test_dt_patches_user_srcjar/WORKSPACE
- examples/scala3/WORKSPACE
- scala/private/macros/compiler_sources_integrity.bzl
- scripts/README.md
- scripts/create_repository.py
- scripts/update_compiler_sources_integrity.py
- src/java/io/bazel/rulesscala/scalac/reporter/BUILD
- src/java/io/bazel/rulesscala/scalac/reporter/since_3_3_before_3_7_2/CompilerCompat.java
- src/java/io/bazel/rulesscala/scalac/reporter/since_3_7_2/CompilerCompat.java
- test/shell/test_examples.sh
- test_thirdparty_version.sh
- third_party/repositories/scala_3_7.bzl
Upgrades Scala 3.7.1 to 3.7.2
https://github.com/scala/scala3/issues/23625
> Upgrade Scala 3.7 to 3.7.2 (was 3.7.1)

- MODULE.bazel
- examples/crossbuild/protobuf.patch
- scala/latest_deps.bzl
Resolves the Windows symlink breakage from bazelbuild/bazel-central-registry#5490 by replacing `examples/crossbuild/protobuf.patch` with a full copy. Bumps `rules_python` to 1.5.2 for both Bzlmod and legacy WORKSPACE builds.
This is hopefully a temporary measure to unblock the next `rules_scala` release. This will probably require creating a v7.1.1 tag to trigger a new `.bcr/presubmit.yml` workflow.
See bazelbuild/bazel-central-registry#5506 for details about the breakage. If and when bazelbuild/continuous-integration#2350 lands and makes its way to the BCR presubmit build, we could restore the symlink. Better yet, if protocolbuffers/protobuf#19679 ever lands, we could remove this symlink and all the others.
Bumped `rules_python` to 1.5.2 for legacy `WORKSPACE` builds because it contains …
> Fix BCR presubmit, update rules_python to 1.5.2

- protoc/private/toolchain_impl.bzl
Removal of string + label concatenation error when someone do not register rules_scala's PROTOC_TOOLCHAIN_TYPE
-
> fix: string + label concatenation error

- .bazelci/presubmit.yml
- MODULE.bazel
- scala/latest_deps.bzl
Updates the `test_rules_scala_linux_last_green` and the matrixed `bcr_presubmit` jobs to use `soft_fail`. Upgrades `rules_python` from 1.6.0-rc0 to 1.6.0.
Also adds the `{bcr_bazel}` value to matrixed `bcr_presubmit` job names.
It occurred to me that we don't want failing `bcr_presubmit` jobs for Bazel `8.x`, `rolling`, or `last_green` to potentially block pull requests. Breakages under these versions could be due to unrelated upstream Bazel changes, addressable in a separate pull request.
Also, the `test_rules_scala_linux_last_green` build step using `buildkite-agent annotate` doesn't fit the `bcr_presubmit` jobs well. These annotations were also somewhat easy to miss, leading to the `test_rules_scala_linux_last_green` job occasionally remaining broken for some time.
Today I learned …
> soft_fail CI tasks, upgrade to rules_python-1.6.0
