.bazel-installer-linux-x86_64.sh.sha256, .bazelrc.travis, .travis.yml
=> Add Travis CI support

.travis.yml, scala/scala.bzl, test/BUILD, test/src/main/resources/scala/test/byes, test/src/main/scala/scala/test/ScalaLibBinary.scala, test/src/main/scala/scala/test/ScalaLibResources.scala, test_run.sh
=> Fix resources bug

scala/scala.bzl
we don't want large targets for build speed and incrementalism, but for thrift it might happen (and we'd rather be slow than fail).
=> use an arg file for scalac to deal with large targets

scala/scala.bzl, test/BUILD, test_run.sh
closes https://github.com/bazelbuild/rules_scala/issues/18
=> Add skylark macro for import to java

scala/scala.bzl
hit a bug fixed in scala 2.11.8.
Should have bumped already.
=> Bump to scala 2.11.8

README.md, scala/scala.bzl, test/BUILD, test_run.sh
=> Add support for a repl target

README.md
@johnynek I took the liberty of adding another sentence about the prelude since that by itself was another gotcha for me when I started out
=> fixes #60 by clarifying the getting started path

scala/scala.bzl, test/BUILD, test/data/BUILD, test/data/some.txt, test/src/main/scala/scala/test/ScalaLibBinary.scala, test/src/main/scala/scala/test/ScalaLibResources.scala
We hit this internally.
We were not testing one branch of the resources setup code.
=> Add a test and bugfix for a regression in resources

.gitignore, test_run.sh
running md5 if osx, md5sum otherwise, also ignoring hash1/hash2 in git.
decided not to actually wait for #76  and just do the quick win.
WDYT?
=> md5 bash script handling

src/java/io/bazel/rulesscala/scalac/ScalaCInvoker.java, test/src/main/scala/scala/test/mix_java_scala/FooBar.java
This will fix javac compilation issue #112 when multiple java files are present in the src
=> Fix Multiple Java source file compilation

README.md, scala/scala.bzl, test/BUILD, test/DataRoot1.scala, test/DataRoot2.scala, test/HelloLibTest2.scala, test/SuiteUsage.scala
Both test and library meta targets
=> Add in some meta targets

src/scala/io/bazel/rules_scala/scrooge_support/Compiler.scala, src/scala/scripts/BUILD, src/scala/scripts/TwitterScroogeGenerator.scala, twitter_scrooge/twitter_scrooge.bzl
=> Add worker support to Scrooge rules

WORKSPACE, scala/support/BUILD, src/java/io/bazel/rulesscala/io_utils/BUILD, src/java/io/bazel/rulesscala/io_utils/DeleteRecursively.java, src/scala/BUILD, src/scala/io/bazel/rules_scala/tut_support/BUILD, src/scala/io/bazel/rules_scala/tut_support/TutCompiler.scala, src/scala/scripts/BUILD, src/scala/scripts/TwitterScroogeGenerator.scala, test/tut/BUILD, test/tut/SomeExample.md, test/tut/TestDep.scala, tut_rule/tut.bzl
This makes a tut rule allows you to pass a single src and a list of deps, and run tut on it.
review @ianoc ?
cc @tpolecat
=> Add basic tut-support for type-checked docs

src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
=> Capture javac args in a @argfile

README.md
Instead of using git_repository use http_archive which should be more efficient
=> suggested different way to import rules_scala

scala/support/JUnitXmlReporter.scala
=> Don't write XML output if the envvar unset

src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
The method collects sources from SrcJars
=> rename collectMixedScalaSources to collectSrcJarSources

scala/scala.bzl, twitter_scrooge/twitter_scrooge.bzl
=> Use new mirror.bazel.build hostname

scala/scala.bzl, test/src/main/scala/scala/test/resources/BUILD, test/src/main/scala/scala/test/resources/DummyStandAlone.scala, test/src/main/scala/scala/test/resources/resource.txt, test_run.sh
Added tests, made sure it works both on direct files and filegroups
=> fixing #138 | missing resources on no_src scala_library

src/java/io/bazel/rulesscala/test_discovery/DiscoveredTestSuite.scala, test/BUILD, test/src/main/scala/scala/test/junit/JunitIncludesRunWith.scala, test/src/main/scala/scala/test/junit/JunitIncludesTestHierarchies.scala, test/src/main/scala/scala/test/junit/JunitNoTests.scala
test discovery filters classes which match affix without tests, includes classes with @RunWith and test methods in hierarchy
=> test discovery enhancements

.bazelrc.travis
=> Try not using batch mode in bazel

README.md
As subj. updating the version to latest since people usually copy-paste
=> update rules_scala version to latest in readme

.travis.yml
travis stopped working for HEAD. 
This script should fix it.
Warning: the regex is hideous , but that's the only thing that captured all cases (RC/linux/darwin)
=> fixed travis for HEAD

src/scala/scripts/TwitterScroogeGenerator.scala, twitter_scrooge/twitter_scrooge.bzl
First commit fixes #117. Second is for forward compatibility with scrooge, as I use a newer version here.
=> scrooge generator: add an option to enable finagle compilation (fixes #117)

scala/scala.bzl
this aims to fix #277 
@kevingessner any chance you can take this branch out for a manual spin on your repo?
=> wrap full jars in a struct for intellij plugin

.bazelrc.travis
I've heard docker can deal with sandboxing now....
Seeing if we can turn this on.
=> Disable standalone mode on travis

scala_proto/scala_proto.bzl, test/BUILD
=> Allow scala libraries as deps of scalapb_proto_library

test/gen_src/BUILD, test/gen_src/SrcGenerator.scala
These is no reason this shouldn't work, but, I added a test as an example of generating source.
I see no reason to test this other than just building and running the code and it not crashing.
=> Add a test of using genrule with scala rules

test/src/main/scala/scala/test/resources/BUILD, test/src/main/scala/scala/test/resources/DummyStandAlone.scala, test/src/main/scala/scala/test/resources/ScalaLibOnlyResourcesTest.scala
Passing no srcs only resources test
=> No src resources test

src/java/io/bazel/rulesscala/specs2/Specs2RunnerBuilder.scala, test/src/main/scala/scala/test/junit/specs2/Specs2Tests.scala, test_run.sh
=> Handling special (regex) characters and multiple test names in specs2

.travis.yml, scala/scala_import.bzl, test/src/main/scala/scala/test/scala_import/BUILD
Fix a runtime error due to ijar dependendency sneaking in. See #354 for
details.
Fixes #354
=> Fix for scala_import's export/ijar bug

scala_proto/scala_proto.bzl, src/scala/scripts/BUILD, src/scala/scripts/PBGenerateRequest.scala, src/scala/scripts/ScalaPBGenerator.scala
fixes #352 
@johnynek @azymnis would appreciate your review.
We're already using this with our own custom generator
=> generalize scala_proto_srcjar so that it takes flags and generator

README.md
added back paragraph that I mistakingly deleted on #364
=> added back mistakenly deleted paragraph

scala/scala.bzl
When executing non-locally, the wrong version of Java would be used,
referencing a path that didn't exist. This change adds the
_java_runtime attribute to have to locate the java runtime on the
machine where the Scala code is being executed, and selects the
correct configuration for the host_javabase.
As a minor cleanup, this also removes the now no-longer-necessary
_java attribute.
TESTED=Ran unit tests and also ran a custom Scala unit test through:
previously, the Scala unit test failed with an incorrect java path
error, now it passes.
Change-Id: I9c2829bded04ec2d9d014094bd9e72cd984fe6e6
=> Adds the _java_runtime attribute to fix toolchain use in Scala.

src/java/io/bazel/rulesscala/specs2/BUILD, src/java/io/bazel/rulesscala/specs2/Specs2RunnerBuilder.scala, src/java/io/bazel/rulesscala/specs2/package.scala
This adds support when running under specs2 v4
=> Support for specs2 v4

jmh/jmh.bzl
redo #452 to fix #430 piecemeal...
=> Fix bazel deprecations in jmh rules

scala/scala_import.bzl
this is the scala_import portion of #452 to address #430
=> Fix scala_import bazel incompatibilities

.travis.yml
make a bazel_0_10 branch which will hold the current master before we start being more aggressive about removing incompatible bazel features.
=> Use 0.10 in travis

.travis.yml
This is literally the first time I write `.travis.yml` files, so I'm a bit of a noideadog here.
=> Only test with the latest Bazel version on Travis.

src/java/io/bazel/rulesscala/specs2/Specs2RunnerBuilder.scala, src/java/io/bazel/rulesscala/test_discovery/FilteredRunnerBuilder.scala
Additionally, filtering out runners that are not actually run, to reduce the amount of empty entries.
This fixes #231
=> Fixing "null" entry in test.xml with specs2

scala/scala.bzl
These methods don't seem to be used anymore. I haven't tested it locally; just testing via CI.
=> Remove unreferenced private methods

scala/scala.bzl
This is a refactor to get the place where we create our ad-hoc scala provider, which is just a struct with certain data.
This will change to returning a ScalaInfo when we move to providers.
ptal @ittaiz
=> refactor to add a create_scala_provider method

.gitignore, .travis.yml, test_reproducibility.sh, test_rules_scala.sh, tools/bazel.rc
- Enables Bazel's local cache for all development by default
- Sets up Travis to cache the local cache directory across CI builds
=> Enable local cache by default

test_all.sh
This is a quick follow up to #478
=> Update test_all.sh to include test_reproducibility.sh

scala/scala.bzl
Basic cleanup/hygiene. I'll apply similar treatment to other files as I make my way through the code.
=> Privately scope as much as possible in scala.bzl

WORKSPACE, scala/scala_maven_import_external.bzl, third_party/plugin/src/test/BUILD
when user adds a `generated_linkable_rule_name` attribute
=> fix bug in jvm_import_external 

README.md
=> update rules_scala commit in readme

.travis.yml
Let’s see how this goes now that we’ve upgraded protobuf
=> Update Travis to run with Bazel 0.13.0

.bazelrc.travis, .travis.yml, scala/private/rule_impls.bzl, scala/scala.bzl, test_reproducibility.sh, test_rules_scala.sh, thrift/thrift.bzl, tools/bazel.rc, twitter_scrooge/twitter_scrooge.bzl
This will be needed for @johnynek ijar build and it. Also should avoid having to comment out lines in the tools/bazelrc
=> Bump to using min version of 0.14.1

scala/scala.bzl
=> Upgrade to Scala 2.11.12 to support Java 9

scala/private/rule_impls.bzl, test/BUILD, test/JavaUsesScalaStdLib.java
@johnynek I'd appreciate your review
@softprops I'm not sure if there are other issues in #526 remaining after this PR. Do you remember?
=> add scala stdlib to java compile classpath, relates to #526

src/scala/scripts/ScalaPBGenerator.scala
fixes #367 
@azymnis any objections?
=> take version from protoc instead of scalapb config

README.md
Took a while for me to adapt to the new aspect-powered scrooge, but I believe this is correct now I've got it working.
=> add a little bit more docs about scrooge usage

test/tut/BUILD, test_version/version_specific_tests_dir/tut/BUILD
Comment out `tut` dependencies in tests to solve latest issues with `tut` repositories
=> Comment out tut test deps

README.md
Add instructions for the usage of `unused_dependency_checker` to the README
@johnynek
=> Unused dependencies readme

README.md
=> Update rules scala version in docs

WORKSPACE
https://github.com/bazelbuild/rules_scala/issues/600
=> update bazel-toolchains pin

README.md
This may help us find collaborators and share experiences.
ptal @ittaiz
=> Add Adopters to README.md

src/java/io/bazel/rulesscala/test_discovery/DiscoveredTestSuite.scala
=> fix incorrect error message of array

scala/scala_maven_import_external.bzl
=> Add source jar support to Maven import external

scala/scala.bzl
re: https://github.com/bazelbuild/rules_scala/issues/619#issuecomment-424927132
=> Allow injecting versions and shas for scala extra jars

.travis.yml
=> disable the linting test until we can fix it

WORKSPACE
https://github.com/bazelbuild/bazel-toolchains/issues/216
=> Update bazel-toolchains pin.

jmh/jmh.bzl, junit/junit.bzl, private/format.bzl, scala/private/common.bzl, scala/private/rule_impls.bzl, scala/providers.bzl, scala/scala.bzl, scala/scala_cross_version.bzl, scala/scala_import.bzl, scala/scala_maven_import_external.bzl, scala/scala_toolchain.bzl, scala/toolchains.bzl, scala_proto/scala_proto.bzl, specs2/specs2.bzl, specs2/specs2_junit.bzl, src/java/io/bazel/rulesscala/scalac/jvm_export_toolchain.bzl, test/aspect/aspect.bzl, test/check_statsfile.bzl, test/src/main/scala/scalarules/test/large_classpath/helper.bzl, test_expect_failure/missing_direct_deps/internal_deps/custom-jvm-rule.bzl, thrift/thrift.bzl, tut_rule/tut.bzl, twitter_scrooge/twitter_scrooge.bzl
Progress towards #644
This diff is large, because I reformatted all files with Buildifier. This will allow you to use Buildifier automated fixes in the future.
=> Update files for future Bazel changes

scala/private/rule_impls.bzl
For the feature request in: https://github.com/bazelbuild/rules_scala/issues/598
=> Use --compression in _build_deployable

test/jar_lister.py
__print()__ is a function in Python 3.
=> Use print() function in both Python 2 and Python 3

scala/support/JUnitXmlReporter.scala
=> Replace unused pattern vars in JUnitXmlReporter with _

scala/private/rule_impls.bzl, scala/providers.bzl, scala_proto/scala_proto.bzl
This adds building a `-src.jar` in addition to the target jar, so that IntelliJ supports navigating to sources.
=> [WIP] Producing a source jar for build targets

specs2/BUILD, specs2/specs2.bzl, specs2/specs2_junit.bzl
=> Upgrading bundled specs2 to v4.3.5 (from v3.x)

README.md
=> Add Ascend to adopters

src/java/io/bazel/rulesscala/scalac/ScalacProcessor.java
Fix for: https://github.com/bazelbuild/rules_scala/issues/655
=> Fix windows compatability

scala/private/rule_impls.bzl
see https://github.com/bazelbuild/bazel/issues/7186
Fixes #712
=> Prepare for --incompatible_use_toolchain_providers_in_java_common

scala_proto/private/proto_to_scala_src.bzl
Just to ensure this doesn't break any stability for caching
=> sort the list

src/scala/scripts/ScalaPBGenerator.scala
A workaround for #779.
Replacement for #787 given the cla-bot problems.
=> Handle FileAlreadyExistsException in ScalaPBGenerator

.github/PULL_REQUEST_TEMPLATE.md
Adds a GitHub template for PRs (that looks like this PR).
Simplifying the pull request and review process by calling out important information for opening pull requests.
=> Add a basic PR template

.travis.yml, tools/bazel
We might want to move the default over soon. But figure we should just get a sense of the master trunk or new PR's work for 1.0
1.0 got released today
=> Add a test build for bazel 1.0

scala/private/macros/scala_repositories.bzl
Context: https://github.com/bazelbuild/bazel/issues/10270
=> Mirror all http_archives.

.travis.yml, README.md
Should be rebase/merge after #883
To this comment, https://github.com/bazelbuild/rules_scala/pull/883#discussion_r351089062
=> Explicitly label bazel 0.28.1

README.md, docs/scala_proto_library.md, test_version.sh
Upgrade scala v2.12 up to date with the latest v2.12 release train.
=> Bump scala 2.12 to v2.12.10

WORKSPACE, test/shell/test_scala_library.sh, test/src/main/scala/scalarules/test/scala_import/BUILD, test_expect_failure/scala_import/BUILD
=> Convert maven_jar to jvm_maven_import_external

AUTHORS
Adds myself to the AUTHORs file
https://github.com/bazelbuild/rules_scala/pull/865
=> authorship attribution for higherkindness/rules_scala design

WORKSPACE
update bazel-toolchains version
fix #901
=> update bazel-toolchains version

scala_proto/private/proto_to_scala_src.bzl
Removes an unused reference to compile_scala.
Cleaning up reference to this function in preparation for some larger refactoring/cleanup.
=> Remove unused reference to compile_scala

docs/customizable_phase.md
Fix doc on naming convention.
It should have been done with #953
=> Fix doc for new naming convention

scala_proto/scala_proto.bzl
Fix Travis Maven issue.
Should have been fixed by #968. Sorry I missed one place.
=> Fix maven server urls

scala/private/phases/phase_compile.bzl
remove unused method
cleanup post #974 
cc @borkaehw
=> remove unused method

test/proto_cross_repo_boundary/repo/BUILD.repo
Missed that one in #989.
@ittaiz ptal
=> Add load() for proto_library to @proto_cross_repo_boundary

README.md
remove spotify from adopters
They looked at Bazel but didn't adopt
Up-to-date adopters list
=> remove spotify from adopters

README.md
Update README.md with protobuf version matching actual dependencies
Version taken from scala/private/macros/scala_repositories.bzl.
Previous version from docs was conflicting with actual version of zlib that resulted in build failures when applying the instructions from the README.
=> Update README.md with protobuf version matching actual dependencies

README.md
Fixed protobuf URL in README
With the last protobuf version update in the README, the URL needs to include the 'v' prefix before the version.
=> Fixed protobuf URL in README

README.md, docs/coverage.md
Documentation for coverage support
I was specifically asked to add documentation for coverage support :)
=> Documentation for coverage support

README.md
update rules_scala version in the readme
fixes #1021
=> update rules_scala version in the readme

README.md, docs/publish_to_maven.md
resolves issue: https://github.com/bazelbuild/rules_scala/issues/921
=> Document how to publish to a maven repository

src/scala/io/bazel/rules_scala/tut_support/BUILD, test/tut/BUILD
=> Move scala_compiler to runtime deps

.bazelrc.travis, WORKSPACE
Not a lot of changes towards complying with bazel 3.4.1
=> [bazel-3.4.1] adjustments

scala/private/toolchain_deps/BUILD, scala/private/toolchain_deps/toolchain_dep_rules.bzl, scala/providers.bzl, scala/scala_toolchain.bzl
Removes unused and misleading leftovers
=> Cleanup ScalacProvider leftovers after toolchains refactoring

src/scala/io/bazel/rules_scala/tut_support/BUILD, tut_rule/BUILD, tut_rule/toolchain/BUILD, tut_rule/toolchain/toolchain.bzl, tut_rule/tut.bzl
Tut deps toolchain, part of #940
=> Add tut deps toolchain

scala/scalafmt/BUILD, scala/scalafmt/scalafmt_repositories.bzl, scala/scalafmt/toolchain/BUILD, scala/scalafmt/toolchain/toolchain.bzl
Scalafmt deps toolchain, part of #940
=> Add Scalafmt deps toolchain

jmh/BUILD, jmh/jmh.bzl, jmh/toolchain/BUILD, jmh/toolchain/toolchain.bzl, src/scala/io/bazel/rules_scala/jmh_support/BUILD
Deps toolchain for JMH, part of #940
=> Add jmh deps toolchain

third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/ScalaVersion.scala
=> Reduce analyzer warnings

third_party/repositories/scala_2_13.bzl
Align 2.13 version with #1143 #1139
=> Update ScalaTest, Scalactic and Scrooge libs for 2.13

CODEOWNERS, Governance.md
add  Vaidas Pilkauskas @liucijus as maintainer
Clarify ownership
=> add  Vaidas Pilkauskas @liucijus as maintainer

manual_test/scala_test_jvm_flags/EmptyTest.scala, test/HelloLibTest.scala, test/HelloLibTest2.scala, test/MacroTest.scala, test/ScalaTestData.scala, test/ScalaTestResourcesFromLocalTargetTest.scala, test/TestFilterTestA.scala, test/TestFilterTestB.scala, test/coverage/TestAll.scala, test/longnames/looooooongnaaaaaaame/anooooootherlooooooooongname/anooooootherlooooooooongname2/anooooootherlooooooooongname3/LongNamesTest.scala, test/phase/add_to_all_rules/PhaseTest.scala, test/proto/BlackListedProtoTest.scala, test/proto/CustomGeneratedObjectTest.scala, test/proto/PackProtosTest.scala, test/scala_test/A.scala, test/scalacopts/EchoMacroSettings.scala, test/scalafmt/formatted/formatted-test.scala, test/scalafmt/unformatted/unformatted-test.scala, test/src/main/scala/scalarules/test/io_utils/DeleteDirectoryTest.scala, test/src/main/scala/scalarules/test/neverlink/NeverlinkTest.scala, test/src/main/scala/scalarules/test/resource_jars/TestResourceJars.scala, test/src/main/scala/scalarules/test/resources/ScalaLibResourcesFromExternalScalaTest.scala, test/unstable/test.scala, third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinderTest.scala, third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/ScalaVersionTest.scala, third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/ScalacDependencyTest.scala, third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/StrictDepsTest.scala, third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/UnusedDependencyCheckerTest.scala
Update depraceted ScalaTest usages
=> Migrate from deprecated ScalaTest classes

WORKSPACE
Moves `org_typelevel__cats_core` under repositories
=> Move cats test dep to repositories

src/java/io/bazel/rulesscala/scalac/ReportableMainClass.java
=> Fix failed build reporting for Scala 2.11

src/java/io/bazel/rulesscala/specs2/BUILD
Use dependencies from testing toolchain
=> Use toolchain deps in specs2_test_discovery

scala/private/macros/scala_repositories.bzl
=> Update rules java to support Bazel 4.0.0

scala/scala_import.bzl, test/src/main/scala/scalarules/test/scala_import/BUILD
=> Fix scala_import file name collision in the same package

.bazelci/presubmit.yml, .travis.yml
Move examples testing to BuildKite
=> Move examples build to bk

scala/scala_import.bzl, test/src/main/scala/scalarules/test/scala_import/BUILD, test/src/main/scala/scalarules/test/scala_import/ScalaImportExposesJarsTest.scala
Reverts `scala_import` stamping due to #1200
=> Revert scala_import stamping

junit/junit.bzl, test/BUILD, testing/BUILD
=> Remove junit binds

jmh/BUILD, jmh/jmh.bzl
=> Remove JMH binds

tut_rule/BUILD, tut_rule/tut.bzl
=> Remove tut binds

scala/scala_import.bzl, test/shell/test_deps.sh, test_expect_failure/missing_direct_deps/external_deps/BUILD, test_expect_failure/missing_direct_deps/external_deps/Empty.java, test_expect_failure/missing_direct_deps/external_deps/UsesExternalDep.java
Fixes incorrect label stamping, I think I lost correct implementation during reverts.
=> Fix scala_import stamp label

scala_proto/private/scala_proto_aspect.bzl
Addresses comment: https://github.com/bazelbuild/rules_scala/pull/1243#discussion_r620124365
=> Remove incorect use of rstrip

manual_test/coverage_local_jacocorunner/expected-coverage.dat, manual_test/coverage_local_jacocorunner/test.sh, scripts/build_jacocorunner/build_jacocorunner.sh
Fixes for #1277.  Updated jacoco build script and test script to use specific tags and new test locations.  
I attempted to run these scripts, and ran into several issues.  After a lot of troubleshooting and debugging, I figured out the root causes and a few potential fixes.  Decided to submit a PR with these fixes, in case it helps anyone else attempting the same thing.
=> Fix build jacoco scripts

third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/ScalaVersionTest.scala, third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/StrictDepsTest.scala, third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/UnusedDependencyCheckerTest.scala
More cleanup: Removes redundant imports
=> Remove same package imports

README.md
Add twitter to the list of production users, cc: @wisechengyi
=> Add Twitter to production users

test/shell/test_toolchain.sh, test_expect_failure/compilers_javac_opts/BUILD
=> Remove use of deprecated java_toolchain to fix builds with Bazel master

src/scala/scripts/ScalaPBWorker.scala
Relates to https://github.com/bazelbuild/rules_scala/issues/1364
=> Fix deprecation warning in ScalaPBWorker

test/aspect/aspect.bzl
Needed to flip https://github.com/bazelbuild/bazel/issues/16196
=> Fix aspect test to recognize `@//` labels

test/shell/test_scala_proto_library.sh
Needed to flip https://github.com/bazelbuild/bazel/issues/16196
=> Fix test_scala_proto_library to accept @-prefixed labels

.bazelci/presubmit.yml, test/coverage_scalatest/expected-coverage.dat, test/coverage_specs2_with_junit/expected-coverage.dat
Update coverage expected data to match 5.3.1 output data
=> Update Coverage test data to Bazel 5.3.1

README.md
Add missing repository to load statement.
=> Fix setup guide in readme

examples/scala3/WORKSPACE, examples/testing/multi_frameworks_toolchain/WORKSPACE, examples/testing/scalatest_repositories/WORKSPACE, examples/testing/specs2_junit_repositories/WORKSPACE, scala/scala.bzl
Updates examples with updated setup macros from #1436
=> Update example Rules Scala setup macros

docs/testing.md, examples/testing/multi_frameworks_toolchain/BUILD, scala/scala.bzl, testing/BUILD, testing/testing.bzl
Simplifies deps setup for testing rules, in a similar way as in #1439
=> Add setup testing toolchain macro

jmh/jmh.bzl, scala/private/common_attributes.bzl, scala/private/rules/scala_test.bzl, scala/scalafmt/phase_scalafmt_ext.bzl
=> Update to be removed "host" cfg to "exec"

.github/workflows/workspace_snippet.sh
=> Fix external name in workspace snippet

README.md, WORKSPACE, dt_patches/test_dt_patches/WORKSPACE, examples/scala3/WORKSPACE, examples/testing/multi_frameworks_toolchain/WORKSPACE, examples/testing/scalatest_repositories/WORKSPACE, examples/testing/specs2_junit_repositories/WORKSPACE, scala/private/macros/scala_repositories.bzl, test_version/WORKSPACE.template, third_party/test/proto/WORKSPACE, tools/BUILD
Updating rule dependencies to make sure Rules Scala still works with newer versions
=> Update rule dependencies

README.md
Per https://github.com/bazelbuild/rules_scala/issues/1490 improve README.md
As a documentation wonk, I like documentation to minimize mistakes, and following the original documentation led to some copy/paste mistakes that had to be cleared up in the issues. 
When I figure out how to support Scala 3, I will update the documentation again with a better explanation.
=> Improve scala_config() documentation in README.md

examples/testing/multi_frameworks_toolchain/example/ScalaTestExampleTest.scala, examples/testing/scalatest_repositories/example/ExampleTest.scala
I was grepping through and found some examples that had the same typo.  
I found a typo and wanted to help out.
=> fix typo in example tests (Exmaple => Example)

third_party/repositories/repositories.bzl
For multiple `SCALA_VERSIONS` we will need to download artifacts for each version.
Some naming collision avoidance is needed.
=> Allow version-aware naming for artifact repositories

scala/private/macros/setup_scala_toolchain.bzl
These should also point to Scala version-specific artifacts.
See previous PR: #1561
#1290
=> Fix the remaining default providers in `setup_scala_toolchain`

README.md
Add Yobi AI to list of adopters. We are big supporters of this work :).
=> Add Yobi.ai to adopters

dt_patches/dt_patch_test.sh, dt_patches/test_dt_patches_user_srcjar/WORKSPACE, examples/scala3/WORKSPACE, scripts/README.md, scripts/create_repository.py, test/shell/test_examples.sh, test_thirdparty_version.sh, third_party/repositories/scala_3_6.bzl
Upgrade 3.6.3 -> 3.6.4
https://github.com/scala/scala3/issues/22728
=> Upgrade Scala 3.6 to 3.6.4

MODULE.bazel, dt_patches/dt_patch_test.sh, dt_patches/test_dt_patches_user_srcjar/MODULE.bazel, dt_patches/test_dt_patches_user_srcjar/WORKSPACE, examples/scala3/WORKSPACE, scripts/README.md, scripts/create_repository.py, test/shell/test_examples.sh, test_thirdparty_version.sh, third_party/repositories/repositories.bzl, third_party/repositories/scala_3_7.bzl
Add Scala 3.7.0 to the list of supported and tested version
=> Add Scala 3.7.0
